### ISSUE TITLE
Not working with DataBinding

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#103]
The inclusion of the new version of Kotlin introduced a bug where there is some incompatibility with data binding (discussion of the issue in the official bug tracker).

https://youtrack.jetbrains.com/issue/KT-8007

**Comment by hotchemi** [comment]
I hope JetBrains or Databinding team will fix it soon....

**Comment by diaz9557** [comment]
Is this issue resolve now ? I am current facing the same issue . Binding file is not generating . If you need more details then please ask .
