### ISSUE TITLE
Lint support causes clean to fail

### ISSUE THREAD

**Issue by viniciussoares** [hotchemi/PermissionsDispatcher#105]
Tested on 2.0.6 and 2.0.7.

`Information:Gradle tasks [clean, :app:generateProductionReleaseSources, :app:compileProductionReleaseSources]
:app:clean FAILED
Error:Execution failed for task ':app:clean'.
Unable to delete file: S:\dev\test\app\build\intermediates\exploded-aar\com.github.hotchemi\permissionsdispatcher\2.0.7\jars\lint.jar`

**Comment by hotchemi** [comment]
Thank you for your report!
@shiraji Any thoughts?

**Comment by shiraji** [comment]
Not sure. Let me find out what's going on. Sorry for inconvenience.

**Comment by shiraji** [comment]
OK, after I googled, I found [the same issue](https://github.com/JakeWharton/timber/issues/100) in Timber. According to the issue, this is a bug of AndroidStudio. Could you report to http://b.android.com ?

**Comment by hotchemi** [comment]
Oh boy...

@viniciussoares could u continue the development on the IntelliJ?
@shiraji Thank you for your quick catch!

**Comment by shiraji** [comment]
Actually, there is already report for this bug to http://b.android.com

https://code.google.com/p/android/issues/detail?id=190812

**Comment by viniciussoares** [comment]
@shiraji I'll fill the bug report. ^_^

Downgrade to 2.0.5 fixed the problem.

Looking forward to contribute to this awesome project :)

**Comment by hotchemi** [comment]
OK, we don't have a plan to remove lint check so keeping fingers crossed with google's quick fix.
Thanks for your report! I'll put this issue on a existing issue list.
