### ISSUE TITLE
verifyPermissions with empty grantResults returns true

### ISSUE THREAD

**Issue by ticofab** [hotchemi/PermissionsDispatcher#114]
Hi, and thanks for this great library! I am getting some strange behaviour on my Nexus5 running Android 6.0.1, updated March 2016. After the user has denied permission once (for both fine & coarse location), sometimes the method `verifyPermissions(int... grantResult)` is invoked with an empty `grantResult`. In that case, it won't find any PERMISSION_DENIED and it will return true, with the result that the method proceeds like if it has the permission.
I don't know why this happens, but it seems we can easily defend against it checking if `grantResult` is empty. Does it sound reasonable?

**Comment by hotchemi** [comment]
Thank you for the report.
Well, I'm not sure why it happens, but Would this be a solution for you?
https://github.com/hotchemi/PermissionsDispatcher/issues/68#issuecomment-183963565

**Comment by ticofab** [comment]
Yes, that would be a very simple check to prevent this problem. I haven't been able to figure out why grantResults is sometimes empty.. Thanks!

**Comment by hotchemi** [comment]
OK, I'll impl and release tonight!

**Comment by shiraji** [comment]
I'll send pull request in one minute @hotchemi

**Comment by hotchemi** [comment]
@ticofab I released 2.1.0. Please use it. Thx for your report!

**Comment by ticofab** [comment]
Thanks! I'll try it out and come back on this if I there's anything else to report :)
