### ISSUE TITLE
Does this library supports Application?

### ISSUE THREAD

**Issue by wawlian** [hotchemi/PermissionsDispatcher#115]
This is an extremely great library which can handle most of the situations in my app. But I wonder whether it can support handling runtime permissions in Application or not? If it does, how can I do with it？

**Comment by aurae** [comment]
Are you referring to the `Application` class? In that case, PermissionsDispatcher only supports the `@RuntimePermissions` annotation on sub-classes of `Activity` and `Fragment`, and in general I would advise against asking for runtime permissions anywhere else. You need to provide some context to the user, explaining to them why you are requesting a permission - doing it all right away in your `Application#onCreate` kinda defeats the point. Therefore, to reiterate, it is not supported.

**Comment by wawlian** [comment]
@aurae I got it and thank you for your kind reply.
