### ISSUE TITLE
Multiple permissions and Never ask again issue

### ISSUE THREAD

**Issue by Smeet123** [hotchemi/PermissionsDispatcher#125]
Lets say I am using camera feature and that requires 2 permission - 1. Camera and 2. Write External Storage. When it asks for both the permissions I Deny it. Again I press on camera capture button, it shows rational dialog explaining why it is required. Then I press on ALLOW on that dialog. So it first asks for the camera permission again and I checked NEver ask again and Deny it. Then it asks for Storage permission that I Allow. So in never ask again, So never ask again method is called in that I am showing one alert that you press on never ask again, and you have to manually turn that permission in from setting screen. Once I come back from setting screen and in onActivityResult, I am again calling check method for checking the permissions whether it is allowed or not. It again asks for Camera permission that is Ok (because previously I check never ask again and deny it) but it again ask for Storage permissions even though I previously allowed it.

For demo project, please use the link : https://github.com/hotchemi/PermissionsDispatcher/files/191383/Permission.zip

**Comment by Smeet123** [comment]
In generated java file it has a method : 

```
static void openCameraInstanceWithCheck(CameraFragment target) {
    if (PermissionUtils.hasSelfPermissions(target.getActivity(), PERMISSION_OPENCAMERAINSTANCE)) {
      target.openCameraInstance();
    } else {
      if (PermissionUtils.shouldShowRequestPermissionRationale(target.getActivity(), PERMISSION_OPENCAMERAINSTANCE)) {
        target.showRationaleForCamera(new OpenCameraInstancePermissionRequest(target));
      } else {
        target.requestPermissions(PERMISSION_OPENCAMERAINSTANCE, REQUEST_OPENCAMERAINSTANCE);
      }
    }
  }
```

In else part, every time it asks for both the permissions without checking whether any of the permission(s) is already granted or not. Please check if any of the permission(s) is/are granted and exclude it from target.requestPermissions() is it is already granted.

**Comment by Smeet123** [comment]
And due to this, blank screen is appeared as activity is created again. Don't know this is the internal issue of Android permission implementation. Really this is very unexpected behavior of Android. This can be resolved if you solve the above issue.

**Comment by hotchemi** [comment]
See https://github.com/hotchemi/PermissionsDispatcher/issues/69.

We follow the google's thoughts and implementation, so we don' plan to support. Thx.
