### ISSUE TITLE
how do slove this bug?

### ISSUE THREAD

**Issue by a1018875550** [hotchemi/PermissionsDispatcher#126]
![image](https://cloud.githubusercontent.com/assets/8246218/14096850/5d93f78c-f59e-11e5-8b25-84a61493c1d3.png)

![image](https://cloud.githubusercontent.com/assets/8246218/14096864/6d35d890-f59e-11e5-9e70-9675af5e35c1.png)

![image](https://cloud.githubusercontent.com/assets/8246218/14097885/ba952456-f5a8-11e5-8bcd-edab5dc8e43a.png)

I don't understand why?
How do I do?

**Comment by Smeet123** [comment]
Which Android studio version you are using? It is not compatible with Android  Studio 2.0 below versions. So please update your Android Studio to 2.0 beta version as stable version is not available. This above issue is in Android Studio and not in the Permission Dispatcher library.

**Comment by a1018875550** [comment]
I'm using the AndroidStudio 1.5.1
 this bug will not in Android Studio  2.0 beta version ?

**Comment by Smeet123** [comment]
No, in Android Studio 2.0 beta version it is working fine. But it has some lint issue also, just warning but it will not affect your working flow. Please refer entire conversation over here : https://github.com/hotchemi/PermissionsDispatcher/issues/124

**Comment by a1018875550** [comment]
Thanks
