### ISSUE TITLE
How to solve the problem ?

### ISSUE THREAD

**Issue by chond** [hotchemi/PermissionsDispatcher#129]
![image](https://cloud.githubusercontent.com/assets/10560641/14164048/7883b26c-f72e-11e5-8977-758fead105e7.png)

**Comment by shiraji** [comment]
Rebuild.

**Comment by chond** [comment]
![image](https://cloud.githubusercontent.com/assets/10560641/14164070/b7f78680-f72e-11e5-9e74-a421696fb71f.png)

Android studio 2.1 Preview 3

**Comment by chond** [comment]
Thanks
