### ISSUE TITLE
Entire class has warning "Generated onRequestPermissionsResult method not called"

### ISSUE THREAD

**Issue by sevar83** [hotchemi/PermissionsDispatcher#130]
I get my whole class underlined in red with this warning:

> "Generated onRequestPermissionsResult method not called [NeedOnRequestPermissionsResult]"

My code is fine. It compiles and runs but the editor warning keeps showing also on every class nested in a fragment or activity. Could you please fix it as I can't see my own real errors :D.

**Comment by hotchemi** [comment]
What version do you use?
And this issue is discussed in https://github.com/hotchemi/PermissionsDispatcher/issues/124

**Comment by sevar83** [comment]
Yes, appears to be the same issue. Using 2.1.0, but after upgrading to 2.1.1 it shows up again. I haven't try clean rebuild and Invalidate Caches because the project is quite large.

**Comment by hotchemi** [comment]
You should try, why not?

**Comment by sevar83** [comment]
Migration to 2.1.1 + Clean Rebuild + Invalidate Caches And Restart didn't fix it :S Do you know how can I disable that particular warning from Lint config?

**Comment by shiraji** [comment]
Could you try this? https://github.com/hotchemi/PermissionsDispatcher/issues/124#issuecomment-205289493

**Comment by sevar83** [comment]
@shiraji With your changeset it works fine. :+1:

**Comment by shiraji** [comment]
Cool. That is what I wanna know! I will send pull request with this change to fix this issue. Sorry for inconvenience. 

Since it may take time to release v2.1.2, you can use following code to disable this lint in v2.1.1

```groovy
android {
      lintOptions {
          disable 'NeedOnRequestPermissionsResult'
      }
}
```

Thanks a lot.

**Comment by gmfbilu** [comment]
oh my god,it tooks me a lot of time to fix this probleam.
