### ISSUE TITLE
Generated classes show up as errors in Android Studio 2.0

### ISSUE THREAD

**Issue by svenoaks** [hotchemi/PermissionsDispatcher#136]
All the generated classes like MainActivityPermissionsDispatcher show up as errors in Android Studio, even though app builds fine. I've closed and reopened everything, cleaned, etc. Any help?

**Comment by ecatix** [comment]
MainActivityPermissionsDispatcher doesn't seem to be generated with Android Studio 2.0. The build.gradle seems to be correct and the annotations are recognized. It must be something very simple.

**Comment by hotchemi** [comment]
I'm using Android Studio 2.0 preview 5 but it works fine. Have you tried rebuild project?

**Comment by ecatix** [comment]
Yes, rebuild did the trick. Thank you.

**Comment by hotchemi** [comment]
OK.
