### ISSUE TITLE
Why are there 2 dialogs presented?

### ISSUE THREAD

**Issue by chubbard** [hotchemi/PermissionsDispatcher#138]
When I add a @OnShowRationale to my class I see my rationale dialog which is the following:

```	
@OnShowRationale({Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION})
	protected void showRationaleForLocation(final PermissionRequest request) {
		new AlertDialog.Builder(getContext())
			.setMessage( getString(R.string.showMyLocation, getString(R.string.app_name)) )
			.setPositiveButton(R.string.allowPermission, new DialogInterface.OnClickListener() {
				@Override
				public void onClick(DialogInterface dialog, int which) {
					request.proceed();
				}
			})
			.setNegativeButton(R.string.denyPermission, new DialogInterface.OnClickListener() {
				@Override
				public void onClick(DialogInterface dialog, int which) {
					request.cancel();
				}
			})
			.setCancelable(false)
			.show();
	}
```

But after clicking allow it then shows another dialog that I can only guess is from Android OS asking the same question.  That dialog has a never show this to me again option on it, but the flow is not smooth.  I see a dialog asking me to grant permission.  I click allow, then a second dialog asks me the same thing but more generically, and I click allow again.

How can I suppress this 2nd AndroidOS dialog from showing?

**Comment by hotchemi** [comment]
See https://github.com/hotchemi/PermissionsDispatcher/issues/69 .
It's the problem of specification of the Android framework.
