### ISSUE TITLE
compileDebugJavaWithJavac fails with NoAnnotatedMethodsException when using AA Framework 

### ISSUE THREAD

**Issue by DINGJIN90** [hotchemi/PermissionsDispatcher#139]
compileDebugJavaWithJavac fails with NoAnnotatedMethodsException when using Android Annotation Framework

**Comment by DINGJIN90** [comment]
@hotchemi please take a look, thanks in advance!

**Comment by hotchemi** [comment]
@DINGJIN90 Sorry for the late, I think PermissionsDispatcher can't be used AA as AA creates new Activity...sorry.

**Comment by hotchemi** [comment]
See https://github.com/hotchemi/PermissionsDispatcher/issues/14 .

**Comment by gowravshekar** [comment]
Is there no solution to use Android Annotations with PermissionsDispatcher library?

**Comment by hotchemi** [comment]
I've not founded but could you try?

**Comment by shiraji** [comment]
AA now has a plugin feature https://github.com/excilys/androidannotations/wiki/Creating-an-AndroidAnnotations-plugin

I think you need to implement that in order to use both AA and PM.

**Comment by aurae** [comment]
Using @shiraji's suggestion would make the addition of PermissionsDispatcher's functionality to AA-based projects possible, I agree. I'll try to have a look at this soon, if I find the time and you guys don't mind.

**Comment by shiraji** [comment]
That would be awesome!

**Comment by hotchemi** [comment]
Interesting:-) It would be nice if we can provide the plugin as another dependency!

**Comment by chow890115** [comment]
I think u should develop another version to implement AA , and keep the current going is better:D
