### ISSUE TITLE
Can't use with AndroidAnnotations

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#14]
Because they use _ ends with classes actually.

**Comment by aurae** [comment]
Rather than checking the class name for "Activity" or "Fragment", the processor should check if the class annotated with `@RuntimePermissions` is a subtype of `android.app.Activity`, `android.app.Fragment` or `android.support.v4.app`.

In an annotation processor I recently wrote, I also only allow for some annotated elements to be of a certain type. Applying this to PermissionsDispatcher could look something like this:

```java

// PermissionsProcessor.java:
public synchronized void init(ProcessingEnvironment env) {
    // ...
   this.types = env.getTypeUtils();
   this.elements = env.getElementUtils();
}

// RuntimePermissionsAnnotatedElement.java:
class RuntimePermissionsAnnotatedElement {
    //...
    
    private final TypeMirror type;

    RuntimePermissionsAnnotatedElement(TypeElement element) {
        // ...
        type = element.asType();
    }
    
    public TypeMirror asType() {
        return type;
    }
}

// Now, to check if an annotated element is an Activity:
// "types" are the TypeUtils retrieved from the ProcessingEnvironment at init time
// "elements" are the ElementUtils retrieved from the ProcessingEnvironment at init time
TypeMirror activityType = types.getDeclaredType(elements.getTypeElement("android.app.Activity"));
RuntimePermissionsAnnotatedElement element = // ...
if (types.isSubType(element.asType(), activityType)) {
    // This is an activity sub-class.
} else if (//Same for Fragment) {
} else if (// Same for Support Fragment) {
} else {
    // Invalid element
    throw new WrongClassException(...);
}
```

**Comment by hotchemi** [comment]
Oh it's really nice idea!

**Comment by Fleker** [comment]
Any update on this? I also ran into the `WrongClassException` when trying to compile one of my activities that was an `AppCompatActivity`. I don't know why that was happening, but a fix would be appreciated.

**Comment by hotchemi** [comment]
@Fleker Do u use AndroidAnnotations?

**Comment by Fleker** [comment]
I spent some more time and figured out my problem. I think it had to do with trying to annotate a private method and it broke on compilation. Now my issue has been resolved.

**Comment by hotchemi** [comment]
OK but the error message is wired...

**Comment by hotchemi** [comment]
I'm gonna delete validation. If user don't annotate proper class, it causes compile error so it doesn't matter.

**Comment by WonderCsabo** [comment]
@hotchemi i cannot say it is a good idea. Generating a non-compilable class is not user friendly, and should be always avoided. Moreover, it will not be clear to the user that the processor is buggy, or she/he used it in a wrong way.

Why don't you just apply the easy fix which was already proposed?

**Comment by hotchemi** [comment]
@WonderCsabo Thanks, I changed my mind!

**Comment by hotchemi** [comment]
I realized This implementation can't catch nested super class problem.
I mean if the target extends AppCompatActivity it doesn't go well in this case...

**Comment by WonderCsabo** [comment]
@hotchemi I think you are wrong. `types.isSubType(element.asType(), activityType))` will return true if the actual element is a subclass of `AppCompatActivity`.

**Comment by hotchemi** [comment]
@WonderCsabo Oh really? I tried to add [this](https://github.com/hotchemi/PermissionsDispatcher/blob/fix-14/permissionsdispatcher-processor/src/test/java/permissions/dispatcher/processor/data/Source.java#L839-L858) test data but it doesn't go well...anything wrong?

**Comment by WonderCsabo** [comment]
I think the test data is OK. However `isSubTypeOf` definitely works on multi-level inheritance. It should as defined in the JLS, but i also double checked. Maybe you are calling it wrong somewhere.

**Comment by hotchemi** [comment]
Oh thanks.
Actually we define [checking](https://github.com/hotchemi/PermissionsDispatcher/blob/fix-14/permissionsdispatcher-processor/src/main/java/permissions/dispatcher/processor/PermissionsProcessor.java#L69-L73) in these lines and using them in these [lines](https://github.com/hotchemi/PermissionsDispatcher/blob/fix-14/permissionsdispatcher-processor/src/main/java/permissions/dispatcher/processor/ClassType.java#L14-L19)...

**Comment by hotchemi** [comment]
@WonderCsabo @aurae 
I realized wired thing.
Instead of original extended Activity, I tried to use actual FragmentActivity, and the test passed.
With debug, it seems that original activity doesn't have inheritance information, I'm not sure why...

**Comment by hotchemi** [comment]
It might be the bug of compiler-testing.

**Comment by WonderCsabo** [comment]
In your test data you extend the outer class with the inner class. Am I
seeing this right?

**Comment by hotchemi** [comment]
`static class SuperActivity extends Activity {}`
I think it must extends android.app.Activity right? It's just static.

**Comment by WonderCsabo** [comment]
You deleted the commit unfortunately, but i think your test case looked like this:
```java
public class MyChildClass extends MyChildClass.SuperClass {
	
	static class SuperClass extends Object {}
}
```
This cannot compile, because of cyclic inheritance. So that is why `isSuperType` returned `false`.

**Comment by hotchemi** [comment]
@WonderCsabo Oh sorry that was my mistake...

**Comment by BukT0p** [comment]
Hi, its me, again. Tried to use this lib one more time and got this message:
`Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> permissions.dispatcher.processor.exceptions.NotDefinedException: @NeedsPermission or @NeedsPermissions are not defined`

I have my fragment generated and dispatcher is generated too. But there is no code for calling the dispatcher inside the generated fragment. I can't find much details on that in log.

**Comment by hotchemi** [comment]
Could u paste the code of fragment? I guess you don't defined @NeedsPermission.

**Comment by BukT0p** [comment]
As stated before I have my TestFragment_ generated as well as TestFragmentPermissionsDispatcher but in TestFragment_ there are no references to Dispatcher. I have compilation error https://gist.github.com/BukT0p/572e431288b698f25de0

**Comment by hotchemi** [comment]
@BukT0p Umm it's make sense because u don't use original fragment. Could u send pull request?
