### ISSUE TITLE
NoParametersAllowedException on Gradle build

### ISSUE THREAD

**Issue by embydextrous** [hotchemi/PermissionsDispatcher#141]
Execution failed for task ':app:compileDebugJavaWithJavac'.
> permissions.dispatcher.processor.exception.NoParametersAllowedException: Method 'permissionDeclined()' must not have any parameters.

**Comment by shiraji** [comment]
> Method 'permissionDeclined()' must not have any parameters.

**Comment by embydextrous** [comment]
`package com.listup.android.activity;

import android.Manifest;
import android.accounts.Account;
import android.accounts.AccountManager;
import android.animation.Animator;
import android.animation.AnimatorListenerAdapter;
import android.annotation.SuppressLint;
import android.app.Dialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.graphics.Color;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.CardView;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.view.animation.AccelerateInterpolator;
import android.view.animation.DecelerateInterpolator;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import android.widget.Toast;
import com.afollestad.materialdialogs.DialogAction;
import com.afollestad.materialdialogs.MaterialDialog;
import com.daimajia.androidanimations.library.Techniques;
import com.daimajia.androidanimations.library.YoYo;
import com.dd.morphingbutton.MorphingButton;
import com.facebook.AccessToken;
import com.facebook.CallbackManager;
import com.facebook.FacebookCallback;
import com.facebook.FacebookException;
import com.facebook.FacebookSdk;
import com.facebook.drawee.backends.pipeline.Fresco;
import com.facebook.drawee.backends.pipeline.PipelineDraweeController;
import com.facebook.drawee.view.SimpleDraweeView;
import com.facebook.imagepipeline.common.ResizeOptions;
import com.facebook.imagepipeline.request.ImageRequest;
import com.facebook.imagepipeline.request.ImageRequestBuilder;
import com.facebook.login.LoginManager;
import com.facebook.login.LoginResult;
import com.google.android.gms.analytics.HitBuilders;
import com.listup.android.R;
import com.listup.android.TrovoApplication;
import com.listup.android.api.ServiceGenerator;
import com.listup.android.api.request.LoginAccessTokenBody;
import com.listup.android.api.request.LoginRequestBody;
import com.listup.android.api.response.user.LoginResponse;
import com.listup.android.helper.CleverTapWrapper;
import com.listup.android.model.UserInfo;
import com.listup.android.util.Constants;
import com.listup.android.util.NetUtils;
import com.listup.android.util.PrefUtils;
import com.listup.android.util.StringUtils;
import com.listup.android.util.Utils;
import com.sinch.verification.CodeInterceptionException;
import com.sinch.verification.Config;
import com.sinch.verification.ServiceErrorException;
import com.sinch.verification.SinchVerification;
import com.sinch.verification.Verification;
import com.sinch.verification.VerificationListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

import butterknife.BindColor;
import butterknife.BindString;
import butterknife.BindView;
import butterknife.ButterKnife;
import butterknife.OnClick;
import permissions.dispatcher.NeedsPermission;
import permissions.dispatcher.OnNeverAskAgain;
import permissions.dispatcher.OnPermissionDenied;
import permissions.dispatcher.OnShowRationale;
import permissions.dispatcher.PermissionRequest;
import permissions.dispatcher.RuntimePermissions;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

@RuntimePermissions
public class FBLoginActivity extends AppCompatActivity {

    @BindView(R.id.FBLoginButton)
    Button fbLoginButton;
    @BindView(R.id.listup_trademark_imageview)
    ImageView listupIv;
    @BindView(R.id.MainLayoutLogin)
    RelativeLayout mainLayoutLogin;
    @BindView(R.id.userInputLayout)
    RelativeLayout userInputLayout;
    @BindView(R.id.userPicturesLayout)
    FrameLayout userPicturesLayout;
    @BindView(R.id.cover_card)
    CardView coverCard;
    @BindView(R.id.cover_image)
    SimpleDraweeView coverImage;
    @BindView(R.id.profile_image)
    SimpleDraweeView profileImage;
    @BindView(R.id.name_text_view)
    TextView nameView;
    @BindView(R.id.ed_email)
    AutoCompleteTextView emailEditText;
    @BindView(R.id.ed_mobile)
    EditText mobileEditText;
    @BindView(R.id.verify_phone)
    MorphingButton verifyButton;
    @BindView(R.id.positive_button)
    Button positiveButton;
    @BindView(R.id.negative_button)
    Button negativeButton;
    @BindString(R.string.error_msg_no_network)
    String noNetworkMessage;
    @BindString(R.string.access_token_error_message)
    String accessTokenErrorMessage;
    @BindString(R.string.login_failure_message)
    String loginFailureMessage;
    @BindString(R.string.wait_title)
    String waitTitle;
    @BindString(R.string.welcome_message)
    String welcomeMessage;
    @BindString(R.string.skip)
    String skipText;
    @BindString(R.string.submit)
    String submitText;
    @BindString(R.string.cancel)
    String cancelText;
    @BindString(R.string.mobile_verification_wait_message)
    String mobileVerificationWaitMessage;
    @BindColor(R.color.accent)
    int colorAccent;

    private Intent preserveIntent;
    private CallbackManager callbackManager;
    private AccessToken accessToken;
    private boolean mobileVerified = false;
    private boolean isVerifyingMobile = false;
    private UserInfo userInfo;
    protected static final String TAG = FBLoginActivity.class.getSimpleName();
    private static final String[] permissions = {"public_profile", "email", "user_birthday", "user_friends"};
    private static final String[] additionalPermissions = {"user_friends"};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        initStatusBarColor();
        super.onCreate(savedInstanceState);
        FacebookSdk.sdkInitialize(getApplicationContext());
        callbackManager = CallbackManager.Factory.create();
        getLoginManagerInstance();
        preserveIntent = getIntent();
        setContentView(R.layout.activity_login_fb);
        ButterKnife.bind(this);
        initViews();
    }

    private void initStatusBarColor() {
        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            Window window = getWindow();
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            window.setStatusBarColor(Color.parseColor("#00000000"));
            window.addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
        }
    }

    private void getLoginManagerInstance() {
        LoginManager.getInstance().registerCallback(callbackManager, new FacebookCallback<LoginResult>() {
            @Override
            public void onSuccess(LoginResult loginResult) {
                if (loginResult.getAccessToken().getPermissions().contains("user_friends")) {
                    accessToken = loginResult.getAccessToken();
                    login();
                } else {
                    LoginManager.getInstance().logInWithReadPermissions(FBLoginActivity.this, Arrays.asList(additionalPermissions));
                }
            }

            @Override
            public void onCancel() {
                if (!NetUtils.isNetworkConnected(getApplicationContext()))
                    Toast.makeText(FBLoginActivity.this, noNetworkMessage, Toast.LENGTH_SHORT).show();
                else {
                    AccessToken accessToken = AccessToken.getCurrentAccessToken();
                    if (accessToken != null && accessToken.getToken() != null)
                        login();
                    else
                        Toast.makeText(FBLoginActivity.this, accessTokenErrorMessage, Toast.LENGTH_LONG).show();
                }
            }

            @Override
            public void onError(FacebookException exception) {
                Toast.makeText(FBLoginActivity.this, loginFailureMessage, Toast.LENGTH_LONG).show();
            }
        });
    }

    private void initViews(){
        fbLoginButton.getLayoutParams().width= (int) (Utils.getScreenWidth(this)*0.75);
        fbLoginButton.setPadding((int) (Utils.getScreenWidth(this)*0.12),0,0,0);
        listupIv.getLayoutParams().width = (int) (Utils.getScreenWidth(this) * 0.56);
        listupIv.getLayoutParams().height = (int) (Utils.getScreenWidth(this) * 0.56 * (32.0 / 49.0));
        listupIv.requestLayout();
    }

    @OnClick(R.id.FBLoginButton)
    public void onFacebookButtonClick() {
        AccessToken accessToken = AccessToken.getCurrentAccessToken();
        if (accessToken != null) {
            LoginManager.getInstance().logOut();
        }
        LoginManager.getInstance().logInWithReadPermissions(FBLoginActivity.this, Arrays.asList(permissions));
    }

    private void login() {
        final MaterialDialog dialog = new MaterialDialog.Builder(this)
                .content(waitTitle)
                .progress(true, 0)
                .progressIndeterminateStyle(true)
                .show();
        LoginAccessTokenBody loginAccessTokenBody = new LoginAccessTokenBody(new LoginAccessTokenBody.User(accessToken.getToken()));
        ServiceGenerator.generateService(this).login(loginAccessTokenBody).enqueue(new Callback<LoginResponse>() {

            @Override
            public void onResponse(Call<LoginResponse> call, Response<LoginResponse> response) {
                if (dialog != null)
                    dialog.dismiss();
                if (response.body() != null) {
                    LoginResponse loginResponse = response.body();
                    if (loginResponse.getUserInfo() == null) {
                        Toast.makeText(getApplicationContext(), loginFailureMessage, Toast.LENGTH_SHORT).show();
                        return;
                    }
                    userInfo = loginResponse.getUserInfo();
                    if (userInfo.getEmail() != null && !userInfo.getEmail().isEmpty() && userInfo.getMobile() != null && !userInfo.getMobile().isEmpty()) {
                        savePreferences();
                        goToMainActivity();
                    } else
                        showUserInfoInputScreen();
                } else
                    Toast.makeText(getApplicationContext(), loginFailureMessage, Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onFailure(Call<LoginResponse> call, Throwable t) {
                if (dialog != null)
                    dialog.dismiss();
                Toast.makeText(getApplicationContext(), loginFailureMessage, Toast.LENGTH_SHORT).show();
            }
        });
    }

    private void savePreferences() {
        PrefUtils.saveObjectToPrefs(PrefUtils.PREF_KEY_USER_INFO, userInfo, FBLoginActivity.this);
        PrefUtils.saveToken(FBLoginActivity.this, userInfo.getToken());
        PrefUtils.saveUserId(FBLoginActivity.this, userInfo.getUserid());
        PrefUtils.putInt(getApplicationContext(), PrefUtils.PREF_KEY_SIGN_IN_STATUS, Constants.SIGN_IN_STATUS_LOGGED_IN);
    }

    private ArrayList<String> getEmailAccounts() {
        AccountManager manager = (AccountManager) getSystemService(ACCOUNT_SERVICE);
        List<Account> accounts = Arrays.asList(manager.getAccountsByType("com.google"));
        ArrayList<String> userEmails = new ArrayList<>();
        for (Account account:accounts)
            userEmails.add(account.name);
        return userEmails;
    }

    private void showUserInfoInputScreen() {
        initUserInputViews();
        setPictures();
        setupEditTexts();
        setUpButtons();
    }

    private void initUserInputViews() {
        YoYo.with(Techniques.SlideOutLeft).duration(400).interpolate(new AccelerateInterpolator()).withListener(new com.nineoldandroids.animation.Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(com.nineoldandroids.animation.Animator animation) {

            }

            @Override
            public void onAnimationEnd(com.nineoldandroids.animation.Animator animation) {
                mainLayoutLogin.setVisibility(View.GONE);
            }

            @Override
            public void onAnimationCancel(com.nineoldandroids.animation.Animator animation) {

            }

            @Override
            public void onAnimationRepeat(com.nineoldandroids.animation.Animator animation) {

            }
        }).playOn(mainLayoutLogin);
        YoYo.with(Techniques.SlideInRight).interpolate(new DecelerateInterpolator()).duration(400).withListener(new com.nineoldandroids.animation.Animator.AnimatorListener() {
            @Override
            public void onAnimationStart(com.nineoldandroids.animation.Animator animation) {
                userInputLayout.setVisibility(View.VISIBLE);
            }

            @Override
            public void onAnimationEnd(com.nineoldandroids.animation.Animator animation) {

            }

            @Override
            public void onAnimationCancel(com.nineoldandroids.animation.Animator animation) {

            }

            @Override
            public void onAnimationRepeat(com.nineoldandroids.animation.Animator animation) {

            }
        }).playOn(userInputLayout);
        int height = (int) (Utils.getScreenHeight(this) * 0.30);
        userPicturesLayout.getLayoutParams().height = height;
        userPicturesLayout.requestLayout();
        coverCard.getLayoutParams().height = (int) (height * 0.7);
        coverCard.requestLayout();
        profileImage.getLayoutParams().height = (int) (height * 0.6);
        profileImage.getLayoutParams().width = (int) (height * 0.6);
        profileImage.requestLayout();
        nameView.setText(String.format(welcomeMessage, userInfo.getFullname().substring(0, userInfo.getFullname().indexOf(" "))));
    }

    private boolean hasEmail(UserInfo userInfo){
        return (userInfo.getEmail()!=null&&!userInfo.getEmail().isEmpty());
    }

    private void setUpButtons() {
        negativeButton.setText(hasEmail(userInfo) ? skipText : cancelText);
        positiveButton.setText(submitText);
        negativeButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                HashMap<String, Object> skipVerifyAction = new HashMap<>();
                skipVerifyAction.put("User Id", userInfo.getUserid());
                skipVerifyAction.put("email", userInfo.getEmail());
                skipVerifyAction.put("hasEmail", hasEmail(userInfo) ? "YES" : "NO");
                CleverTapWrapper.pushEvent(skipVerifyAction, CleverTapWrapper.EVENT_SKIP_CANCEL_PRESSED, getApplicationContext());
                if (hasEmail(userInfo)) {
                    if (isVerifyingMobile) {
                        Toast.makeText(getApplicationContext(), mobileVerificationWaitMessage, Toast.LENGTH_SHORT).show();
                        return;
                    }
                    savePreferences();
                    goToMainActivity();
                } else {
                    PrefUtils.getSharedPreferences(FBLoginActivity.this).edit().clear().commit();
                    android.os.Process.killProcess(android.os.Process.myPid());
                }
            }
        });
        positiveButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (isVerifyingMobile) {
                    Toast.makeText(getApplicationContext(), mobileVerificationWaitMessage, Toast.LENGTH_SHORT).show();
                    return;
                }

                HashMap<String, Object> skipVerifyAction = new HashMap<>();
                skipVerifyAction.put("User Id", userInfo.getUserid());
                skipVerifyAction.put("email", userInfo.getEmail());
                CleverTapWrapper.pushEvent(skipVerifyAction, CleverTapWrapper.EVENT_SUBMIT_CLICKED, getApplicationContext());

                if (emailEditText.getText() == null || emailEditText.getText().toString().isEmpty()) {
                    emailEditText.setError("Email cannot be empty.");
                    return;
                }
                if (!StringUtils.isValidEmail(emailEditText.getText().toString())) {
                    emailEditText.setError("Email entered by you is invalid.");
                    return;
                }
                if (mobileEditText.getText() != null && !mobileEditText.getText().toString().trim().isEmpty() && mobileEditText.getText().toString().length() != 10) {
                    mobileEditText.setError("Phone number is not valid.");
                    return;
                }
                if (mobileEditText.getText() != null && !mobileEditText.getText().toString().trim().isEmpty() && mobileEditText.getText().length() == 10) {
                    if (mobileVerified) {
                        updateUserDetails(emailEditText.getText().toString(), mobileEditText.getText().toString());
                        return;
                    } else {
                        Toast.makeText(getApplicationContext(), "Please verify mobile number first.", Toast.LENGTH_SHORT).show();
                        return;
                    }
                }
                updateUserDetails(emailEditText.getText().toString(), "");
            }
        });
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,@NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        FBLoginActivityPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
    }

    private void updateUserDetails(String email, String mobile) {
        final Dialog dialog = new MaterialDialog.Builder(this)
                .content("Updating your details...")
                .progress(true, 0)
                .progressIndeterminateStyle(true)
                .show();
        LoginRequestBody loginRequestBody = new LoginRequestBody(new LoginRequestBody.User(accessToken.getToken(), email, mobile));
        Call<LoginResponse> loginResponseCall = ServiceGenerator.generateService(this).loginUpdate(userInfo.getToken(), loginRequestBody, userInfo.getUserid());
        loginResponseCall.enqueue(new Callback<LoginResponse>() {
            @Override
            public void onResponse(Call<LoginResponse> call, Response<LoginResponse> response) {
                if (dialog != null && !dialog.isShowing())
                    dialog.dismiss();
                if (response.body() != null) {
                    LoginResponse loginResponse = response.body();
                    if (loginResponse.getUserInfo() == null) {
                        Toast.makeText(getApplicationContext(), "Failed to Update Details", Toast.LENGTH_SHORT).show();
                        return;
                    }
                    userInfo = loginResponse.getUserInfo();
                    savePreferences();
                    goToMainActivity();
                } else {
                    try {
                        Toast.makeText(FBLoginActivity.this,
                                "Unable to login in. " + response.errorBody().string(),
                                Toast.LENGTH_SHORT).show();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }

            @Override
            public void onFailure(Call<LoginResponse> call, Throwable t) {
                if (dialog != null && dialog.isShowing())
                    dialog.dismiss();
                Toast.makeText(FBLoginActivity.this, "Failed to update details.", Toast.LENGTH_SHORT).show();
            }
        });

    }

    private void setupEditTexts() {
        ArrayAdapter<String> adapter = new ArrayAdapter<>(this, R.layout.select_account, R.id.autoCompleteItem, getEmailAccounts());
        emailEditText.setAdapter(adapter);
        verifyButton.setBackgroundResource(R.drawable.button_green_solid);
        verifyButton.setVisibility(View.GONE);
        verifyButton.setTranslationX(300);
        verifyButton.setAlpha(0f);
        if (hasEmail(userInfo)) {
            emailEditText.setText(userInfo.getEmail());
            emailEditText.setEnabled(false);
            mobileEditText.requestFocus();
        } else {
            emailEditText.requestFocus();
            emailEditText.setEnabled(true);
        }
        mobileEditText.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                if (isVerifyingMobile) return;
                if (s.length() == 10) {
                    verifyButton.animate().setDuration(300).setInterpolator(new DecelerateInterpolator()).alpha(1.0f).translationX(0).setListener(new AnimatorListenerAdapter() {
                        @Override
                        public void onAnimationStart(Animator animation) {
                            super.onAnimationStart(animation);
                            verifyButton.setVisibility(View.VISIBLE);
                        }
                    }).start();
                    verifyButton.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View v) {
                            if (!isVerifyingMobile && !mobileVerified)
                                FBLoginActivityPermissionsDispatcher.verifyMobileActionWithCheck(FBLoginActivity.this);
                        }
                    });
                } else {
                    verifyButton.animate().setDuration(300).setInterpolator(new AccelerateInterpolator()).alpha(0.0f).translationX(300).setListener(new AnimatorListenerAdapter() {
                        @Override
                        public void onAnimationEnd(Animator animation) {
                            super.onAnimationEnd(animation);
                            verifyButton.setVisibility(View.GONE);
                        }
                    }).start();
                    verifyButton.setOnClickListener(null);
                }
            }

            @Override
            public void afterTextChanged(Editable s) {

            }
        });
    }

    @NeedsPermission({Manifest.permission.CALL_PHONE, Manifest.permission.READ_PHONE_STATE})
    void verifyMobileAction() {
        startVerification(mobileEditText.getText().toString());
        HashMap<String, Object> verifyMobileAction = new HashMap<>();
        verifyMobileAction.put("User Id", userInfo.getUserid());
        verifyMobileAction.put("email", userInfo.getEmail());
        verifyMobileAction.put("mobile number", mobileEditText.getText().toString());
        CleverTapWrapper.pushEvent(verifyMobileAction, CleverTapWrapper.EVENT_VERIFY_MOBILE, this);
    }

    @OnShowRationale({Manifest.permission.CALL_PHONE, Manifest.permission.READ_PHONE_STATE})
    void showPermissionRationale(final PermissionRequest request) {
        final boolean[] dialogHandledPositively = {false};
        MaterialDialog callPermission = new MaterialDialog.Builder(this)
                .title("Mobile Number Verification").content("Kindly allow us to verify your number by a missed call.")
                .positiveText("Allow").onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog materialDialog,@Nullable DialogAction dialogAction) {
                        dialogHandledPositively[0] = true;
                        materialDialog.dismiss();
                        request.proceed();
                    }
                })
                .build();
        callPermission.setOnDismissListener(new DialogInterface.OnDismissListener() {
            public void onDismiss(DialogInterface dialog) {
                if (!dialogHandledPositively[0]) {
                    request.cancel();
                    Toast.makeText(FBLoginActivity.this, "Can't verify your mobile without these permissions", Toast.LENGTH_LONG).show();
                }
            }
        });
        callPermission.getWindow().getAttributes().windowAnimations = R.style.MyAnimation_Window;
        callPermission.show();
    }

    @OnNeverAskAgain({Manifest.permission.CALL_PHONE, Manifest.permission.READ_PHONE_STATE})
    @OnPermissionDenied({Manifest.permission.CALL_PHONE, Manifest.permission.READ_PHONE_STATE})
    void permissionDeclined(int permissionCode) {
        Toast.makeText(this, "Call permission is necessary to verify mobile number.", Toast.LENGTH_SHORT).show();
    }

    private void setPictures() {
        String cover = userInfo.getCover()!=null&&!userInfo.getCover().isEmpty()?userInfo.getCover():userInfo.getSocialMediaPic();
        ImageRequest coverRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(cover))
                .setResizeOptions(new ResizeOptions(Utils.getScreenWidth(this), (int) (Utils.getScreenHeight(this)*0.21))).build();
        PipelineDraweeController coverController = (PipelineDraweeController) Fresco.newDraweeControllerBuilder().setOldController(coverImage.getController())
                .setImageRequest(coverRequest).build();
        coverImage.setController(coverController);
        ImageRequest profileRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(userInfo.getSocialMediaPic()))
                .setResizeOptions(new ResizeOptions(Utils.dpToPx(96), Utils.dpToPx(96))).build();
        PipelineDraweeController profileController = (PipelineDraweeController) Fresco.newDraweeControllerBuilder().setOldController(profileImage.getController())
                .setImageRequest(profileRequest).build();
        profileImage.setController(profileController);

        HashMap<String, Object> profileUpdate = new HashMap<>();
        profileUpdate.put("Id", userInfo.getUserid());
        profileUpdate.put("Name", userInfo.getFullname());
        profileUpdate.put("Email", userInfo.getEmail());
        CleverTapWrapper.pushProfile(profileUpdate, this);
    }

    @SuppressLint("SetTextI18n")
    private void startVerification(String phoneNumber) {
        Config config = SinchVerification.config().applicationKey(getResources().getString(R.string.sinch_flash_verification_key)).context(getApplicationContext()).build();
        VerificationListener listener = new MyVerificationListener();
        Verification verification = SinchVerification.createFlashCallVerification(config, "+91" + phoneNumber, listener);
        isVerifyingMobile = true;
        verifyButton.setText("00:30");
        Thread t = new Thread() {
            int i = 29;

            @Override
            public void run() {
                try {
                    while (isVerifyingMobile && i > 0) {
                        Thread.sleep(1000);
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                if (isVerifyingMobile) {
                                    String ss;
                                    if (i % 60 == 0) ss = "00";
                                    else if (i % 60 < 10) ss = "0" + i % 60;
                                    else ss = i % 60 + "";
                                    verifyButton.setText("00:" + ss);
                                    i--;
                                }
                            }
                        });
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };

        t.start();
        verification.initiate();
    }

    private class MyVerificationListener implements VerificationListener {
        @Override
        public void onInitiated() {
        }

        @SuppressLint("SetTextI18n")
        @Override
        public void onInitiationFailed(Exception e) {
            isVerifyingMobile = false;
            verifyButton.setText("RETRY");
        }

        @Override
        public void onVerified() {
            MorphingButton.Params circle = MorphingButton.Params.create()
                    .duration(500)
                    .cornerRadius(Utils.dpToPx(36))
                    .width(Utils.dpToPx(36))
                    .height(Utils.dpToPx(36))
                    .color(colorAccent)
                    .icon(R.drawable.ic_done_new);
            verifyButton.setText("");
            verifyButton.morph(circle);
            isVerifyingMobile = false;
            mobileVerified = true;
            mobileEditText.setEnabled(false);
            verifyButton.setEnabled(false);
            if(StringUtils.isValidEmail(emailEditText.getText().toString()))
                updateUserDetails(emailEditText.getText().toString(), mobileEditText.getText().toString());
        }

        @SuppressLint("SetTextI18n")
        @Override
        public void onVerificationFailed(Exception e) {
            isVerifyingMobile = false;
            verifyButton.setText("RETRY");
            if (e instanceof CodeInterceptionException) {
                Toast.makeText(FBLoginActivity.this, "Intercepting the verification call automatically failed.", Toast.LENGTH_LONG).show();
            } else if (e instanceof ServiceErrorException) {
                Toast.makeText(FBLoginActivity.this, "Please try again.", Toast.LENGTH_LONG).show();
            } else {
                Toast.makeText(FBLoginActivity.this, "Please check your network and try again.", Toast.LENGTH_LONG).show();
            }
        }

    }

    private void goToMainActivity() {
        TrovoApplication.getDefaultTracker().send(new HitBuilders.EventBuilder()
                .setCategory(getResources().getString(R.string.category_login))
                .setAction(getResources().getString(R.string.action_logged_in))
                .build());
        Intent myIntent = new Intent();
        myIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
        if (preserveIntent != null)
            switch (preserveIntent.getIntExtra(Constants.WHICH_ACTIVITY_TO_START, -1)) {
                case Constants.START_TROVO_ACTIVITY:
                    myIntent.setClass(getApplicationContext(), TrovoActivity.class);
                    myIntent.setData(preserveIntent.getData());
                    myIntent.setAction(preserveIntent.getAction());
                    break;
                case Constants.START_ITEM_DESCRIPTION_ACTIVITY:
                    myIntent.setClass(getApplicationContext(), ItemDescriptionActivity.class);
                    myIntent.setData(preserveIntent.getData());
                    myIntent.setAction(preserveIntent.getAction());
                    break;
                case Constants.START_ADD_PRODUCT_ACTIVITY:
                    myIntent.setClass(getApplicationContext(), ProductAddActivity.class);
                    myIntent.setData(preserveIntent.getData());
                    myIntent.setAction(preserveIntent.getAction());
                    break;
                default:
                    myIntent.setClass(getApplicationContext(), TrovoActivity.class);
                    break;
            }
        finish();
        startActivity(myIntent);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        callbackManager.onActivityResult(requestCode, resultCode, data);
    }
}
`

**Comment by embydextrous** [comment]
I don't want to shift to any other library for permissions. It was working very fine. And all of a sudden this bug. I tried rebuild project, clean, invalidate caches.

**Comment by aurae** [comment]
The issue is right in the error message: Methods annotated with @OnPermissionDenied must not have parameters, yours does, hence the error.

**Comment by shiraji** [comment]
Could you remove the parameter of `permissionDeclined` like this?

```java
@OnNeverAskAgain({Manifest.permission.CALL_PHONE, Manifest.permission.READ_PHONE_STATE})
@OnPermissionDenied({Manifest.permission.CALL_PHONE, Manifest.permission.READ_PHONE_STATE})
void permissionDeclined() {
    Toast.makeText(this, "Call permission is necessary to verify mobile number.", Toast.LENGTH_SHORT).show();
}
```

BTW, this is the first time i see one method have  `@OnNeverAskAgain` and `@OnPermissionDenied`. Do you really want to do that?

**Comment by embydextrous** [comment]
Thanks. I got the point.
