### ISSUE TITLE
Rationale dialog first not shown after reinstall

### ISSUE THREAD

**Issue by Rainer-Lang** [hotchemi/PermissionsDispatcher#142]
I discovered something strange.
When I reinstall the app - the first time a permission rationale dialog should be shown, only the Android default permission dialog is shown. After deny/allow (it doesn't matter what is chossen) ALL other permission rationale dialogs are shown (for all other or same permissions).

**Comment by hotchemi** [comment]
> When I reinstall the app - the first time a permission rationale dialog should be shown

I think it's not correct, for the first time permission dialog should be shown to user.

**Comment by hotchemi** [comment]
Please reopen if you're still in trouble.

**Comment by Rainer-Lang** [comment]
@hotchemi I maybe I don't understand it.... I have for all permissions rationale dialogs. These dialogs are essential for the users to grant permissions in the next dialog - the Android system permission dialog.

BUT for the very first time when I have to ask user for permission, the rationale dialog isn't be shown. So the user gets only the Android permission dialog without any explanation. 
For me there is something wrong. For my understanding, there should be every time a rationale dialog - simple because I have such rationale dialogs for all permissions.

**Comment by hotchemi** [comment]
Please check runtime permissions specification before using this library, thx. http://developer.android.com/training/permissions/requesting.html

**Comment by Rainer-Lang** [comment]
@hotchemi Your library is already running - version 2.1.2. Rationale dialogs are shown. But only the very first rationale dialog after reinstall of the app isn't shown. All other rationale dialogs later in the app are shown without any problems.
I encountered this problem even in your sample-app - on both buttons. BUT you need to deinstall the app first!

**Comment by hotchemi** [comment]
Rationale dialog should be shown after user have pressed denied button, of course it is reseted when the app in uninstalled...please look android developers carefully...

**Comment by Rainer-Lang** [comment]
```@OnShowRationale - Annotate a method which explains why the permission/s is/are needed.``` (readme)
I understood that first the rationale dialog is shown to explain the user why he should press ```allow``` and grant the permission. After this the Android dialog.
So I misunderstood it?

**Comment by hotchemi** [comment]
Please re-read android developers.

**Comment by Rainer-Lang** [comment]
I re-read it - and I understand it. Thanks a lot.
Then: Is it right that the very first permission dialog has no "never ask again"?

**Comment by hotchemi** [comment]
yup.

**Comment by Rainer-Lang** [comment]
@hotchemi I have to apologize for this issue/confusion and thank you for your patience.

**Comment by hotchemi** [comment]
@Rainer-Lang No problem:)

**Comment by Repraance** [comment]
I met the same problem as I thought. After carefully reading the developer documents, I was told that never be opinionated. Thank you all!
