### ISSUE TITLE
Create Android Annotation plugin

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#143]
Ref. https://github.com/hotchemi/PermissionsDispatcher/issues/139#issuecomment-217834223

Now Android Annotation has a plugin system so we can create plugin for permissionsdispatcher.

**Comment by AleksanderMielczarek** [comment]
I've created such a plugin. You can check it out here: https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionDispatcherPlugin
It's very simple. It just removes @RuntimePermissions from generated class.

**Comment by hotchemi** [comment]
Awesome! I'll test it later! Really appreciated!
