### ISSUE TITLE
Make the helper class non-generated

### ISSUE THREAD

**Issue by aleb** [hotchemi/PermissionsDispatcher#144]
The `@OnShowRationale(Manifest.permission.CAMERA)` annotation seems to be only for decoration while it could be used by the library to find which methods to call when the client calls the helper's `onRequestPermissionsResult` or `show*WithCheck` methods. In this case the generated class has no reason to exist and should be replaced with a normal class.

If this is not true, please mention in https://github.com/hotchemi/PermissionsDispatcher#2-delegate-to-generated-class the reason why this generated class needs to be generated.

**Comment by hotchemi** [comment]
Sorry, I can't understand your point. What do you mean?

**Comment by aleb** [comment]
I see now the OnShowRationale annotation is not just for decoration and is used actually, by the code which generates the helper class.

The problem is that having to generate the helper class based on the method annotations is awkward. Maybe because I'm not sure at what point this operation is performed and I have the impression it's fragile.

I think it's possible to get rid of the generated helper if in the helper's `onRequestPermissionsResult` you inspect the methods of the passed Activity object and see which ones are annotated and call them.

**Comment by hotchemi** [comment]
> I see now the OnShowRationale annotation is not just for decoration and is used actually

I think we don't use OnShowRationale annotation itself by generated code.
Could you give me a concrete example? The following is a sample of the generated class.
https://github.com/hotchemi/PermissionsDispatcher/blob/master/art/MainActivityPermissionsDispatcher.java

And if you have any idea, could you give me a pull request?

**Comment by shiraji** [comment]
> The problem is that having to generate the helper class based on the method annotations is awkward. Maybe because I'm not sure at what point this operation is performed and I have the impression it's fragile.

"Annotation Processing Tool" is the word you probably should google it. Annotation processing is the one of the common tools that is used in the Android library these days. For example, Dagger, ButterKnife, AndroidAnnotations are the libraries that use annotation processing to generate codes. It is not awkward and fragile. In fact, annotation processing reduces the amount of the code to write.

> I think it's possible to get rid of the generated helper if in the helper's onRequestPermissionsResult you inspect the methods of the passed Activity object and see which ones are annotated and call them.

Are you saying the helper class uses Reflection to find the target method? Using reflection is not good performance.
