### ISSUE TITLE
Installation failed by adding dependencies in build.gradle

### ISSUE THREAD

**Issue by willthink** [hotchemi/PermissionsDispatcher#146]
I added this two lines in dependencies in app's build.gradle
 
compile 'com.github.hotchemi:permissionsdispatcher:2.1.2'
 apt 'com.github.hotchemi:permissionsdispatcher-processor:2.1.2'

And 
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
in project build.gradle dependencies

But I'm getting this error after syncing grade project

Error:Could not find com.github.hotchemi:permissionsdispatcher-processor:2.1.2.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.1.2/permissionsdispatcher-processor-2.1.2.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.1.2/permissionsdispatcher-processor-2.1.2.jar
    https://repo1.maven.org/maven2/com/github/hotchemi/permissionsdispatcher-processor/2.1.2/permissionsdispatcher-processor-2.1.2.pom
    https://repo1.maven.org/maven2/com/github/hotchemi/permissionsdispatcher-processor/2.1.2/permissionsdispatcher-processor-2.1.2.jar
    file:/Users/Zongzi/Documents/sdk/extras/android/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.1.2/permissionsdispatcher-processor-2.1.2.pom
    file:/Users/Zongzi/Documents/sdk/extras/android/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.1.2/permissionsdispatcher-processor-2.1.2.jar
    file:/Users/Zongzi/Documents/sdk/extras/google/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.1.2/permissionsdispatcher-processor-2.1.2.pom
    file:/Users/Zongzi/Documents/sdk/extras/google/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.1.2/permissionsdispatcher-processor-2.1.2.jar
Required by:
    project:app:unspecified

**Comment by aurae** [comment]
PermissionsDispatcher is distributed via `jcenter`. Make sure that your module has access to that by including it, e.g. in your project-level build.gradle:

```groovy
allprojects {
    repositories {
        jcenter()
    }
}
```
