### ISSUE TITLE
Add TargetSDK Version Judge,Please.

### ISSUE THREAD

**Issue by hexllo** [hotchemi/PermissionsDispatcher#147]
I use "android.permission.SYSTEM_ALERT_WINDOW" ,run on Android6.0 is very OK.

but,run on Android4.2,Occure FATAL EXCEPTION.

i guess Android4.2 SDK  no exists " android.provider.Settings.canDrawOverlays" method.

![image](https://cloud.githubusercontent.com/assets/14800596/15179660/cfca9ec2-17af-11e6-9352-f8f271b85d53.png)

please add judge SDK version in PermissionDispater.

PermissionDispater is very good frame.

**Comment by aurae** [comment]
I can reproduce the issue. `Settings#canDrawOverlays` was added to the platform in API level 23, so calling this method without a proper check is an oversight that must be taken care of.

Thank you for the report!

**Comment by aurae** [comment]
@shiraji, you brought in the original support for `SYSTEM_ALERT_WINDOW`, so your knowledge about how the platform treats that special permission is greater than mine. How would we backport the behavior of `Settings#canDrawOverlays' below 23?

**Comment by hexllo** [comment]
I add judge to outer.
eg:

  if(Build.VERSION.SDK_INT >= 23)
        {
            MainActivityPermissionsDispatcher.processPhoneWithCheck(this);
            MainActivityPermissionsDispatcher.showTopWindowWithCheck(this);
        }
        else
        {
            processPhone();
        }

**Comment by shiraji** [comment]
It should be like this...

```java
if (Build.VERSION.SDK_INT < 23 || Settings.canDrawOverlays(target)) {
    target.systemAlertWindow();
}
```

```java
if (Build.VERSION.SDK_INT < 23 || Settings.System.canWrite(target)) {
    target.writeSettings();
}
```

I will send PR

**Comment by hotchemi** [comment]
@hexllo Just released 2.1.3! Thank you for your report!

**Comment by hexllo** [comment]
You're welcome.

**Comment by hexllo** [comment]
You're welcome.

**Comment by hexllo** [comment]
You're welcome.
