### ISSUE TITLE
Dispatcher class for Fragment

### ISSUE THREAD

**Issue by mahmoud-elnaggar** [hotchemi/PermissionsDispatcher#149]
I'm using Support Fragment and annotate my Fragment with @RuntimePermission 
but the Dispatcher class not generated , 
it is working very well with Activity.

**Comment by shiraji** [comment]
Could you give us minimum project that reproduce this problem or show us your Fragment? Because support Fragment with `@RuntimePermission` should work like Activity.

**Comment by hotchemi** [comment]
Yup, also check https://github.com/hotchemi/PermissionsDispatcher#fragment-support.

**Comment by mahmoud-elnaggar** [comment]
I feel embarrassed
it is my mistake that I depended on auto-complete on Android Studio and I had to write Full  Class name , also Emulator didn't give me any Runtime Exception for Permission so I thought that the library somehow has a bug, Sorry :(

**Comment by shiraji** [comment]
Don't be. Grad this library hass nothing to wrong.
