### ISSUE TITLE
MainActivityPermissionsDispatcher is not generated after build

### ISSUE THREAD

**Issue by Montrazul** [hotchemi/PermissionsDispatcher#153]
I followed the instructions but the MainActivityPermissionsDispatcher is never created. I cant use this Activity after the build process.

**Comment by hotchemi** [comment]
Please check your gradle setting, and try sample module.

**Comment by Montrazul** [comment]
Yes, that is what i did and the sample project also did not create the MainActivityPermissionsDispatcher.

**Comment by shiraji** [comment]
Have you rebuild project?

**Comment by Montrazul** [comment]
Before i used the MainActivityPermissionsDispatcher. I implmemented everything needed before MainActivityPermissionsDispatcher, i rebuild project and after tried to access MainActivityPermissionsDispatcher but the class could never be found.

**Comment by shiraji** [comment]
Rebuild after adding `MainActivityPermissionsDispatcher`

**Comment by Montrazul** [comment]
Why "adding" the MainActivityPermissionsDispatcher should get created automatically after you build the project using the annotations.......

**Comment by shiraji** [comment]
And if it does not help, could you give us a sample project?

**Comment by Montrazul** [comment]
The sample project is provided on this github repository.

**Comment by aurae** [comment]
The sample project definitely 100% no-doubt works perfectly fine. Are you on Android Studio? What version? What version of Gradle are you building with?

**Comment by shiraji** [comment]
Well, the sample project compile successfully on all of my workstation. You need to give us your sample project that reproduce this issue.

**Comment by Montrazul** [comment]
Android Studio 2.1.1
Gradle Version 2.1.0

**Comment by shiraji** [comment]
It seems a bug in AndroidStudio, not PermissionsDispatcher. Have you use other annotation processing library?

**Comment by aurae** [comment]
That's very weird. Do you use Instant Run? About 90% of my build-related issues in the past weeks all came down to disabling Instant Run.

**Comment by hotchemi** [comment]
@aurae @shiraji Thank you for your help!

**Comment by a-jahanshahlo** [comment]
oh I'm get mistake!
Please use like this instruction:
[Your Activity Name]PermissionsDispatcher

Ha ha ha.

**Comment by hotchemi** [comment]
@a-jahanshahlo Here! https://github.com/hotchemi/PermissionsDispatcher/blob/master/README.md#2-delegate-to-generated-class

**Comment by a-jahanshahlo** [comment]
@hotchemi  thank you to your link.
unfortunately I'm not above link before. 
I'm know about this project on this link:
http://guides.codepath.com/android/Managing-Runtime-Permissions-with-PermissionsDispatcher

Thanks Again.

**Comment by hotchemi** [comment]
@a-jahanshahlo Cool! But it's not under our management...😅 Can you open an issue there?

**Comment by a-jahanshahlo** [comment]
😅😅😅😅😅😅😅😅😅😅😅😅😅😅v
