### ISSUE TITLE
How to ask for multiple permissions at a time with PermissionsDispatcher?

### ISSUE THREAD

**Issue by shmueldw** [hotchemi/PermissionsDispatcher#155]
How to ask for multiple permissions at a time?

**Comment by acrolink** [comment]
I have the same question.. Thanks

**Comment by shmueldw** [comment]
What is a question?

**Comment by shmueldw** [comment]
```
@NeedsPermission({Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.READ_CONTACTS,Manifest.permission.WRITE_CONTACTS})
void insertDummyContact(){...}
```

**Comment by acrolink** [comment]
Thank you @shmeuldw .. I will give this project full testing later .. Interesting

**Comment by hotchemi** [comment]
Yup!

**Comment by acrolink** [comment]
So, at each point in my code when I need to access internet/camera/device info etc I would have to ask for authorization? Or can this be made one time on app start in MainAcrivity?

**Comment by acrolink** [comment]
**UPDATE**

Now I have just unraveled the power of this code, not all that complicated after all. Thank you guys.
