### ISSUE TITLE
permissions.dispatcher.processor.exception.WrongClassException

### ISSUE THREAD

**Issue by herbertdai** [hotchemi/PermissionsDispatcher#156]
permissions.dispatcher.processor.exception.WrongClassException: Class 'com.test.hk.agg.MyUITest' can't be annotated with '@RuntimePermissions'

**Comment by shiraji** [comment]
Is your `MyUITest` extends `Activity`, `Fragment` or `support.v4.app.Fragment`?

Documentation for `RuntimePermissions` is this.
https://github.com/hotchemi/PermissionsDispatcher#1-attach-annotations

**Comment by herbertdai** [comment]
@shiraji  Hi, I'm running a AndroidJunit4 test and the MyUITest looks like: 

```
import android.support.test.runner.AndroidJUnit4;
import org.junit.runner.RunWith;

/**
 * Created by herbert on 6/8/16.
 */

@RunWith(AndroidJUnit4.class)
public class MyUITest {

}

```

I do not use any Dispatcher related annotations in this file.

**Comment by hotchemi** [comment]
Umm, wired...could you give us an example project?

**Comment by herbertdai** [comment]
Thanks @hotchemi , Wait a minute, I'm building a sample project.

**Comment by herbertdai** [comment]
I build a new example  project but no error ocurred,  it may be the reason that my project structure is not the stand AndroidStuio-like structure. Still trying on that.

**Comment by hotchemi** [comment]
Okay.

**Comment by herbertdai** [comment]
Just like what I tried, after I changed the file structure to the standard  like : ./app/src/androidTest/java/, the test runs ok!

> Testing started at 12:02 AM ...

Thanks @hotchemi
