### ISSUE TITLE
Using with SyncAdapter

### ISSUE THREAD

**Issue by alexsho** [hotchemi/PermissionsDispatcher#159]
Hi,
Very useful library.
I need to get a permissions for sync adapter in Marshmallow.
When i put @RuntimePermission at the top of the class extending from AbstractThreadedSyncAdapter
It fails on compilation (WrongClassException)
Is it the way to use your library with sync adapter ?

**Comment by shiraji** [comment]
Here is documentation
https://github.com/hotchemi/PermissionsDispatcher#1-attach-annotations

You need to put `@RuntimePermission` at the top of class that extend `Activity` or `Fragment`.

**Comment by hotchemi** [comment]
@alexsho Yup, Only Activity and Fragment provide permission related methods, so we restrict user to annotate only Activity or Fragment.
I your case, you should show a dialog when the app is first launched. And insert checking code before you start the SyncAdapter(user can revoke permission from setting).

**Comment by alexsho** [comment]
Thank you.
