### ISSUE TITLE
Call the WithCheck method from Fragment. onRequestPermissionsResult is not called back

### ISSUE THREAD

**Issue by katsuki-nakatani** [hotchemi/PermissionsDispatcher#16]
Generated Diapatcher.java withCheck method
```
ActivityCompat.requestPermissions(target.getActivity(), PERMISSION_METHOD, REQUEST_METHOD);
```

If the target is a fragment it is expected to be referred to as the FragmentCompat class below
```
FragmentCompat.requestPermissions(target, PERMISSION_METHOD, REQUEST_METHOD);
```

not called as well shouldShowRequestPermissionRationale method
It is necessary to call in FragmentCompat

We hope that you add the fragment for the method to PermissionsUtils.java

```
 public static boolean shouldShowRequestPermissionRationale(Fragment fragment, String... permissions) {
        String[] var2 = permissions;
        int var3 = permissions.length;

        for(int var4 = 0; var4 < var3; ++var4) {
            String permission = var2[var4];
            if(FragmentCompat.shouldShowRequestPermissionRationale(fragment, permission)) {
                return true;
            }
        }

        return false;
    }
```

But if you make this change, there is a need to up the MinSDKVersion to 15

Thanks

**Comment by hotchemi** [comment]
Thanks for your report! I'm gonna deal with.

**Comment by hotchemi** [comment]
For the time being I'm gonna rule out android.app.Fragment. We should deal with it as a option but currently I have no idea about good interface...

**Comment by aurae** [comment]
Support for `android.app.Fragment` will be included once the library revision in Kotlin is being introduced, which should hopefully be some time this month. It will enable you to annotate native Fragments with `@RuntimePermissions` if you also added a dependency on support-v13 in your project.

**Comment by hotchemi** [comment]
@katsuki-nakatani Please check 1.2.1.
