### ISSUE TITLE
Cannot click on 'Allow' for permission

### ISSUE THREAD

**Issue by jmoscatiello** [hotchemi/PermissionsDispatcher#160]
Hey all,

  I have been using the lib for a while, I love it. I recently updated to a new version of Android 6.0.1 and it seems I can no longer click on the 'Accept' button. Does anyone know why this can be happening or is anyone experiencing it. 

Thanks!

**Comment by hotchemi** [comment]
@jmoscatiello I think it's not a problem of PermissionsDispatcher, it just shows a dialog by calling requestPermission. I think you should submit a bug report to b.android.com!

**Comment by jmoscatiello** [comment]
Just a note. For my sanity I downloaded the sample and ran it. Same issue. will investigate more. 

Thanks.

**Comment by shiraji** [comment]
https://code.google.com/p/android/issues/detail?id=213120

**Comment by jmoscatiello** [comment]
@shiraji Thank you
