### ISSUE TITLE
Delegate class not generated automatically

### ISSUE THREAD

**Issue by RajeshJadav** [hotchemi/PermissionsDispatcher#161]
Is there any option to generate Delegate class automatically? Currently i have to build entire project then Delegate class is generated

**Comment by aurae** [comment]
Annotation processors are invoked during javac compilation, which you need to invoke with `build` or something similar. `assemble` should work as well, though!

**Comment by hotchemi** [comment]
@RajeshJadav https://github.com/hotchemi/PermissionsDispatcher/issues/161#issuecomment-227090527 is definitely correct. This is the limit of the annotation processing.
