### ISSUE TITLE
duplicate entry:android/support/v4/print/PrintHelperKitkat$1.class

### ISSUE THREAD

**Issue by the-south-snowing** [hotchemi/PermissionsDispatcher#163]
Error:Execution failed for task ':C2B_Phone:transformClassesWithJarMergingFor_360Debug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/print/PrintHelperKitkat$1.class

anybody can help me ?

**Comment by hotchemi** [comment]
@the-south-snowing I think it's not from this library, because we don't use print stuff you know...
Have you tried rebuild project and delete cash?

**Comment by aurae** [comment]
Might be a version conflict with the support-v4 library pulling in two variants of the same class. As hotchemi-san said though, not a PermissionsDispatcher issue per se.

**Comment by hotchemi** [comment]
@the-south-snowing You can try like following:

```
    compile('com.commonsware.cwac:camera-v9:0.5.4') {
      exclude module: 'support-v4'
    }
```

@aurae Thx man!

**Comment by ShadowBill** [comment]
Nobody can sovle this question？
