### ISSUE TITLE
Unexpected @OnNeverAskAgain behavior

### ISSUE THREAD

**Issue by markini** [hotchemi/PermissionsDispatcher#164]
Hello, I just want to confirm the expected behavior of `@OnNeverAskAgain`.

I have 3 functions like this:
```java
@OnClick(R.id.iv_new_photo)
public void photoClick() {
	MyFragmentPermissionsDispatcher.onNewPhotoClickWithCheck(this);
}

@NeedsPermission({CAMERA, WRITE_EXTERNAL_STORAGE})
public void onNewPhotoClick() {
...
}

@OnNeverAskAgain({CAMERA, WRITE_EXTERNAL_STORAGE})
void onCameraNeverAskAgain() {
	DialogStarter.startNeverAskAgainDialog(getActivity(), R.string.cam_never_ask_again);
}
```

When I click on my photo button and deny the permissions with never ask again. The function `onCameraNeverAskAgain` is immediately triggered. Is this the intended behavior?

I expected it to only show when I click on the camera button again (which it also does).

**Comment by shiraji** [comment]
If user click with never ask again, then `onCameraNeverAskAgain` is called. AFAIK, this is the expected behavior.

**Comment by hotchemi** [comment]
@markini Yup, please see android developers or this slide https://speakerdeck.com/hotchemi/managing-runtime-permissions?slide=8
