### ISSUE TITLE
How to generate Delegate class

### ISSUE THREAD

**Issue by zongxinbo** [hotchemi/PermissionsDispatcher#165]
I have rebuild my project, but still no delegate class generated.  
Please help me.

**Comment by shiraji** [comment]
Could you post the code or minimum project that reproduce this issue? and post the version of android studio, android gradle plugin version, and the PermissionsDispatcher version.

**Comment by hotchemi** [comment]
@zongxinbo Yes, please check at our sample module with your AndroidStudio and if you still have problem pls post the minimal project.
