### ISSUE TITLE
feature-request: onPermissionGranted(X) annotation

### ISSUE THREAD

**Issue by meierjan** [hotchemi/PermissionsDispatcher#166]
I just stumbled across a case in which a callback annotation like "onPermissionGranted" would help me out. Why not add this to the API?

I just helped myself out but doing something like this:
```
@Override
    public void onRequestPermissionsResult(
            int requestCode,
            @NonNull String[] permissions,
            @NonNull int[] grantResults
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        // ....
        List<String> permissionsAsList = Arrays.asList(permissions);
        if(permissionsAsList.contains("android.permission.CAMERA")) {
            if(grantResults[permissionsAsList.indexOf("android.permission.CAMERA")] == android.content.pm.PackageManager.PERMISSION_GRANTED) {
                onLocationPermissionGranted();
            }
        }
    }
```

Although I think it's something not always needed but sometimes it's nice to have.

**Comment by hotchemi** [comment]
@meierjan
Hi thx for your request.
Isn't it enough to `@NeedsPermissions`? You can declare permission to each annotated method and handle callback as you suggested.

**Comment by hotchemi** [comment]
Yeah it's definitely nice to have but I would like to keep api simple. Anyway Thx for your suggestion!

**Comment by meierjan** [comment]
Hey, the difference is that the NeedsPermission annotated method is executed always where as the "onPermissionGranted" annotation would be executed only in that case. But thanks for the heads up

**Comment by aurae** [comment]
So you're talking about a one-time callback method that only gets invoked after the permission is granted "for the first time", and skipped in case that permission had already been granted?

**Comment by meierjan** [comment]
Exactly. I think this fits pretty good into the philosophy as all other callbacks are there except this one.

**Comment by hotchemi** [comment]
FYI: You can do that by writing your own `onRequestPermissionsResult`(not delegating the work to generated class).

**Comment by meierjan** [comment]
Yeah, like I posted in my issue - up there. It was just a feature request. Thanks for the heads up

**Comment by xbroak** [comment]
How would we perform the desired operation after permission has been granted without this? For instance, if there is a button for "Make phone call", we'd check, ask for the permission, get the OK, then what? The user has to press on "Make phone call" again after it closes?
