### ISSUE TITLE
Build error with AndroidAnnottations

### ISSUE THREAD

**Issue by mrljdx** [hotchemi/PermissionsDispatcher#167]
HI When I use AndroidAnnotations with your permissions dispatcher ,there is a error as belows:

> Error:Execution failed for task ':app:compileBiliDebugJavaWithJavac'.
``>``permissions.dispatcher.processor.exception.NoAnnotatedMethodsException: Annotated class 'MainFragment_' doesn't have any method annotated with '@NeedsPermission'

Source code as belows:

        @EFragment(R.layout.fragment_main)
        @RuntimePermissions
         public class MainFragment extends Fragment{

                 @Override
                 public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,       @NonNull int[] grantResults) {
                     super.onRequestPermissionsResult(requestCode, permissions, grantResults);
                     
                         PermissionsChecker.onPermissionResult(requestCode, permissions, grantResults);
                         MainFragmentPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
                 }

                 @NeedsPermission(Manifest.permission.WRITE_CONTACTS)
                 void writeContactTest() {
                 }
         }

Is there any solutions for this situations ? 
thanks~ ：）

**Comment by shiraji** [comment]
Check this plugin https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin

#143 is the issue we talked about AA plugin.

**Comment by hotchemi** [comment]
Totally.
