### ISSUE TITLE
Endorse AA plugin in README

### ISSUE THREAD

**Issue by aurae** [hotchemi/PermissionsDispatcher#168]
Let's consider adding a section on `AndroidAnnotations` in the README, in which we redirect people to [Aleksander's plugin](https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin). This could be generalized into an "Integration" section in the future once we add support for more frameworks, but since AA is the only one right now, we should add it like that.

What do you think, @hotchemi @shiraji?

**Comment by hotchemi** [comment]
@aurae You don't have to ask us cuz you have a commit bits! :D And I definitely agree with your proposal!

**Comment by LouisCAD** [comment]
@aurae Are you working on this? If you're not, I'm going to update the README today so it's finally done :wink:

**Comment by aurae** [comment]
I haven't found time yet, no, so you're more than welcome to go ahead! :)
