### ISSUE TITLE
How to delegate to a class other than MainActivity

### ISSUE THREAD

**Issue by acrolink** [hotchemi/PermissionsDispatcher#169]
In the examples you state (inside onCreate):

```
MainActivityPermissionsDispatcher.showCameraWithCheck(this);
```

How to do the same inside a custom class, a one that extends for example Intent Service? Thank you.

**Comment by hotchemi** [comment]
We only support Activity and Fragment because `requirePermissions` method is in them, what `custom class` means?

**Comment by acrolink** [comment]
@hotchemi In my app I have created a class that extends IntentService. I use that class to read/write to a local storage file. What I understand from your answer is that PermissionsDispatcher supports only Activity and Fragment, so it looks like any permissions needed by my IntentService type class must be obtained within MainActivity or within a Fragment activity.

**Comment by hotchemi** [comment]
@acrolink Exactly. You have to do the same thing even you decide to not to use PermissionsDispatcher.

**Comment by aurae** [comment]
The problem with runtime permissions within `Service` classes comes with their lack of user-facing UI, which makes it cumbersome to show a dialog to the user.

I outlined what I'd call an "acceptable solution" to this problem [in another issue recently](https://github.com/hotchemi/PermissionsDispatcher/issues/34), please check it out and consider if implementing this Notification-based approach works for you!
