### ISSUE TITLE
Could this support methods that return values?

### ISSUE THREAD

**Issue by fat-tire** [hotchemi/PermissionsDispatcher#17]
First off this is very cool, so thanks for implementing it!

Right now, `PermissionsDispatcher` only seems to work if the method annotated with `@NeedsPermission` is of type `void` and doesn't return anything.  (It actually *does* let you annotate a method that returns a value, but the resulting `...WithCheck` methods are`static void` so you can't use it in place of the original call).

Would it be possible to make this work while the original method was blocking, ie, synchronously-- to allow for methods which may return, say, `boolean` on success/failure (as in loading/saving files to external storage, checking if a contact exists, etc.)?

If so, awesome!!  If not, there should probably be a warning/error if you try to use `@NeedsPermission` on a method when a value is returned.

Thanks again, I wish I had seen this sooner.  This is great!

**Comment by aurae** [comment]
I don't see how the asynchronous process of requesting permissions could be changed to allow for arbitrary return types yet, since those would need to be propagated to the caller somehow. I suggest you annotate your methods based on "access" use cases, e.g.

```java
@NeedsPermission(Manifest.permission.READ_CONTACTS)
void accessContacts() {
    // In here, handle checks if a contact exists, after permission was granted
}
```

I do agree about the need for a compile-time exception and validations on the return types of annotated methods, though!

**Comment by hotchemi** [comment]
In my think, it's not necessary requirement.
In [official sample](https://github.com/googlesamples/android-RuntimePermissions/blob/master/Application/src/main/java/com/example/android/system/runtimepermissions/MainActivity.java#L142), they check permissions only when replacing fragment.
In a word, you can separate handling permissions and do some stuff with permissions to different methods right?
Of course we can do that but I don't wanna complicate API, we should focus on simplify the usage and API. Like golang.

**Comment by fat-tire** [comment]
@aurae, it's a perplexing issue, for sure.. 

FWIW, some Activity methods which one might want to `@Override` (like `onSearchRequested()`, `onTouchEvent()`, etc.) do return values, which make them ineligible for being annotated with `@NeedsPermission`.  And then of course every one that might be in the activity that uses a permission would have to be refactored.

that said, I really don't know how/if it could be [feasible](https://stackoverflow.com/questions/15815907/wrapping-a-series-of-asynchronous-calls-with-a-synchronous-method-with-a-return) do what I'm suggesting, especially without blocking the UI thread... but I'm no expert here, which is why I'm asking.

The Android Backstage developers' [podcast](http://androidbackstage.blogspot.com/2015/08/episode-33-permission-mission.html) from Google developers seemed to suggest that this async issue is tripping people up, even within Google.  Listen at about 41:20:

In this discussion:

Chet Haas -- toolkit team
Tor Norbye-- tools team
Ben Poiesz -- product manager

Rough transcript:

Norbye:  "*So it doesn't seem like it should be a lot of work for developers.  But I understand part of the problem is that these are not synchronous calls, right?.  So what you have to- actually change the way your activity is written to have a callback-- so it's really kinda like a state machine where... for this state, you-*"

Poiesz: "*Ah- I thought- there was a- there might be an option for synchronous response--*"

Norbye: "*Oh.  that would make things--*"

Poiesz: "*I can talk with folks internally.  I recall a discussion about synchronous- but we can find out.*"

Norbye: "*Yeah. In fact we should probably should probalby make it into the tools.  Where you have an easy refactoring...*"

Then he talks about using annotations in the tools to determine which APIs require permissions.. (which as of now doesn't work that great IMO) and how he wants the tools someday to actually generate the required code if it finds an unchecked "dangerous" method call:

Norbye:  "*...then if you're on M as well it'll say, 'hey, are you actually checking for this permission or are you catching security exceptions?', and if you're not, we'll say 'you probably need to do something for requesting the permission here.'   What I would like though is for that to have a quick fix where you can go 'CHING!' and it inserts all the right stuff for asking, but the way things were back when I looked, this required restructuring a lot of things-- adding interfaces and callbacks, and changing the flow, and that we couldn't do.  But if there's an easy synchronous mode as a temporary thing or a permanent thing, that would [be great].*"

**Comment by aurae** [comment]
Thanks for your input and the link! Sadly, as you said, the synchronicity of methods with return types doesn't necessarily play along with the way Runtime Permissions have been constructed. If we allowed for this, there are two major factors that cause problems with this approach:

```java
public class MyActivity extends Activity {
	
        // Suppose we could do this...
	@NeedsPermission(Manifest.permission.READ_CONTACTS)
	@Override public boolean onSearchRequested() {
		boolean whatever = ...
		return whatever;
	}

	// Omitted for brevity: Rationale, Deny callbacks...

	@Override public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
		MyActivityPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, permissions, grantResults);
	}
}

public final class MyActivityPermissionsDispatcher {

    private static final int REQUEST_ONSEARCHREQUESTED = 0;
    private static final String[] PERMISSION_ONSEARCHREQUESTED = new String[] { "android.permission.READ_CONTACTS" };

    private MyActivityPermissionsDispatcher() {
    }

    public static boolean onSearchRequestedWithCheck(MyActivity target) {
        if (PermissionUtils.hasPermission(target, PERMISSION_SHOWCAMERA)) {
            return target.onSearchRequested();
        } else {
            if (PermissionUtils.shouldShowRationale(target, PERMISSION_SHOWCAMERA)) {
                target.showSearchRequestedRationale();
            }
            ActivityCompat.requestPermissions(target, PERMISSION_SHOWCAMERA, REQUEST_SHOWCAMERA);

            // Problem 1: What to return here?
            return ?
        }
    }

    public static void onRequestPermissionsResult(MyActivity target, int requestCode, int[] grantResults) {
        switch (requestCode) {
            case REQUEST_ONSEARCHREQUESTED:
                if (PermissionUtils.verifyPermissions(grantResults)) {
                	// Problem 2: What about the return type here?
                    target.onSearchRequested();
                } else {
                    target.onSearchRequestedDenied();
                }
            default:
            	break;
        }
    }
}
```

Again, I would advocate for code to be refactored in a way that relies entirely on `void` methods. We'll see what Google brings to the table in terms of a "synchronous mode", but I doubt that the system at hand is going to change in the near future.

**Comment by hotchemi** [comment]
I think you misunderstand the point.
`requirePermissions` is not synchronous, but you can ask user to grant permissions before synchronous stuff is needed.
Please check [it](https://github.com/googlesamples/android-RuntimePermissions/blob/master/Application/src/main/java/com/example/android/system/runtimepermissions/MainActivity.java#L177) out. Official sample is checking permissions before adding fragment. And using permissions in the fragment. And actually when user deny some permissions from the system setting, the process will be recreated. So this approach doesn't cause any matter, right?

**Comment by hotchemi** [comment]
I'm gonna close this issue, if u have any problem please reopen it.
