### ISSUE TITLE
How to call showRational() method for @OnNeverAskAgain event

### ISSUE THREAD

**Issue by roostaamir** [hotchemi/PermissionsDispatcher#170]
I am using Permission dispatcher plugin and when the user clicks never ask again, the activity freezes.
I want to show the user the Rational dialog when the user checks the never ask again dialog and enters the application again.

currently the app will freeze when the user checks never show this again

what should I do?

**Comment by roostaamir** [comment]
it looks like checking `don't ask again` results in @OnPermissionDenied to be called infinitely. What is the problem?

**Comment by shiraji** [comment]
Could you post your code that is related to PermissionsDispatcher?

**Comment by hotchemi** [comment]
@roostaamir Could you give us an example?
