### ISSUE TITLE
if app op set one permission denied, it will work very strange

### ISSUE THREAD

**Issue by wangxiaote** [hotchemi/PermissionsDispatcher#173]
if app op set one permission denied, next time I try to get permissions, and the permission dialog will show; If I click allow button, the APP will be killed and restart.
I debug it,and found that the permission status is PERMISSION_DENIED_APP_OP; it means a app op deny it. and it can not get the permission by request permission dialog of system.

**Comment by hotchemi** [comment]
@wangxiaote Could you give us device info and an example which reproduces the problem? We need more info to investigate.

**Comment by hotchemi** [comment]
There is no enough information yet so I'm gonna close. Pls reopen if you're still in trouble.

**Comment by ivanisidrowu** [comment]
I got the same situation as this one, here's my sample code in Gist.
https://gist.github.com/ivanisidrowu/d8ed4e2c34680b0d224cc8cde56d9056

I tested it on Nexus 4 API 23 emulator. First time, I granted first permission and denied one permission. Second time I opened the APP, I denied first permission and the others. However, when I denied the first one, the APP restarted. Please help :( Thanks!
