### ISSUE TITLE
how I use it in eclipse？please tell me.

### ISSUE THREAD

**Issue by xubuhang** [hotchemi/PermissionsDispatcher#174]
how I use it in eclipse？

**Comment by shiraji** [comment]
You can download jar and aar files from bintary https://bintray.com/hotchemi/maven/permissionsdispatcher and https://bintray.com/hotchemi/maven/permissionsdispatcher-processor . I'm not sure how to use aar using ADT though...

To be honest, that is all information we have for you. ADT is officially [no longer supported](http://android-developers.blogspot.jp/2015/06/an-update-on-eclipse-android-developer.html).

**Comment by hotchemi** [comment]
@xubuhang Yup, our best advice is "Throw Eclipse away.", Sorry!

**Comment by xubuhang** [comment]
thanks, @hotchemi @shiraji .
