### ISSUE TITLE
If I has two method need same permission,How to distinguish it's  for `OnShowRationale`?

### ISSUE THREAD

**Issue by a1018875550** [hotchemi/PermissionsDispatcher#177]
If I has two method need same permission,How to distinguish it's for `OnShowRationale`

**Comment by hotchemi** [comment]
@a1018875550 If you declare same permission on **different** Activities or Fragments it will be handled as different thing. Isn't it enough?

**Comment by a1018875550** [comment]
I have some defferent require  in a Activity,but they alse need the permission of "Camera";So how to distinguish of them

**Comment by hotchemi** [comment]
Can you try like the following? If that doesn't work well, it seems currently we have no way to do that. So improvement is needed.

```java
// use them
private static final String[] PERMISSION_SHOWCAMERA1 = new String[] {"android.permission.CAMERA"};
private static final String[] PERMISSION_SHOWCAMERA2 = new String[] {"android.permission.CAMERA"};
```

**Comment by hotchemi** [comment]
@a1018875550 Did it work well?

**Comment by a1018875550** [comment]
No it's dosen't work;the Android Studio note 
`Error:Execution failed for task ':mazi:compileDebugJavaWithJavac'.> permissions.dispatcher.processor.exception.DuplicatedValueException: [android.permission.CAMERA] is duplicated in 'showRationaleForCamera()' annotated with '@OnShowRationale'`

**Comment by hotchemi** [comment]
@a1018875550 Sorry to hear that. 
Currently we don't provide the way to handle same permissions in the same Activity/Fragment.
So my current best advise is creating different Activity/Fragment and put the other permission to it...Is it possible?

**Comment by a1018875550** [comment]
;It's like possible for now If put other permission to one of it; But It's not a permanent solution；
You can add a int value to `@NeedsPermission` and others to distinguish them,this is my suggest hope you find a better solution; Thank you very much!

**Comment by hotchemi** [comment]
> http://hrnabi.com/wp-content/uploads/2015/09/002a-580x386.jpg

Yep we actually thought that feature before but we dropped it because it complicates the library itself. But I think it's worth to reconsider? What do you think @aurae @shiraji ?

**Comment by aurae** [comment]
In case the permission signature is identical for both permission-protected methods, do you even need to have different rationales? I'd argue that they would report pretty much the same thing to the user, so a single rationale method usually suffices for most use cases.

However, I'd be okay with adding tags to annotated methods, if we can ensure that it doesn't require changes for all current users of the library.

**Comment by a1018875550** [comment]
thaks

**Comment by hotchemi** [comment]
@aurae Thx for your comment, I didn't realised that but that's the good point.

**Comment by shiraji** [comment]
I still don't see the point of requiring the same permissions in one Activity/Fragment. Other than that, I have pretty much the same opinion with @aurae 

So, let's think about how the tag works.

* tag should be option
* If a developer sets a tag in `@NeedsPermission`, he/she must provides permissions and the tag to all `@OnShowRationale`, `@OnPermissionDenied`, `@OnNeverAskAgain`.
* This means in the following case, `showRationaleForCamera` will be ignored. (Need more lint check!)
```java
    @NeedsPermission(Manifest.permission.CAMERA, tag = "FOO") // I set String but tag type can be integer, Object or anything.
    void showCamera() { 
        // do something
    }

    @OnShowRationale(Manifest.permission.CAMERA)
    void showRationaleForCamera(PermissionRequest request) {
        // do something
    }
```

Is this all functionalities for tag?

---

Sample

```java
    // this method's OnShowRationale will be showRationaleForCamera
    @NeedsPermission(Manifest.permission.CAMERA, tag = "FOO")
    void showCamera() { 
        // do something
    }

    // this method's OnShowRationale will be showRationaleForCamera2
    @NeedsPermission(Manifest.permission.CAMERA)
    void showCamera2() { 
        // do something
    }

    @OnShowRationale(Manifest.permission.CAMERA, tag = "FOO")
    void showRationaleForCamera(PermissionRequest request) {
        // do something
    }

    @OnShowRationale(Manifest.permission.CAMERA)
    void showRationaleForCamera2(PermissionRequest request) {
        // do something
    }
```

**Comment by hotchemi** [comment]
@shiraji Thx, actually @aurae proposed almost the same idea before at https://github.com/hotchemi/PermissionsDispatcher/issues/18#issuecomment-136099353 but at that time I wanted to keep this library simple so didn't implement.

**Comment by hotchemi** [comment]
@shiraji Are you working on this issue?

**Comment by shiraji** [comment]
Not yet. You can take it.

2016年8月8日(月) 13:13 Shintaro Katafuchi <notifications@github.com>:

**Comment by hotchemi** [comment]
@shiraji Okay.
In my think this improvement is not mandatory so I'd like to close it if someone is eager to implement that.

**Comment by peienliudao** [comment]
try it:
it can work.
We can add a int value(eg:Manifest.permission.INTERNET) to @NeedsPermission  to distinguish them.
Sample:

@NeedsPermission(Manifest.permission.CAMERA)
@OnPermissionDenied(Manifest.permission.CAMERA)
@OnNeverAskAgain(Manifest.permission.CAMERA)



@NeedsPermission({Manifest.permission.CAMERA,Manifest.permission.INTERNET})
 @OnPermissionDenied({Manifest.permission.CAMERA,Manifest.permission.INTERNET})
@OnNeverAskAgain({Manifest.permission.CAMERA,Manifest.permission.INTERNET})
