### ISSUE TITLE
How can I use OnNeverAskAgain?

### ISSUE THREAD

**Issue by kensoon** [hotchemi/PermissionsDispatcher#179]
I don't know how to use the PermissionsDispatcher to invoke the OnNeverAskAgain.Can anybody tell me how to use it, thinks a lot!

**Comment by shiraji** [comment]
Have you read README?

**Comment by hotchemi** [comment]
@kensoon If you define a method which is annotated with OnNeverAskAgain, it'll be called when user denied a permission with "never ask again" check.
