### ISSUE TITLE
Allow multiple methods to use same @NeedsPermission (and avoid DuplicatedValueException)

### ISSUE THREAD

**Issue by fat-tire** [hotchemi/PermissionsDispatcher#18]
Say that you have multiple methods that each require the identical permission to, say, write to external storage.  Because you don't know what the user is going to do, you want to make sure that if *either* method is called, the appropriate permissions is checked and a request is made to the user...

So--- you annotate with `@NeedsPermission("android.permission.WRITE_EXTERNAL_STORAGE")`
 on each.  But now, you get one of these:

`Error:Execution failed for task ':compileDebugJavaWithJavac'. > permissions.dispatcher.processor.exceptions.DuplicatedValueException: [android.permission.WRITE_EXTERNAL_STORAGE] is duplicated in interface permissions.dispatcher.NeedsPermission`

Unfortunately, the documentation for the new runtime permissions kind of assume that there's only one occasion in which you'll be asking for a permission-- you can set various [request codes](https://github.com/googlesamples/android-RuntimePermissions/blob/master/Application/src/main/java/com/example/android/system/runtimepermissions/MainActivity.java#L88-L96) in `@onRequestPermissionResult`-- supposedly one per permission, right?  But in the above case you'd have to set them to account for each *method* that might be using each permission.  And handle the result for every possible combination of methods/permissions/responses right there.

Sigh. This could easily become a logistical nightmare.  Maybe `PermissionsDispatcher` could make it easier by allowing more than one method to use `@NeedsPermission` for the same permission(s) and do the right thing?

**Comment by aurae** [comment]
I can see how multiple methods with the same `@NeedsPermission` signature would be a thing. I don't think it would be an issue if we allowed for that, albeit the uniqueness of other annotated methods (`@ShowsRationale` and soon `@DeniedPermission`) have to be ensured. In this case, the same 'rationale' and 'deny' callbacks would be invoked for all `@NeedsPermission` methods with identical signatures, if they are present:

```java
@RuntimePermissions
public class MyActivity extends AppCompatActivity {
	
	@NeedsPermissions(Manifest.permission.CAMERA)
	void showCamera() {
	}
	
	@NeedsPermission(Manifest.permission.CAMERA)
	void useCamera() {
	}
	
	@ShowRationale(Manifest.permission.CAMERA)
	void showCameraRationale() {
	}
	
	@DeniedPermissions(Manifest.permission.CAMERA)
	void onCameraDenied() {
	}
	
	@Override
	public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
		MyActivityPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
	}
}

public final class MyActivityPermissionsDispatcher {

	private static final int REQUEST_SHOWCAMERA = 0;
	private static final String[] PERMISSION_SHOWCAMERA = new String[] { "android.permission.CAMERA" };
	private static final int REQUEST_USECAMERA = 1;
	private static final String[] PERMISSION_USECAMERA = new String[] { "android.permission.CAMERA" };
	
	private MyActivityPermissionsDispatcher() {
	}
	
	public static void showCameraWithCheck(MyActivity target) {
		if (PermissionUtils.hasPermission(target, PERMISSION_SHOWCAMERA)) {
			target.showCamera();
		} else {
			if (PermissionUtils.shouldShowRationale(target, PERMISSION_SHOWCAMERA)) {
				target.showCameraRationale();
			}
			ActivityCompat.requestPermissions(target, PERMISSION_SHOWCAMERA, REQUEST_SHOWCAMERA);
		}
	}
	
	public static void useCameraWithCheck(MyActivity target) {
		if (PermissionUtils.hasPermission(target, PERMISSION_USECAMERA)) {
			target.useCamera();
		} else {
			if (PermissionUtils.shouldShowRationale(target, PERMISSION_USECAMERA)) {
				target.showCameraRationale();
			}
			ActivityCompat.requestPermissions(target, PERMISSION_USECAMERA, REQUEST_USECAMERA);
		}
	}
	
	public static void onRequestPermissionsResult(MyActivity target, int requestCode, int[] grantResults) {
		switch (requestCode) {
			case REQUEST_SHOWCAMERA:
				if (PermissionUtils.verifyPermissions(grantResults)) {
					target.showCamera();
				} else {
					target.onCameraDenied();
				}
				break;
			case REQUEST_USECAMERA:
				if (PermissionUtils.verifyPermissions(grantResults)) {
					target.useCamera();
				} else {
					target.onCameraDenied();
				}
				break;
			default:
				break;
		}
	}
}
```

**Comment by fat-tire** [comment]
In the above case you have both `ShowCamera()` and `UseCamera()` sharing the same rationale (`showCameraRationale`).  I actually think in most cases you could just say "give me the damn permission.." but to be honest I could anticipate wanting a different rationale for each situation...

[I just need to pause and note that Google's new runtime permission model is really, really awful IMO.  In contrast, CyanogenMod just lets the system handle it when needed w/o any action by the developer... which makes SO much more sense to me.]

Anyhoo, back to your comment:

*In this case, the same 'rationale' and 'deny' callbacks would be invoked for all @NeedsPermission methods with identical signatures, if they are present:*

Would there be some way of knowing which rationale is the "default" for the permission?  Is it the first annotated?  What if you supply more than one?  Like in the above example, what if there was a `useCameraRationale` defined, a la:

    @ShowRationale(Manifest.permission.CAMERA)
        void showCameraRationale() {
        }

It would be great if the appropriate one was used...

[I need to break in one more time and say AGAIN how much I hate the way this is implemented by Google.  A *lot* of people are going to be tripped up by all this.]

**Comment by aurae** [comment]
The annotation processor relies heavily on the permission signatures provided in the Annotation in order to do its thing, therefore it would raise a DuplicatedValueException if you provide more than 1 ShowRationale with identical signatures. Maybe if the annotations could optionally be provided with an ID from the user's side, the compiler can stitch together rationale callbacks with the same signature. Something like:

```java
private static final int ID_SHOWCAMERA = 0;
private static final int ID_USECAMERA = 1;

// ...

@NeedsPermission(value = Manifest.permission.CAMERA, id = ID_SHOWCAMERA)
void showCamera() {
}

@NeedsPermission(value = Manifest.permission.CAMERA, id = ID_USECAMERA)
void useCamera() {
}

@ShowsRationale(value = Manifest.permission.CAMERA, id = ID_SHOWCAMERA)
void showCameraRationale() {
}

@ShowsRationale(value = Manifest.permission.CAMERA, id = ID_USECAMERA)
void useCameraRationale() {
}
```

I think it's not very pretty, but it might work (and it's catered to special cases anyway)!

**Comment by hotchemi** [comment]
Right, currently we restrict user to give each annotation to unique value because there is no other way to find related optional annotations.
As @aurae said, we can implement new feature that setting unique id to identify each method, but IMO it may complicate library's api. I don't like it.
Actually our validate is based on `@RuntimePermissions`. I mean you can declare same permission in different activity or fragment. Isn't it enough?

**Comment by hotchemi** [comment]
Any update?

**Comment by hotchemi** [comment]
@fat-tire If u need this feature immediately, please reopen it. I'm gonna close it cos u can handle with this  issue with other way, I guess.

**Comment by fat-tire** [comment]
Well "need" is relative.  Right now I'm skipping API 23 entirely due to the new permissions requirement and hoping Google provides some better suggestions to implement it... <sigh>

**Comment by hotchemi** [comment]
@fat-tire No, I just don't want to complicate the api any more. A ton of developers request a new feature but we have to focus on clean up the interface and which feature is really needed.
In this case, you can implement show rationale logic by yourself right? `@ShowRationale` is just the option and you can handle with `PermissionUtils` may be.

**Comment by fat-tire** [comment]
Yes, I can wing it.  Not a problem.  But I do imagine there will be lots of apps which need to check the same permission in multiple methods within a single activity.  That's the real issue-- multiple `@NeedsPermission`s-- much more than the secondary conversation above about handling `@ShowRationale`s for each individual `@NeedsPermission`.

**Comment by hotchemi** [comment]
OK, actually I have no idea to handle with the problem well but we have to re-consider about of it.

**Comment by TheKlint** [comment]
I have also run into this problem, with multiple methods needing the same permission, so I would really appreciate, if you would prioritise this.

Thanks :+1:

**Comment by Shusshu** [comment]
+1

**Comment by aurae** [comment]
The need to specify mehods with unique `@NeedsPermission` signatures will be lifted in the next release. `@OnShowRationale` and `@OnPermissionDenied` callbacks still need to be unique, with the processor throwing `DuplicatedValueException`s if multiple methods are annotated with the same permission signature, but as for the "using" side, you will be able to annotate multiple methods with the same signature. Those methods will share the corresponding "rationale" and "denied" callbacks, if available.

**Comment by abry00** [comment]
Hallo thanks for your work, I need this functionality as well, may I ask when next release will actually be released?

**Comment by hotchemi** [comment]
@abry00 Oh sorry it's already released at 2.0.1.

**Comment by abry00** [comment]
that is great, but How to add it to the android studio? If I change 2.0.0 (that works with no problems) in build.gradle to 2.0.1 then I get this:

Error:Could not find com.github.hotchemi:permissionsdispatcher-processor:2.0.1.
Searched in the following locations:
    https://jcenter.bintray.com/com/github/hotchemi/permissionsdispatcher-processor/2.0.1/permissionsdispatcher-processor-2.0.1.pom
    https://jcenter.bintray.com/com/github/hotchemi/permissionsdispatcher-processor/2.0.1/permissionsdispatcher-processor-2.0.1.jar
    file:/Users/abry/android/sdk/extras/android/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.0.1/permissionsdispatcher-processor-2.0.1.pom
    file:/Users/abry/android/sdk/extras/android/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.0.1/permissionsdispatcher-processor-2.0.1.jar
    file:/Users/abry/android/sdk/extras/google/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.0.1/permissionsdispatcher-processor-2.0.1.pom
    file:/Users/abry/android/sdk/extras/google/m2repository/com/github/hotchemi/permissionsdispatcher-processor/2.0.1/permissionsdispatcher-processor-2.0.1.jar
Required by:
    TracktivityAS:app:unspecified

**Comment by hotchemi** [comment]
@abry00 Try again, sorry!
