### ISSUE TITLE
I have a problem when use PermissionsDispatcher

### ISSUE THREAD

**Issue by Witype** [hotchemi/PermissionsDispatcher#180]
I ask MultPermission like 
~~~
@NeedsPermission({Manifest.permission.WRITE_EXTERNAL_STORAGE,Manifest.permission.READ_PHONE_STATE})
~~~
when I allow on of the permission and denied the other permission,Next time open the app also will request the permission which has been allowed, 
this is my problem!!!

**Comment by hotchemi** [comment]
@Witype Please check https://github.com/hotchemi/PermissionsDispatcher/issues/69, This is the Android Framework default specification and we just follow it.
