### ISSUE TITLE
Is there a way to use this library on class with static methods?

### ISSUE THREAD

**Issue by HelLViS69** [hotchemi/PermissionsDispatcher#182]
I successfully use this library in my apps, but now I ran into this error:

> Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> permissions.dispatcher.processor.exception.WrongClassException: Class 'PhoneUtils' can't be annotated with '@RuntimePermissions'

Obviously, in a static method I can't access 'this'.. I also tried to pass the Context in other ways but the error still remains and I can't compile

**Comment by tux-world** [comment]
@HelLViS69 could you help me on this issue? https://github.com/hotchemi/PermissionsDispatcher/issues/183 i cant implementing that, and dont ask permission with me

**Comment by HelLViS69** [comment]
@tux-world You have to call ActivityContactLists.syncByServerWithCheck() instead of syncByServer()

**Comment by shiraji** [comment]
https://github.com/hotchemi/PermissionsDispatcher#1-attach-annotations

`@RuntimePermissions` Register an Activity or Fragment to handle permissions

Other that than, this library give you compile error.

**Comment by HelLViS69** [comment]
So, it's quite impossible to use it in an utils/helper class..

**Comment by hotchemi** [comment]
@HelLViS69 Why do you need to annotate util class? I can't find appropriate reason to do that.

**Comment by HelLViS69** [comment]
Hi @hotchemi , simply because I have a static method to execute a phone call and other stuff I use in various parts of the app, so it's more comfortable to have those methods in a dedicated util class instead of rely them in an activity. In this way I can call those methods from all the activities

**Comment by hotchemi** [comment]
@HelLViS69 I think you should handle permissions stuff on Activity/Fragment even if you declare these methods in util class. Because Android Framework just provides requestPermission method on Activity and Fragment. And we don't plan to make it being possible to annotate on Util class.
Anyway thx for your question!
