### ISSUE TITLE
Calling XxxPermisionDispatcher.yyyWithCheck onResume will cause loop @OnNeverAskAgain

### ISSUE THREAD

**Issue by emarc-m** [hotchemi/PermissionsDispatcher#184]
if XxxPermisionDispatcher.yyyWithCheck(target) is called onResume for activity, once the permission is permanently denied, the method @OnNeverAskAgain will be called in an infinite loop.

The reason I'd like to call  XxxPermisionDispatcher.yyyWithCheck onResume is because if the user goes to app settings and manually turns of the permission on the app, PermissionDispatcher will be able to detect the permission was revoked on Activity's onResume.

Thanks.

**Comment by hotchemi** [comment]
@emarc-m Hi, this problem was reported on https://github.com/hotchemi/PermissionsDispatcher/issues/90 and the solution is calling WithCheck method in onStart. Is it okay for your case?

**Comment by emarc-m** [comment]
@hotchemi thanks for the quick response. I think the solution in #90 will be enough. Thanks for the help and good work on the library!
