### ISSUE TITLE
Abstract activity always calls to OnNeverAskAgain

### ISSUE THREAD

**Issue by ClarkXP** [hotchemi/PermissionsDispatcher#185]
When I accept permissions in a Activity that extends of an abstract activity (the annotations was implemented in the abstract activity), always call to OnNeverAskAgain.

**Comment by hotchemi** [comment]
Can you give us a example project which reproduces the problem?

**Comment by ClarkXP** [comment]
Hi @hotchemi. Please close the issue. I did a merge recently from other developer and he commented a permission in the manifest.

Thanks
