### ISSUE TITLE
MainActivityPermissionsDispatcher

### ISSUE THREAD

**Issue by hekaidaqaz** [hotchemi/PermissionsDispatcher#186]
MainActivityPermissionsDispatcher auxiliary class cannot automatically generated, I are according to the step by step operation

**Comment by shiraji** [comment]
Rebuild?

**Comment by hotchemi** [comment]
@hekaidaqaz Have you tried rebuild? If rebuild doesn't help you please have a try with [official sample](https://github.com/hotchemi/PermissionsDispatcher/tree/master/sample).

**Comment by hotchemi** [comment]
Please reopen if needed.

**Comment by hekaidaqaz** [comment]
Thank you, solve the
