### ISSUE TITLE
Could you push the processor library  for java code

### ISSUE THREAD

**Issue by a1018875550** [hotchemi/PermissionsDispatcher#187]
I want to add some code for "Xiaomi" mobile.Because the mobile has some different for normal moible; But I see your processor library is using the kotlin,I don't know how to use the kotlin; so could you push the processor libray for java code; Thanks;

**Comment by hotchemi** [comment]
Sorry, I can't understand...you mean you want to copy the logic?

**Comment by a1018875550** [comment]
yes, I want rewrite to my request;but youre code is kotlin and I can't understand kotlin;So ,do you have java code for the processor library?

**Comment by aurae** [comment]
If you just want to use the library, you don't need to have Kotlin in your project whatsoever! It works fine in your Java projects as well. If you'd like to explore the source of our annotation processor, I'd suggest checking out the repo's history until you arrive at the 1.x releases of the library, since it has only been rewritten using Kotlin in 2.0.0.

The chances of us undergoing the language switch *back to Java* in the near future are pretty slim, though.

**Comment by a1018875550** [comment]
thanks,and the 1.x library is sample to 2.x?

**Comment by aurae** [comment]
There were a few additions to the feature set in 2.x, but it's still mostly the same. The most notable change was the inclusion of native Fragments using an optional dependency, which wasn't available in 1.x.

You can check out our [migration guide to 2.x](https://github.com/hotchemi/PermissionsDispatcher/wiki/Migrating-to-2.x) for details on the changes, but you'll see that it's been mostly just renaming stuff.

**Comment by hotchemi** [comment]
@a1018875550 You can see the source code of the latest 1.x here.
https://github.com/hotchemi/PermissionsDispatcher/tree/1.2.1

Btw can you tell us the plan you're gonna change? Just my interest but I might be able to give you a "folk" of this library for you.

**Comment by a1018875550** [comment]
yeah,Do you the "Xiaomi" chinese  mobile; As you know the android is opend;So they take the android source  put their mobiles but they change some code like the permission ; In "Xiaomi" mobile it's not same as usual to check the permission; Like this to check permission for camera:
<img width="889" alt="qq20160820-0 2x" src="https://cloud.githubusercontent.com/assets/8246218/17816811/b42538c8-666d-11e6-9e31-d4011d7274d7.png">

And I have face other company like "Xiaomi" in China;So I want to rwrite this library to correspond the chinese mobile company;

**Comment by hotchemi** [comment]
Oh dear...not trivial change....
If you use current ver of the library, what kind of mistake will happen?

**Comment by a1018875550** [comment]
the library dosen't work; and the application sometime crashed and the log note me I didn't check permissions, sometime the screen goes black ;

**Comment by a1018875550** [comment]
@hotchemi Could you add this judgment for "Xiaomi" phone;the latest 1.x version run results is very different for the latest 2.x version;And it's not easy to read kotlin for me; And the code for check permissions to "Xiaomi" phone is same as the code in the picture;Just  add AppOpsManger for every permission code;

**Comment by hotchemi** [comment]
@a1018875550 I can't collect enough info of Xiaomi thingy so please feel free to folk it!

**Comment by Turbo87** [comment]
@a1018875550 don't forget to add the original LICENSE file to your [fork](https://github.com/a1018875550/PermissionDispatcher)

**Comment by a1018875550** [comment]
@hotchemi  the <a href="https://github.com/hotchemi/PermissionsDispatcher/blob/master/processor/src/main/kotlin/permissions/dispatcher/processor/impl/BaseProcessorUnit.kt"> ADD_WITH_CHECK_BODY_MAP</a>
what's means;How to achieve this for Java? Thanks!

**Comment by hotchemi** [comment]
Deal with by yourself.
