### ISSUE TITLE
Auto generated class not generated

### ISSUE THREAD

**Issue by tekinarslan** [hotchemi/PermissionsDispatcher#189]
Hi, 
I added library and apt dependency in my library module module, and I add annotations in my fragment(I want to use only fragment). But, auto generated class not generated. After that, I moved dependency in app gradle and class was generated. How can I use this lib in my module project ? 

Thanks,

**Comment by hotchemi** [comment]
@tekinarslan Can you give us a sample? Probably you didn't set apt-plugin or something.

**Comment by tekinarslan** [comment]
sorry.I missed it, I was added plugin into my project module. I will try move and response you. Thanks

**Comment by hotchemi** [comment]
@tekinarslan My pleasure 😃

**Comment by tekinarslan** [comment]
I added "apply plugin: 'android-apt'"  into my app and add dependencies into my library module .Class not generated. When I moved dependencies into my app gradle, Class was generated.
My purpose is that I will add your lib into my lib module as gradle and I use my apps.
Thanks

**Comment by hotchemi** [comment]
Please apply apt plugin to the lib module s well.

**Comment by tekinarslan** [comment]
Added, not generate class. This class only generate this state:
added in my my app gradle: 
 apt 'com.github.hotchemi:permissionsdispatcher-processor:2.1.3'
    compile 'com.github.hotchemi:permissionsdispatcher:2.1.3'
apply plugin: 'android-apt'

Please can you define steps for library project? Also I see that you added library directly into your sample gradle, Could you try compiled version of this dependency as above?

**Comment by hotchemi** [comment]
Can you give us an example which can reproduce the problem? We can't investigate with such a few info.
