### ISSUE TITLE
It can't be used with Dagger 2

### ISSUE THREAD

**Issue by destil** [hotchemi/PermissionsDispatcher#19]
Hi, when I try to use it in a project with Dagger 2, I get this exception during build:

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> permissions.dispatcher.processor.exceptions.WrongClassException: Annotated class must be finished with 'Activity' or 'Fragment'

**Comment by destil** [comment]
I had some issues in Dagger, once I fixed them, I could enable this library again. However the error message from your library was displayed first and it confused me.

**Comment by hotchemi** [comment]
OK
