### ISSUE TITLE
Can i used on RuntimePermissions in baseActivity? 

### ISSUE THREAD

**Issue by shenxiaolin** [hotchemi/PermissionsDispatcher#190]
Hi
   I write a BaseActivity, and used @RuntimePermissions in this class file.
  Then i new A extends BaseActivity.
   I see a auto generated BaseActivityPermisstionDispatcher class.
   so my question is A class can used BaseActivityPermisstionDispatcher check Permission method???
  or Just only used this BaseActivityPermisstionDispatcher method in BaseActivty??

**Comment by hotchemi** [comment]
@shenxiaolin We've not actively thought about it so how is the result?

**Comment by shenxiaolin** [comment]
I see final class BasePermissionActivityPermissionsDispatcher 
this class is final class and just used in one package.
do you think it to change public?

**Comment by hotchemi** [comment]
@shenxiaolin We don't value that kind of improvement. You can deal with that by annotating each extended class right? We don't want to complicate the usage anymore.
