### ISSUE TITLE
Revoking permissions through phone's Settings , will cause application crash while application is running 

### ISSUE THREAD

**Issue by cike2056** [hotchemi/PermissionsDispatcher#191]
Whether you add an interface method used to monitor revoked permission? thx

**Comment by shenxiaolin** [comment]
i occur same problem when user close location permission and application live in background.
I need to monitor revoked permission.
Who can tell us how to do fix it.

**Comment by cike2056** [comment]
@shenxiaolin 如果targetSdkVersion <23可以解决权限问题，但是算不上是真正解决。

**Comment by hotchemi** [comment]
@cike2056 @shenxiaolin You should call method onStart(please do not call it onResume which causes infinite loop.
By the way you should not ask library's usage on issues. Please use StackOverflow.

**Comment by hotchemi** [comment]
And I can't read Chinese at all.

**Comment by cike2056** [comment]
@hotchemi 解決でき、兄さん。すべての発進方法は傍受でクリックした。
情景はたぶん応用転入楽屋は、携帯電話で、再び設置閉鎖権限に応用が崩壊した。

**Comment by cike2056** [comment]
翻訳ソフトウェア表现できないという意味だ.翻訳誤っ.
Using down emoji inappropriately, china-japan friendship, great good.
