### ISSUE TITLE
Won't you like to know which application are using this library?

### ISSUE THREAD

**Issue by tux-world** [hotchemi/PermissionsDispatcher#198]
Won't you like?

**Comment by hotchemi** [comment]
Yup, we already have users list here but contribution is welcome.

https://github.com/hotchemi/PermissionsDispatcher/wiki/Users

**Comment by tux-world** [comment]
@hotchemi very good, could you add this application on google play: https://play.google.com/store/apps/details?id=com.pishguy.androidapplication.shootpaymentservice

after add that, please remove this issue

**Comment by hotchemi** [comment]
@tux-world Addressed. Thx for your cooperation!

**Comment by tux-world** [comment]
@hotchemi any time sir, Thanks to release and support this useful library
