### ISSUE TITLE
add parameter(s) to the @NeedsPermission method

### ISSUE THREAD

**Issue by muetzenflo** [hotchemi/PermissionsDispatcher#200]
A method that needs a permission is called like this:

<pre>
MainActivityPermissionDispatcher.myMethodWithCheck(this);

@NeedsPermission(...)
void myMethod() { ... }
</pre>

Is there any way to add my own parameters to this method call? Something like this:

<pre>
String myArgument = "foobar";
MainActivityPermissionDispatcher.myMethodWithCheck(this, myArgument);

@NeedsPermission(...)
void myMethod(String myArgument) { ... }
</pre>

If not, what's your approach to this problem? Saving everything as class member and re-use it within the actual method??

**Comment by hotchemi** [comment]
@muetzenflo You can do that like here https://github.com/hotchemi/PermissionsDispatcher/blob/master/processor/src/test/java/permissions/dispatcher/processor/data/Source.java#L3042 .

**Comment by muetzenflo** [comment]
I tried that, but the build failed, because of different number of arguments. After a rebuild it's working now. Sorry to bother you and thanks for this really helpful lib!!

**Comment by hotchemi** [comment]
My pleasure 😄
