### ISSUE TITLE
Java 7 support?

### ISSUE THREAD

**Issue by bhargavms** [hotchemi/PermissionsDispatcher#202]
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by shiraji** [comment]
Could you post stacktrace? Does this stop happening if you remove PermissionsDispatcher dependancy? 

By the way, this library's targetCompatibility/sourceCompatibility is [1.6](https://github.com/hotchemi/PermissionsDispatcher/blob/master/processor/build.gradle#L6-L7)

**Comment by bhargavms** [comment]
Im sorry about this, this has nothing to do with your lib

**Comment by hotchemi** [comment]
ok
