### ISSUE TITLE
**PermissionsDispatcher Class not gerenated

### ISSUE THREAD

**Issue by felipecastilhos** [hotchemi/PermissionsDispatcher#217]
Hi,

I did add the annotations:

``` java
@RuntimePermissions
public class MainActivity extends BaseActivity{
...

    @NeedsPermission(Manifest.permission.ACCESS_FINE_LOCATION   )
    public void callSchedule() {
      ...
    }

```

But the dispatcher class was not generated so I can't call:
MainActivityPermissionDispatcher.callScheduleWithCheck()

Any idea what I might be doing wrong?

**Comment by shiraji** [comment]
Rebuild?

**Comment by hotchemi** [comment]
@felipecastilhos Make sure that you added android-apt plugin and tried rebuild.

**Comment by rdbrown** [comment]
I have the same issue as @felipecastilhos.

I am using Android studio 2.2.2. and I have enabled annotation processing. I have rebuilt all several times.  Can you give some guidance?  Thanks.
Here is my app build.gradle:
apply plugin: 'com.android.application'
apply plugin: 'android-apt'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.3"
    defaultConfig {
        applicationId "com.example.myapp"
        minSdkVersion 21
        targetSdkVersion 24
        versionCode 3
        versionName "1.2"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}



dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile 'com.android.support:support-v4:24.2.1'
    compile 'com.android.support:recyclerview-v7:24.2.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.github.hotchemi:android-rate:1.0.1'
    compile 'com.github.hotchemi:permissionsdispatcher:2.2.0'
    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.2.0'
    compile 'org.androidannotations:androidannotations-api:4.0.0'
    apt 'org.androidannotations:androidannotations:4.0.0'
    apt 'com.github.AleksanderMielczarek:AndroidAnnotationsPermissionsDispatcherPlugin:0.1.0'
    testCompile 'junit:junit:4.12'
    compile 'com.google.android.gms:play-services-appindexing:8.4.0'
}

Here is my project gradle file:

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by shiraji** [comment]
Are you using both `apt` and `annotationProcessor`? I'm not sure it is possible to do that.

**Comment by hotchemi** [comment]
@felipecastilhos Did you solve the problem?

@rdbrown Could you try @shiraji 's suggestion? https://github.com/hotchemi/PermissionsDispatcher/issues/217#issuecomment-258715613

**Comment by rdbrown** [comment]
Not yet, I will try your suggestion tomorrow morning and let you know. Thank you for your quick response.

**Comment by ShkurtiA** [comment]
In the readme file it has to be added this line: `annotationProcessor 'org.androidannotations:androidannotations:4.0.0'`. It's not mentioned any where if that should be added in app build.gradle

**Comment by shiraji** [comment]
> `annotationProcessor 'org.androidannotations:androidannotations:4.0.0'`

This is the line that import AA to use [AndroidAnnotationsPermissionsDispatcherPlugin](https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin). I think you should ask @AleksanderMielczarek to update plugin's readme.

**Comment by lfdversluis** [comment]
Got the same issue, not using annotationProcessor, only the line ` annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:2.2.0"` from the readme.

**Comment by hotchemi** [comment]
@lfdversluis Sorry I can't understand what you mean. If you're not using annotation processor the code never would be generated literally.

**Comment by hotchemi** [comment]
Folks, we mixed some problems in the same issue and AndroidAnnotationsPermissionsDispatcherPlugin is not official product of me. So please ask more detail at appropriate place. Thx!

**Comment by rdbrown** [comment]
Yes, I did. Thanks.  I did not read your documentation carefully. It was my
mistake.

On Sun, Nov 6, 2016 at 9:19 PM, Shintaro Katafuchi <notifications@github.com

**Comment by Dev-iL** [comment]
I'd like to add that there's something fishy going on when using PermissionsDispatcher `v2.2.0` in conjunction with `'com.android.tools.build:gradle:2.3.0-alpha1'`, where the `*PermissionsDispatcher` classes are not generated (with no particular error other than that they simply don't exist).

I found a workaround (solution?) by adding the following to my **app**-level `build.gradle`:

```java
android {
    ...
    defaultConfig {
        ...
        javaCompileOptions {
            annotationProcessorOptions {
                className 'permissions.dispatcher.processor.PermissionsProcessor'
            }
        }
        ...
    }
    ...
}
```

The idea came from the possibly-related issue discussed [here](https://code.google.com/p/android/issues/detail?id=227612).

**Comment by gdannyliao** [comment]
I tried both apt and annotationProcessor at the same time, but PermissionsDispatcher Class is not gerenated too. Then I changed annotationProcessor to apt and it works

**Comment by shiraji** [comment]
You cannot mix them.

2017年3月18日(土) 17:18 liao xingyu <notifications@github.com>:
