### ISSUE TITLE
Please recommend the way for GCM/push messages permissions

### ISSUE THREAD

**Issue by OleksandrKucherenko** [hotchemi/PermissionsDispatcher#225]
Hi,

how i understand app does not really need to ask for that, but in many many apps its a best practice to ask user for that before event starting the GCM registration. Can you propose the best way how to integrate the library with this scenario?

Thanks

**Comment by hotchemi** [comment]
GCM doesn't require any permission in Marshmallow or up. It's just about 4.0.3 or something...in that sense you don't have to ask runtime permission.
