### ISSUE TITLE
Update custom lint rules to the new PSI API

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#226]
@felipecsl asked us to update lint rules.

ref: 
- https://twitter.com/felipecsl/status/804105803065999360
- https://github.com/braintree/braintree_android/pull/130/

cc: @shiraji

**Comment by felipecsl** [comment]
friendly ping: any progress on this?

**Comment by shiraji** [comment]
https://github.com/hotchemi/PermissionsDispatcher/pull/227

**Comment by hotchemi** [comment]
Yeah, we're waiting contributor work:D

**Comment by eyedol** [comment]
@hotchemi @shiraji  @felipecsl it looks like we will be porting over to [UAST][1] soon, the new API for analyzing both `.java` and `.kt` files. I'm keeping an eye on it. I thought I should let you guys know.

[1]: https://groups.google.com/forum/#!msg/lint-dev/7nLiXa04baM/KaHIpKFoCQAJ
