### ISSUE TITLE
NeedOnRequestPermissionsResult lint check is firing erroneously

### ISSUE THREAD

**Issue by seanabraham** [hotchemi/PermissionsDispatcher#230]
After https://github.com/hotchemi/PermissionsDispatcher/pull/227 was merged and I bumped the version in app, it looks like there is a misfiring lint check.

This is the check — NeedOnRequestPermissionsResult: Call the "onRequestPermissionsResult" method of the generated PermissionsDispatcher class in the respective method of your Activity or Fragment

And here is code that it is triggering on:
```java
    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions,
            int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        FooBarFragmentPermissionsDispatcher
                .onRequestPermissionsResult(this, requestCode, grantResults);
    }
```

So the call to the PermissionsDispatcher is actually happening but the lint check does not think it is.

cc @eyedol @hotchemi @felipecsl

**Comment by hotchemi** [comment]
@seanabraham Thx! Let me check 🙇

**Comment by shiraji** [comment]
Does it happen if you write like this?

```java
@Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions,
            int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        FooBarFragmentPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
    }
```

I have following code, which does not report anything

```java
@RuntimePermissions
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @NeedsPermission(Manifest.permission.READ_CALENDAR)
    void abc() {
    }

    @Override
    public void onRequestPermissionsResult(int requestCode,
            @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        MainActivityPermissionsDispatcher.onRequestPermissionsResult(this,
                requestCode, grantResults);
    }
}
```

However, when I write the following code, the lint report it as error.

```java
@RuntimePermissions
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    @NeedsPermission(Manifest.permission.READ_CALENDAR)
    void abc() {
    }

    @Override
    public void onRequestPermissionsResult(int requestCode,
            @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        MainActivityPermissionsDispatcher
                .onRequestPermissionsResult(this, requestCode, grantResults);
    }
}
```

**Comment by seanabraham** [comment]
@shiraji I'll give that a shot now

**Comment by seanabraham** [comment]
If it works that's great but still seems like this is definitely a bug, code style shouldn't affect lint success/failure 😛

**Comment by shiraji** [comment]
Have you complete this? I'm ready to send pull request (except testing)

**Comment by hotchemi** [comment]
@shiraji Here you go! Really appreciate!

**Comment by shiraji** [comment]
You can test new commit using jitpack

https://jitpack.io/#shiraji/PermissionsDispatcher/43a4ec3464

**Comment by hotchemi** [comment]
@shiraji Thx for your quick address! This fix will be shipped on this weekend(We're also addressing xiaomi issue).
Btw, we need a SNAPSHOT mechanism for sure.

**Comment by eyedol** [comment]
@shiraji @hotchemi The fix LGTM. I agree a SNAPSHOT will be great. Anything in master should be pushed a SNAPSHOT.

**Comment by hotchemi** [comment]
@seanabraham This change was shipped as 2.3.0. Thx for your reporting! https://github.com/hotchemi/PermissionsDispatcher/releases/tag/2.3.0

**Comment by felipecsl** [comment]
@hotchemi thanks! Do you mind publishing v2.3.0 of the processor artifact as well, so both are the same version, please?

**Comment by hotchemi** [comment]
@felipecsl Sorry release process failed somehow...done 🙇

**Comment by ypresto** [comment]
FYI:
I found this also happens when using [android-apt](https://bitbucket.org/hvisser/android-apt) (`apt`) for processor dependency. Reproduced with android-apt v1.8.

So, changing

```groovy
    apt 'com.github.hotchemi:permissionsdispatcher-processor:2.3.2'
```

to

```groovy
    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.3.2'
```

will fix the issue.

**Comment by hotchemi** [comment]
@ypresto Thx! WE certainly recommend using Android Gradle plugin!

**Comment by richaagr** [comment]
Hey all, I am facing the same issue.
My build.gradle lools like this:
```
compile 'com.github.hotchemi:permissionsdispatcher:2.4.0'
 apt 'com.github.hotchemi:permissionsdispatcher-processor:2.4.0'

```
And the java file has:
```
@Override
 public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
      super.onRequestPermissionsResult(requestCode, permissions, grantResults);
     AssetDetailViewFragmentPermissionsDispatcher.onRequestPermissionsResult(this,requestCode, grantResults);
    }
```

But I am getting a lint error 

> Call the "onRequestPermissionsResult" method of the generated PermissionsDispatcher class in the respective method of your Activity or Fragment

Any ideas on how to get around this?

**Comment by hotchemi** [comment]
Are you using the latest ver?

**Comment by richaagr** [comment]
I am using 2.4, can't upgrade to latest yet because of old gradle version, which can't be upgraded because of some other dependencies unfortunately

**Comment by richaagr** [comment]
I upgrade to the latest version and lint is finally happy. Thanks :)

**Comment by hotchemi** [comment]
👍
