### ISSUE TITLE
Introduce SNAPSHOT mechanism

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#232]
We currently rely on @shiraji 's Jitpack to test new version but by shipping snapshot jar to bintray we can reduce the burden.

**Comment by eyedol** [comment]
What's the status on this? I have some free time this weekend. I could look into this. I'm thinking to adapt [butterKnife's](https://github.com/JakeWharton/butterknife/blob/master/.buildscript/deploy_snapshot.sh). It seems `bintray` doesn't support `SNAPSHOT` artifacts. Unless we go with [JFrog](https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org) (it integrates nicely with bintray) or [Sonatype Nexus](http://central.sonatype.org/pages/ossrh-guide.html) ( quite popular ). Either will require creating an account so it's better someone with release right to look into this ?

**Comment by hotchemi** [comment]
@eyedol Thx! Actually I've not came up with any idea yet. It seems JFrog is easy to integrate with Bintray/JCenter? Of course PR is welcome!😃

http://szimano.org/automatic-deployments-to-jfrog-oss-and-bintrayjcentermaven-central-via-travis-ci-from-sbt/

**Comment by eyedol** [comment]
@hotchemi  Yes JFrog integrates nicely with bintray and jcenter. PR should follow soon 😃
