### ISSUE TITLE
Does it work as expected on Xiaomi device?

### ISSUE THREAD

**Issue by ryugoo** [hotchemi/PermissionsDispatcher#240]
I checked work on Xiaomi Redmi Note 4 (MIUI 8 / Android 6.0).
Chased the flow of the code using the debugger, but I thought that I did not enter the expected processing (`hasSelfPermissionForXiaomi`). The following code is `> 23`, is not it `>= 23` expected work?

\* However, the permission check seemed to be working properly even with the current code.

https://github.com/hotchemi/PermissionsDispatcher/blob/master/library/src/main/android/permissions/dispatcher/PermissionUtils.java#L99
```java
if (Build.VERSION.SDK_INT > Build.VERSION_CODES.M && Build.MANUFACTURER.equalsIgnoreCase("Xiaomi")) {
```

<table>
<tr><th>Device</th><th>Debugger</th></tr>
<tr><td><img src="https://cloud.githubusercontent.com/assets/1000715/21287703/2ac0a3b4-c4b5-11e6-9e8d-f352857806a4.png"></td><td><img src="https://cloud.githubusercontent.com/assets/1000715/21287711/5969dad2-c4b5-11e6-9b56-af2fa11ca35a.png"></td></tr>
</table>

**Comment by a1018875550** [comment]
It's test miui7, maby it's changed in MIUI 8,who knows!As you know,It's xiaomi not google

**Comment by shiraji** [comment]
Is `Build.VERSION.SDK_INT > Build.VERSION_CODES.M` true?

**Comment by shiraji** [comment]
https://github.com/a1018875550/PermissionDispatcher/blob/master/library/src/main/android/org.jokar.permissiondispatcher.library/PermissionUtils.java#L129

Seems this condition is wrong. Should be `Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && Build.MANUFACTURER.equalsIgnoreCase("Xiaomi")`

**Comment by a1018875550** [comment]
the code >= 23 is right;
 It's work in android 6.0 +,not 7.0+; And I test in "xiaomi5"

**Comment by shiraji** [comment]
> However, the permission check seemed to be working properly even with the current code.

By the way, why does it work???

**Comment by eyedol** [comment]
Yes using the constant value of the build version code is the way to go. Lower version of 23 won't have `Build.VERSION_CODES.M`

**Comment by shiraji** [comment]
So guys, is `Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && Build.MANUFACTURER.equalsIgnoreCase("Xiaomi")` correct?

**Comment by eyedol** [comment]
```java
Build.VERSION.SDK_INT >= 23 && Build.MANUFACTURER.equalsIgnoreCase("Xiaomi")
```

This is correct.

**Comment by eyedol** [comment]
We don't support below `M` discard my earlier comment.

**Comment by shiraji** [comment]
Yea, since should be targetSdkVersion >= 23.

Got it. Thanks for your help! @eyedol

**Comment by shiraji** [comment]
Add #242 pull request since `Build.MANUFACTURER` could be null at least in test cases.

So the final condition will be the following:

`Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && "Xiaomi".equalsIgnoreCase(Build.MANUFACTURER)`

**Comment by hotchemi** [comment]
Thx guys! Btw I wanna clarify why `Build.VERSION.SDK_INT >= Build.VERSION_CODES.M` is actually needed? Does it mean that there is no Xiaomi device lower than M in the world?

**Comment by hotchemi** [comment]
@a1018875550 Any thoughts about https://github.com/hotchemi/PermissionsDispatcher/issues/240#issuecomment-267803663?

**Comment by ryugoo** [comment]
Thank you for investigate and fix!

**Comment by hotchemi** [comment]
@ryugoo Really appreciate for your report! 😄
