### ISSUE TITLE
conflicts with butterknife plugin

### ISSUE THREAD

**Issue by gmfbilu** [hotchemi/PermissionsDispatcher#248]
if you use butterknife you will add "apply plugin:android-apt "，and this is will makes your auto generated code dosent wokes well.

**Comment by shiraji** [comment]
That's not PermissionsDispatcher's issue. Which version of android gradle plugin do you use?

**Comment by gmfbilu** [comment]
2.2.3



来自 魅族 PRO 5



-------- 原始邮件 --------
发件人：Yoshinori Isogai <notifications@github.com>
时间：周六 12月24日 21:22
收件人：hotchemi/PermissionsDispatcher <PermissionsDispatcher@noreply.github.com>
抄送：gmfbilu <gmfbilu@hotmail.com>,Author <author@noreply.github.com>
主题：Re: [hotchemi/PermissionsDispatcher] conflicts with butterknife plugin (#248)

**Comment by shiraji** [comment]
Then, you have to pick using [android-apt](https://bitbucket.org/hvisser/android-apt) or `annotationProcessing`, because they cannot coexist. I would suggest using `annotationProcessing`.

Read https://bitbucket.org/hvisser/android-apt/wiki/Migration to migrate `android-apt` to `annotationProcessor`

**Comment by shiraji** [comment]
As you can see it, this is totally not related with PermissionsDispatcher. So I closed this issue. If you migrate to annotationProcessing and still have problem, let us know.

**Comment by gmfbilu** [comment]
thanks a lot


发送自 Outlook<http://aka.ms/weboutlook>

________________________________
发件人: Yoshinori Isogai <notifications@github.com>
发送时间: 2016年12月25日 2:01:25
收件人: hotchemi/PermissionsDispatcher
抄送: gmfbilu; Author
主题: Re: [hotchemi/PermissionsDispatcher] conflicts with butterknife plugin (#248)


Then, you have to pick using android-apt<https://bitbucket.org/hvisser/android-apt> or annotationProcessing, because they cannot coexist. I would suggest using annotationProcessing.

Read https://bitbucket.org/hvisser/android-apt/wiki/Migration to migrate android-apt to annotationProcessor

―
