### ISSUE TITLE
permissionsdispatcher-processor:2.3.1 seems not available

### ISSUE THREAD

**Issue by shaunkawano** [hotchemi/PermissionsDispatcher#255]
Hi @hotchemi and other contributors, 
Thank you so much for providing such an amazing library first of all; it helps me and surely other developers a lot to develop new apps with handling permissions capability.

I have been using PermissionsDispatcher a while ago and recently I tried to update it to the latest version by specifying the latest `2.3.1` version on my build.gradle file:

```
compile 'com.github.hotchemi:permissionsdispatcher:2.3.1'
annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.3.1'
```

And it seems like the latest version(2.3.1) of `permissionsdispatcher-processor` is not available thus it fails to compile. Below is the result I got when I checked the versions using [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin):

```
The following dependencies are using the latest milestone version:
...
 - com.github.hotchemi:permissionsdispatcher-processor:2.3.0

The following dependencies have later milestone versions:
...
 - com.github.hotchemi:permissionsdispatcher [2.3.0 -> 2.3.1]
```

Thank you in advance!

**Comment by hotchemi** [comment]
Thx! Let me check...

**Comment by hotchemi** [comment]
Sorry it turned out error had happened when publishing to bintray...now investigating.

**Comment by hotchemi** [comment]
@shaunkawano I just published processor module to jcenter!
I just forgot to remove https://github.com/hotchemi/PermissionsDispatcher/pull/256 so build failed before executing upload.
Thx for your catch!!! 👍

**Comment by shaunkawano** [comment]
@hotchemi Thank you very much for your quick fix! The compilation was successful! 👍
