### ISSUE TITLE
onShowRationale and onPermissionDenied never call while request SYSTEM_ALERT_WINDOW permission

### ISSUE THREAD

**Issue by Congeek** [hotchemi/PermissionsDispatcher#258]
it will go to the system setting page directly and call OnNeverAskAgain when i turn back , it's because this permissions is a non-standard flow?

**Comment by hotchemi** [comment]
OnNeverAskAgain should be called when user deny permission with checkbox checked.
Can you give me an example project to reproduce?

**Comment by hotchemi** [comment]
@Congeek Please reopen if needed.
