### ISSUE TITLE
Please add FAQ to your Wiki

### ISSUE THREAD

**Issue by E3V3A** [hotchemi/PermissionsDispatcher#267]
This is a great app, but it is very hard to get started, As most questions one have, may be hidden away under various `closed` issues. Can you please consider adding some of these questions to an FAQ.

For example: 

- How do you add multiple permissions?
- How are group permissions handled?
- How are the different API versions handled?

**Comment by hotchemi** [comment]
@E3V3A Thx for your proposal. As you said we still have insufficient document so let us address.

> How are the different API versions handled?

Can I clarify which part do you mention?

**Comment by E3V3A** [comment]
> How are the different API versions handled?

The Question is,  what is the API range that PD can handle. I.e. If we use PD, is it compatible with everything from API 1 to API 25, or do we still need to handle below M differently etc.? Basically, what are the current limitations of PD?

**Comment by hotchemi** [comment]
ic. Actually we cover below M behaviour so there's no rest task for user.

**Comment by hotchemi** [comment]
this issue will be integrated to https://github.com/hotchemi/PermissionsDispatcher/issues/49. so let me close.
