### ISSUE TITLE
Not working if build tool version is >=25

### ISSUE THREAD

**Issue by 3niman** [hotchemi/PermissionsDispatcher#270]
## Overview

- I'm working on a android project with **Build Tool Version 25.0.2** and added dependency for Permission Dispatcher. When i am building the project, library is not generating any Permission Dispatcher classes at all corresponding to any Activity or Fragments which has annotation **@RuntimePermissions**.
It is working fine if Build tool version downgrades to <25.

**Comment by hotchemi** [comment]
@3niman Thx for your opening. Can you remember the error message?

**Comment by aurae** [comment]
This is very peculiar. I'm always on the latest build tools and haven't noticed any odd behavior. To add to @hotchemi's point, does compilation finish without errors, or do you have a stack trace for us?

**Comment by 3niman** [comment]
@aurae Yes compilation finishes without any error, but no Dispatcher files generated.

Also i have tested with a project which is initially running on build tool version 24.0.3 and working fine. But when changed build tool version to 25.0.2 and Rebuild the project, all the generated Dispatcher file gone.
Rolled back the build tool version to 24.0.3 and its working fine.

**Comment by hotchemi** [comment]
@3niman Umm, it's kinda weird...

- Do you use any other libraries that use annotation processing?
- Can you give us a sample proj that can reproduce the problem?

**Comment by OleksandrKucherenko** [comment]
I can confirm that it works fine with the latest build tools.

**Comment by aqibgatoo** [comment]
it is not working with annotationProcessor but with apt on **Build Tool Version 25.0.2**

**Comment by aqibgatoo** [comment]
using the old way as apt rather that annotationProcessor it works on **Build Tool Version 25.0.2**

**Comment by aurae** [comment]
I'm really inclined to say that the issue isn't with PermissionsDispatcher directly, but your specific setup. Do you have any other code-generating annotation processors in your project that stop working when using Build Tools 25.0.2 & the `annotationProcessor` configuration? If not, could you just add one and test it out, like ButterKnife or LoganSquare?

**Comment by aqibgatoo** [comment]
i already had ButterKnife and i used the `annotationProcessor ` instead of apt plugin and nothing was generated ..**Build Tool Version 25.0.2**

**Comment by shiraji** [comment]
Guys. We need code. Please give us a minimum project that reproduce the issue.

**Comment by hotchemi** [comment]
Yes, we need a sample code to reproduce the problem.

**Comment by vickychijwani** [comment]
I'm facing this too. Here is a test project in the `permissions-dispatcher` branch (it's not minimal though, sorry): https://github.com/vickychijwani/quill/tree/permissions-dispatcher. And you can see the build failure on CircleCI here: https://circleci.com/gh/vickychijwani/quill/173. Can this issue be re-opened please?

Other observations:
- Changing build tools version to 24.x didn't seem to help, but I only tried once, quickly
- Other libraries _may_ be interfering with PermissionsDispatcher, these are the suspects:
   - Retrolambda + gradle-retrolambda (backports Java 8 lambdas to Java 7)
   - Realm (persistence library, uses annotations on model classes)
   - Hugo (Jake Wharton's method call logging library)
   - ButterKnife (view injection library)
   - Retrofit (HTTP interface generator)
   - Gson (JSON <=> POJ converter)

**Comment by aurae** [comment]
Thank you for reporting!  We will have a look into your sample code shortly, trying to reproduce the issue.

**Comment by shiraji** [comment]
Update realm. I sent [PR](https://github.com/vickychijwani/quill/pull/163). This still has compile error because of realm version but at least PD generates `PostEditFragmentPermissionsDispatcher`

#219 It seems this report is correct. Realm v1.x is not working with PD.

**Comment by hotchemi** [comment]
wow weird...anyway thx @shiraji!
@vickychijwani can u check?

**Comment by aurae** [comment]
@3niman Did you use Realm alongside PD as well when you ran into this issue?

**Comment by vickychijwani** [comment]
@hotchemi @shiraji Thanks for looking into this. I guess it's time for me to update Realm - I had been putting it off :smile:. Moving from Realm 1.x to 2.x will take me a few days, I'll report back once I'm done!

**Comment by vickychijwani** [comment]
@hotchemi @shiraji so after upgrading Realm, `MyFragmentPermissionsDispatcher` is generated and seems to work... except the `@OnPermissionDenied` and `@OnNeverAskAgain` are never called. I tried debugging in the auto-generated class, and was surprised to find that Android doesn't call `onRequestPermissionsResult` if the user denies the request! I tested on Android 7.1.1 and 6.0 emulators.

I'm sure my code is somehow wrong but I can't quite figure out where 🤔 . Could you help me out by looking at the code in [permissions-dispatcher branch](https://github.com/vickychijwani/quill/commit/3c52dbf861f5fc7cdabccf6e6e6032fc87570f92)?

**Comment by vickychijwani** [comment]
Uh oh, I realized my mistake as soon as I posted. I forgot to call the delegate's `onRequestPermissionsResult` 😛. Silly me.

**Comment by vickychijwani** [comment]
Everything works perfectly now 🎉. Final working commit is [here](https://github.com/vickychijwani/quill/commit/2d43fce2dcb59debd6795a6b1592a44b9f65f932). This issue can be closed if needed.

**Comment by aurae** [comment]
Happy to hear that, @vickychijwani! :)
