### ISSUE TITLE
Has conflict with Android Data Binding

### ISSUE THREAD

**Issue by aprofromindia** [hotchemi/PermissionsDispatcher#272]
## Overview

- while using with SupportMapFragment and Android Data binding adding @RuntimePermissions annotation on an Activity results in failing DataBinding class generation

### Expected

- normal usage

## Environment

- Play Maps version 9.6, Permissions Dispatcher - 2.3.1, Android Studio 2.2.3

**Comment by aurae** [comment]
Do you have a stack trace for us, or any other compiler output? Or is it simply not generating the Data Binding code?

**Comment by aprofromindia** [comment]
false flag.
