### ISSUE TITLE
provide request permission in showDeniedFor*** callback

### ISSUE THREAD

**Issue by jkwangbest** [hotchemi/PermissionsDispatcher#273]
## Overview

- showDeniedFor*** callback, can we request permission again ? To my understanding, we can't request permission in showNeverAskForCamera callback.
### Expected

- provide a callback to request permission in showDeniedFor*** callback.

Why Needed: If we request a necessary permission, if user denied permission, then it will invoke showDeniedFor*** callback, in this callback, we want request permission again when people press a button.

**Comment by hotchemi** [comment]
@jkwangbest thx for your suggestion. Technically you can but it will cause a infinite loop and I don't recommend it. It'll alarm user obiously. I recommend to show a polite message why the permission is needed and lead user to click a button or something to show a popup dialog again.

**Comment by jkwangbest** [comment]
@hotchemi Yes, The permission is  necessary. If we can no get the permission, we will not let the user use our app. In showDeniedFor*** callback, I've already show a dialog to explain why we need the permission.
