### ISSUE TITLE
Does not seem to be working for Kotlin projects

### ISSUE THREAD

**Issue by Redrield** [hotchemi/PermissionsDispatcher#275]
## Overview

- When compiling a Kotlin activity class with the required annotations, the PermissionsDispatcher class is not generated

### Expected

- Class should be generated.

## Environment

- Using library ver 2.3.1, macOS Sierra, latest Android Studio build (unclear on specific version num), compiling for SDK 25 (Nougat)

## Reproducible steps

- https://gist.github.com/Redrield/2438d2eec9a963051114453203ed66ff (This specific project is failing to generate the PermissionsDispatcher class, when the equivalent class written in plain Java functions fine)

**Comment by shiraji** [comment]
Could you give us build.gradle?

**Comment by Evisceration** [comment]
be sure to use the kotlin annotation processor (kapt)

compile "com.github.hotchemi:permissionsdispatcher:${permissionsDispatcherVersion}"
kapt "com.github.hotchemi:permissionsdispatcher-processor:${permissionsDispatcherVersion}"

**Comment by Redrield** [comment]
Thanks @Evisceration, that seems to have worked (Also it seems the original tutorial I was following was a tad older, and so was using the approach for the android plugin < 2.2

**Comment by hotchemi** [comment]
Thank you guys!

**Comment by Redrield** [comment]
I think I found what the specific issue is. When trying to execute the 'app' configuration in Android Studio, the generated classes are somehow deleted. Building and installing the apk manually works fine, but running that specific configuration causes issues

**Comment by Redrield** [comment]
Update after doing some experimenting. The library does not seem to be showing the dialog for me, using either Kotlin or java. I'm trying to request a dangerous permission (read contacts), using a physical Nexus 5 running a custom ROM of Android N, and a Nexus 5X in AVD. When I try to call MainActivityPermissionsDispatcher.thingWithCheck(this) in the main activity (Namely when a button is clicked), I immediately get a permission denied notification

**Comment by hotchemi** [comment]
@Redrield Please make sure calling `super.onRequestPermissionsResult` in overriden `onRequestPermissionsResult`. If you won't solve the problem please go to stackoverflow.
