### ISSUE TITLE
Fragment#onActivityResult() don't called when Fragment added in FragmentActivity

### ISSUE THREAD

**Issue by S-MILE-S** [hotchemi/PermissionsDispatcher#277]
add Fragment in FragmentActivity:
`getSupportFragmentManager()
                        .beginTransaction()
                        .add(R.id.fragment_container,
                                Fragment.instantiate(this, fName))
                        .commitAllowingStateLoss();`

I find the code in FragmentPermissionsDispatcher :
`Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION, Uri.parse("package:" +     target.getActivity().getPackageName()));
  target.getActivity().startActivityForResult(intent, REQUEST_ADDVIEWTOWINDOW);`
target.getActivity() return the FragmentActivity.if  FragmentActivity#startActivityForResult() be called, there are only FragmentActivity#onActivityResult() be called. 
so i try to use 'target.startActivityForResult(intent, REQUEST_ADDVIEWTOWINDOW);'   instead of  'target.getActivity().startActivityForResult(intent, REQUEST_ADDVIEWTOWINDOW);` in MyFragmentPermissionsDispatcher(copy from FragmentPermissionsDispatcher ). it works, Fragment#onActivityResult() is be called.

But ,  it's not a good way. so i want know how to use the PermissionsDispatcher in Fragment which added in FragmentActivity.

**Comment by shiraji** [comment]
Are you asking the best way to integrate PermissionsDispatcher in `Fragment` which is added in `FragmentActivity`?

**Comment by S-MILE-S** [comment]
yes @shiraji

**Comment by shiraji** [comment]
Yea. I think this is a bug. I will fix this.

https://github.com/hotchemi/PermissionsDispatcher/blob/master/processor/src/main/kotlin/permissions/dispatcher/processor/impl/helper/SystemAlertWindowHelper.kt#L19 this generates

```java
target.getActivity().startActivityForResult(intent, REQUEST_ADDVIEWTOWINDOW);
```

It should use `Fragment#startActivityForResult` not `Activity#startActivityForResult`

**Comment by shiraji** [comment]
This is what you report, right? @S-MILE-S

**Comment by S-MILE-S** [comment]
yes，it‘s working.
