### ISSUE TITLE
permissions.dispatcher.processor.exception.SupportV13MissingException with gradle plugin  2.4.0-dev

### ISSUE THREAD

**Issue by ivangonzalez88** [hotchemi/PermissionsDispatcher#279]
## Overview

Hi,

I have an issue with permission dispatcher, it is throwing the below exception even if i add a dependency for support-v13. The issue happens when i use the following:

gradle plugin  version 
com.android.tools.build:gradle:2.4.0-dev 
wrapper
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

Everything works fine on 'com.android.tools.build:gradle:2.2.3', but i actually depend on de 2.4.0-dev version.

Caused by: permissions.dispatcher.processor.exception.SupportV13MissingException: PermissionsDispatcher for annotated class 'AlertActivationFragment' can't be generated, because the support-v13 dependency is missing on your project
	at permissions.dispatcher.processor.impl.NativeFragmentProcessorUnit.checkPrerequisites(NativeFragmentProcessorUnit.kt:25)
	at permissions.dispatcher.processor.impl.BaseProcessorUnit.createJavaFile(BaseProcessorUnit.kt:34)
	at permissions.dispatcher.processor.PermissionsProcessor.process(PermissionsProcessor.kt:70)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)

### Expected

 Be able to compile and run.

### Actual

 not compiling, annotation processing not working

## Environment

gradle plugin  version 
com.android.tools.build:gradle:2.3.0-dev 
wrapper
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

buildscript {
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
allprojects{
repositories{
        maven { url "https://jitpack.io" }
}
}
dependencies{
    compile 'com.github.hotchemi:permissionsdispatcher:2.1.3'
    apt 'com.github.hotchemi:permissionsdispatcher-processor:2.1.3'
    compile 'org.androidannotations:androidannotations-api:4.0.0'
    apt 'org.androidannotations:androidannotations:4.0.0'
    apt 'com.github.AleksanderMielczarek:AndroidAnnotationsPermissionsDispatcherPlugin:0.1.0'
}

## Reproducible steps

Just add annotations for processing and change the gradle plugin version 

Thanks & Regards!

**Comment by aurae** [comment]
Are you using Jack? I'm trying to figure out if this issue is connected to #220. Also, I was unaware of the `-dev` qualifier. I'm using `2.3.0-rc1` without a problem - is `-dev` like some sort of bleeding-edge build?

**Comment by hotchemi** [comment]
@ivangonzalez88 any update?

**Comment by ivangonzalez88** [comment]
Hi, sorry about for the delay. The issue persist, but weird thing is that it just happen with gradle-dev versions, i thought the gradle version was public, but i was wrong, sorry about that. I can see that even with a v-13 dependency, NativeFragmentProcessorUnit cannot access to it and it throws the exception. If i annotate android.app.Fragment with @RuntimePermissions, the it fails immediately but it works fine with android.support.v4.app.Fragment.

**Comment by ivangonzalez88** [comment]
Hi, so the issue is fixed, the problem was that i did not get rid of android-apt, and is a deprecated plugin. Thanks for your help

**Comment by hotchemi** [comment]
ok!

**Comment by brian-chu-twc** [comment]
I am using gradle 3.4.1 and build tools 25.0.0 and I saw the same error.

**Comment by hotchemi** [comment]
@brian-chu-twc Thx. can you give us a sample project that can reproduces the problem?

**Comment by ankitbatra11** [comment]
I can see this issue with Android Studio 2.4 Release preview 6 where there is no jack compiler (as Google deprecated it) but java 8 support enabled:

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

```
compile 'com.github.hotchemi:permissionsdispatcher:2.3.2'
compile 'com.android.support:support-v13:25.3.1'
annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.3.2'
```

**Comment by hotchemi** [comment]
@ankitbatra11 Thx. Probably https://github.com/nebula-plugins/gradle-extra-configurations-plugin causes the error and we'll work on this issue on this weekend.

**Comment by ankitbatra11** [comment]
@hotchemi Thanks

**Comment by AlexTip** [comment]
Hi gyus!
Is there any solution for this problem at the moment?

**Comment by hotchemi** [comment]
Ah sorry, wait a bit.

**Comment by AlexTip** [comment]
@hotchemi I'm so sorry for interrupting but once again: when can we expect suggested fix to be published?

**Comment by hotchemi** [comment]
@AlexTip by 5/1! I had been kinda busy but I'm having a vacation from today so I'll be able to work on 🙇

**Comment by hotchemi** [comment]
@AlexTip Can you check with 2.4.0-SNAPSHOT? Now you don't have to add v13 dependency by yourself.

```gradle
repositories {
  jcenter()
  maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
}

dependencies {
  compile 'com.github.hotchemi:permissionsdispatcher:2.4.0-SNAPSHOT'
  annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.4.0-SNAPSHOT'
}
```

**Comment by aurae** [comment]
FWIW, I was able some information on the behavioral change in the Android Gradle plugin, which finally clears up the issue:

https://developer.android.com/studio/preview/features/index.html?utm_source=android-studio#annotationProcessor_config

> In previous versions of the Android plugin for Gradle, dependencies on the compile classpath were automatically added to the processor classpath. (...) (You) can restore behavior to that of Android plugin 2.3 by setting includeCompileClasspath true.

With PermissionsDispatcher 2.4.0, the issue is not a problem anymore. However, if anybody wants to try the includeCompileClasspath setting in PD 2.3.2, that *should* also work.

**Comment by sud007** [comment]
Needed this to work inside the DialogFragment but was facing the same issue. Using the snapshot version fixed it for me.
