### ISSUE TITLE
PermissionsDispatcher class removed when running 'app' and causes build failure

### ISSUE THREAD

**Issue by Redrield** [hotchemi/PermissionsDispatcher#281]
## Overview

- When trying to run the 'app' auto generated configuration, the <Activity>PermissionsDispatcher class is removed and isn't generated in time for the build to succeed.

### Expected

- Class either shouldn't be removed, or should be regenerated in time for the build to succeed

### Actual

- Class is removed and build fails

## Environment

- 2.3.1
- n/a; build doesn't succeed. 
- Latest Windows 10 build, latest Android studio build

## Reproducible steps

- Import example project into intellij, build to generate permissions dispatcher, then try to run 'app'

**Comment by shiraji** [comment]
What do you mean ”remove”？ Have you ever seen XxxPermissionsDispatcher classes?

Have you gone through ISSUE_TEMPLATE's FAQ?

```
Before you add the issue, please make sure to read over the following Frequently Asked Questions:

**"XxxPermissionsDispatcher class is not generated"**

- Did you add `@RuntimePermissions` to your class, and `@NeedsPermission` to your method?
- Did you try a Rebuild? (Sync is not Rebuild!)
- Don't mix `apt` and `annotationProcessor`!
- If you're in Kotlin, use `kapt`!
- If you're using Realm 1.x., please consider upgrading to 2.x (refer to Issue #270: https://github.com/hotchemi/PermissionsDispatcher/issues/270)
- If you checked all these steps, and the generated classes are still not showing up, then attach your Activity/Fragment class, and build.gradle.
```

**Comment by Redrield** [comment]
Yes, I've looked through the FAQs
Also, what I mean by remove is that the class is there before the build, and I can reference the methods inside of it. When I start the build, the references to the class go red, and the build fails because it can't resolve those references.

**Comment by shiraji** [comment]
Have you used other annotation processing library? Like ButterKnife, dagger, or AndroidAnnotations.

**Comment by shiraji** [comment]
Oops, I should've ask this one first...is your Android Studio enabled to use anntation processing? 

http://stackoverflow.com/questions/38642712/enable-annotation-processors-option-in-android-studio-2-2

**Comment by Redrield** [comment]
I should have noted this before. When I just build the project, the class is generated. So annotation processing does work. If I manually go to Build -> Generate APK and install it, it works fine. It's just running this particular configuration where it breaks, and this is a big issue for me because my only seeming alternative is to use a way of debugging my app that is much less than optimal

**Comment by shiraji** [comment]
Isn't that the same issue with above StackOverFlow?

**Comment by Redrield** [comment]
Changing that doesn't seem to do anything. Look, this is what happens when I try to run the app configuration (Bearing in mind that before running it these references were valid and recognized by the IDE)
http://prntscr.com/ec1y5v

**Comment by shiraji** [comment]
Could you post Activity and build.gradle or give us minimum sample project?

**Comment by Redrield** [comment]
https://gist.github.com/Redrield/20a0594306db52c8899b39f580b9513a

**Comment by shiraji** [comment]
Could you try https://github.com/shiraji/PD-281 ?

**Comment by Redrield** [comment]
That worked fine. What did you do different?

**Comment by shiraji** [comment]
Check second commit. you missed kotlin-kapt

Thanks for verifying PD/Android Studio/kapt works fine in Windows environment!👌 (I don't have it!!!)

**Comment by Redrield** [comment]
Aah! Yep, that's why. Thanks!
