### ISSUE TITLE
Error when call pickImage() method

### ISSUE THREAD

**Issue by thanhlv93** [hotchemi/PermissionsDispatcher#293]
Hi There,
I have issue when tried to call method pickImage() and got a message :
android.os.transactiontoolargeexception data parcel size bytes

My gradle :

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha9'
    compile 'com.isseiaoki:simplecropview:1.1.4'
    compile 'com.github.hotchemi:permissionsdispatcher:2.3.2'
    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.3.2'
}

And my java code :

case R.id.buttonPickImage:
                    MainFragmentPermissionsDispatcher.pickImageWithCheck(MainFragment.this);
                    break;

I run app on android 7.1 , i don't know how to fix this issue , please tell me if you have anything suggest.

**Comment by shiraji** [comment]
From Android 7, the behavior of Intent changes.

https://developer.android.com/about/versions/nougat/android-7.0-changes.html#other

By the way, this is totally off topic. PermissionsDispatcher has nothing with this problem.
