### ISSUE TITLE
onActivityResult() method is not generated by dispatcherPermissions class

### ISSUE THREAD

**Issue by JottaReyes** [hotchemi/PermissionsDispatcher#294]
## FAQs

build.gradle

compile 'com.github.hotchemi:permissionsdispatcher:2.3.2'
annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.3.2'

 
___

## Overview

ClassPermissionsDispatcher.onActivityResult(this, requestCode) not been generated

### Expected

Generated class allows the use of onActivityResult(this, requestCode) method

### Actual

Generated class does not allow the use of onActivityResult(this, requestCode) method

## Environment

- Which library version are you using?
2.3.2
- On which devices do you observe the issue?
Samsung Galaxy S7 edge, Android 6.0.1

- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by shiraji** [comment]
Could you post `@NeedsPermission` method? or whole `@RuntimePermission` class?

**Comment by hotchemi** [comment]
@JottaReyes please give us a sample code.

**Comment by hotchemi** [comment]
@JottaReyes pls reopen if needed.
