### ISSUE TITLE
Array vs Single Permission Usage.

### ISSUE THREAD

**Issue by himanshuvirmani** [hotchemi/PermissionsDispatcher#297]
If we give an array based permission request like
```

@NeedsPermission({ Manifest.permission.READ_EXTERNAL_STORAGE,
      Manifest.permission.READ_PHONE_STATE,
      Manifest.permission.GET_ACCOUNTS,
      Manifest.permission.ACCESS_COARSE_LOCATION})
```
Singular rationale annotations do not work(Corresponding callback is not called). We have to give all permission array in rationale too which does not make a lot of sense.

`@OnShowRationale(Manifest.permission.READ_EXTERNAL_STORAGE)`

**Comment by hotchemi** [comment]
@himanshuvirmani this is the specification of the library. If you want to use `showRationale` with single permission please split `NeedsPermission`'s arguments to each corresponding one.
