### ISSUE TITLE
MainActivityPermissionsDispatcher not be created after build the project?

### ISSUE THREAD

**Issue by CK875430315** [hotchemi/PermissionsDispatcher#298]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by shiraji** [comment]
Why do you ignore the template??? Since you don't give us any clue to figure out the problem, I will close this issue.
