### ISSUE TITLE
Callback invoked on old instance of fragment after rotation while "Allow app to {user permission}" is shown.

### ISSUE THREAD

**Issue by iaypym** [hotchemi/PermissionsDispatcher#299]
Hi there!

I have following issue with permission dispatcher:
**Current behavior**
Permission dispatcher invokes callback on old instance of fragment. 
It happens with following steps:
1. FragmentNameFragmentPermissionsDispatcher.callbackMethodWithCheck is called
2. System dialog (something like "Allow this app to read contacts") is shown to user.
3. User rotate device.
4. User clicks on Allow
5. callbackMethod is called on old instance of fragment

**Expected behavior:**
Permission dispatcher invokes callback on current fragment instance.

**Requirements**
It happens only when callbackMethod have following declaration:
```java
@NeedsPermission(READ_CONTACTS)
void callbackMethod(Bundle bundle);
```
i.e. callbackMethod must have bundle argument.
This behavior observed on LG K10 (Android 7.0), Huawei P8 Lite(Android 7.0), Genymotion emulator (Android 7.0)
PermissionDispatcher version - 2.1.3 and 2.3.2

PermissionDispatcher generates following code for onRequestPermissionsResult:
```java
static void onRequestPermissionsResult(FragmentName target, int requestCode, int[] grantResults) {
    switch (requestCode) {
      case REQUEST_CALLBACKMETHOD:
      if (PermissionUtils.getTargetSdkVersion(target.getActivity()) < 23 && !PermissionUtils.hasSelfPermissions(target.getActivity(), PERMISSION_CALLBACKMETHOD)) {
        target.showPermissionDenied();
        return;
      }
      if (PermissionUtils.verifyPermissions(grantResults)) {
        if (PENDING_CALLBACKMETHOD != null) {
          PENDING_CALLBACKMETHOD.grant();
        }
      } else {
        if (!PermissionUtilsV13.getInstance().shouldShowRequestPermissionRationale(target, PERMISSION_CALLBACKMETHOD)) {
          target.showNeverAskAgainReadContactsPermission();
        } else {
          target.showPermissionDenied();
        }
      }
      PENDING_CALLBACKMETHOD = null;
      break;
      default:
      break;
    }
  }
```

**Comment by hotchemi** [comment]
@iaypym Thx for your report. Can I ask the reason of below?

> i.e. callbackMethod must have bundle argument.

**Comment by iaypym** [comment]
@hotchemi It generates the above code only if callback is declared with an argument. When i declare callback without it - PermissionDispatcher generates different code in onRequestPermissionResult (without 
```java
if (PENDING_CALLBACKMETHOD != null) {
          PENDING_CALLBACKMETHOD.grant();
        }```
)

**Comment by iaypym** [comment]
@hotchemi It happens because PENDING_CALLBACKMETHOD doesn't update reference to fragment.
It means that if original fragment is recreated it will contain old instance of fragment not recreated.

**Comment by hotchemi** [comment]
@iaypym Umm it might be a bug. Can you give us an example that reproduces the bug?
