### ISSUE TITLE
Rewriting processor module in Kotlin

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#3]

**Comment by hotchemi** [comment]
Doing in kotlin branch.

**Comment by hotchemi** [comment]
After releasing 1.2.0. Restart this issue. I'm gonna recreate kotlin branch again.

**Comment by aurae** [comment]
I have started working on the Kotlin implementation and enhancements in my fork (not pushed yet, though)! I will inform you once it's available.

**Comment by hotchemi** [comment]
Wow amazing! You should push it!

**Comment by aurae** [comment]
Available now in the kotlin-new branch. Most of the test suite needs to be ported, but other than that the foundation for future development in Kotlin is created!

**Comment by hotchemi** [comment]
I created wip pull request so close this issue.
