### ISSUE TITLE
when permission is not permit,and 'Don’t ask again'.   

### ISSUE THREAD

**Issue by ygysgit** [hotchemi/PermissionsDispatcher#300]
some phone like huawei P8max(android 6.0) and dazen note3(android 5.1) 。   if select 'not permit',and 'Don’t ask again'.     

click will not answer(Like didn't click)

**Comment by ygysgit** [comment]
ContextCompat.checkSelfPermission  always return 0 ,in effect is 'not permit',and 'not answer again'.

**Comment by shiraji** [comment]
Let me clarify what you are asking. If the user taps "not permit" with "Don’t ask again", `ContextCompat.checkSelfPermission` returns `PERMISSION_GRANTED` in some device? (PERMISSION_GRANTED is constant value of 0)

**Comment by ygysgit** [comment]
yes ,(ContextCompat.checkSelfPermission)is always return 0。

**Comment by shiraji** [comment]
That's ugly. Do you know how to fix this issue?

**Comment by hotchemi** [comment]
well, I think this is the bug of Android framework or hardware manufacturer?
we can't do anything about that...
@ygysgit can you clarify that you'll get the same result without PermissionsDispatcher?

**Comment by ygysgit** [comment]
@hotchemi i guess so , and i have email to  hardware manufacturer about this question,if  replay i will tell you.

**Comment by hotchemi** [comment]
@ygysgit great! so let me close the issue for the time being and please comment something if you get a response from them.
