### ISSUE TITLE
There is a problem when permissions are denied on Flyme 6 

### ISSUE THREAD

**Issue by jasonlee3652** [hotchemi/PermissionsDispatcher#303]
## FAQs

 
___

## Overview

There is a problem when permissions are denied on Flyme 6 ，I select Cancel authorization button，the current activity Would finish，After each click activity will be closed。

### Expected

how to compatible Flyme 6?

### Actual

- What is the actual behavior?

## Environment

android sdk 25

Flyme 6 (base android 23)

## Reproducible steps

run your sample module on Flyme 6,You can see。

**Comment by aurae** [comment]
Thanks for reporting! I don't have a device running on Flyme 6 myself. Does the sample app crash? If so, could you copy the stacktrace from Logcat and provide it to us? Otherwise, it would be very helpful if you could provide a small gif or mp4 recording of the issue you're facing.

**Comment by jasonlee3652** [comment]
mp4: https://drive.google.com/open?id=0B0oBMkFEv_yqU2o1eHJ1VkpOZnc

On other platforms are right，except Flyme 6。

I found that Flyme 6 had a camera permission by default

The first time to install,`PermissionUtils.hasSelfPermissions(target, PERMISSION_SHOWCAMERA) ` is true。

```
if ( PermissionUtils.hasSelfPermissions(target, PERMISSION_SHOWCAMERA)) {
 target.showCamera();
 }
```
then  target.showCamera() will execute，This time will pop up the system prompt box about permissions，If i refuse，The program will not execute any of the generated method from delegate，But directly close the current activity。After each click button_camera activity will be closed，and leading to interface stuck For a while.

i try this(first install):

`                
boolean c;
               
 if (ContextCompat.checkSelfPermission(MainActivity.this,Manifest.permission.CAMERA)
                != PackageManager.PERMISSION_GRANTED) {
                   c= false;
                }else{
                    c = true;
                    Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);// 启动系统相机
                    startActivityForResult(intent, 1);
                }`

c is true！

What is the reason for this?

**Comment by hotchemi** [comment]
@jasonlee3652 Thx. But unfortunately it seems we're not be able to do anything about the problem...because it's just the Android library not for Android forked one 🤔 

- `Flyme 6 had a camera permission by default`
  - Pretty unexpected but that's fine!
- `But directly close the current activity`
  - Do you implement `onActivityResult` correctly?
  - If so can you implement the same thing without PermissionsDispatcher and confirm the result?
- `What is the reason for this?`
  - We dunno about Flyme 6 so sorry...

Please reopen if needed.

**Comment by jasonlee3652** [comment]
Thx.I found the cause of the problem.
1.Flyme 6 had a camera permission by default
2.when excute Camera.open(cameraId) method,Flyme 6 will pop up the system prompt box about permissions ,if i refuse,`Camera camera = Camera.open(cameraId)`,c is not null! but camera is null On other platforms.The problem is here.An exception will happen to continue,throw `java.lang.RuntimeException: Camera is being used after Camera.release() was called`.
I found a solution to determine whether the user refused:

```
public static booleanisCameraUseable() {
boolean canUse =true;
Camera mCamera =null;
try{
mCamera = Camera.open();
// setParameters for Flyme 6。MX5 Camera.open() return not null on Flyme 6.
Camera.Parameters mParameters = mCamera.getParameters();
mCamera.setParameters(mParameters);
}catch(Exception e) {
canUse =false;
}
 if(mCamera !=null) {
 mCamera.release();
 } 
return canUse;
 }
```
THX.My English is bad,  i  do not know if you can understand.haha!!!

**Comment by aurae** [comment]
Thanks for the additional info! It's fascinating how some platforms deviate from the norm, and "do their own thing" in some regards. I'm glad you were able to catch the difference in Flyme's behavior in regards to the camera.
