### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by ligi** [hotchemi/PermissionsDispatcher#318]
It seems that the permssionsdispatcher is breaking reproducibility of apps:

https://verification.f-droid.org/org.ligi.passandroid_338.apk.diffoscope.html

Would it be possible to always create the same code?

**Comment by aurae** [comment]
Thanks for reporting! So if I understand this correctly, you're building two APKs back-to-back, diff them, and it generates ever-so-slightly different code?

Right now, I suppose it has to be related to the auto-incrementing request codes associated with each generated method. The order in which the annotation processor detects the methods might not always be the same.

**Comment by ligi** [comment]
Yes and Yes. Here some more infos regarding the problem: 
 https://f-droid.org/wiki/page/Deterministic,_Reproducible_Builds

Your analysis sounds plausible - would it be a hard-fix to have always the same order? I never used annotation-processors from this side ;-)

**Comment by aurae** [comment]
No, it shouldn't be an involved fix - we can make the RoundEnvironment produce ordered lists with a simple String predicate, I assume.

@shiraji @hotchemi I'm taking this one, if you don't mind!

**Comment by hotchemi** [comment]
@ligi @aurae Thx guys! 🇩🇪

**Comment by hotchemi** [comment]
anyone working on the issue?

**Comment by aurae** [comment]
Sorry about that. I started work on this a while back, but I wasn't able to finish due to external responsibilities. I'm heading back to working on this momentarily.

**Comment by aurae** [comment]
Okay, here it is guys. Please excuse the delay 🙇

**Comment by ligi** [comment]
Great you found the time to work on this - I know these "external responsibilities" sometimes suck big time - no excuse needed! Thanks for your work!!

**Comment by hotchemi** [comment]
@aurae thx for your swift work!
