### ISSUE TITLE
MainActivityPermissionsDispatcher cann't find this symbol !

### ISSUE THREAD

**Issue by Abdelsattar** [hotchemi/PermissionsDispatcher#319]
I'm trying to use this lib but this is what shown to me 
http://imgur.com/a/mZou9  (pic link)

i use      compile 'com.github.hotchemi:permissionsdispatcher:2.4.0'

and add @RuntimePermissions for class but is still give me error 

and i rebuild the project multiple times

**Comment by shiraji** [comment]
Did you try these???

Before you add the issue, please make sure to read over the following Frequently Asked Questions:

**"XxxPermissionsDispatcher class is not generated"**

- Did you add `@RuntimePermissions` to your class, and `@NeedsPermission` to your method?
- Did you try a Rebuild? (Sync is not Rebuild!)
- Don't mix `apt` and `annotationProcessor`!
- If you're in Kotlin, use `kapt`!
- If you're using Realm 1.x., please consider upgrading to 2.x (refer to Issue #270: https://github.com/hotchemi/PermissionsDispatcher/issues/270)
- If you checked all these steps, and the generated classes are still not showing up, then attach your Activity/Fragment class, and build.gradle.

**Comment by Abdelsattar** [comment]
my gradel 
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.developer.compersionexample"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha9'
    testCompile 'junit:junit:4.12'
    compile 'com.zxy.android:tiny:0.0.5'
    compile 'com.zhihu.android:matisse:0.4.3'
    compile 'com.github.hotchemi:permissionsdispatcher:2.4.0'

//    compile('com.github.hotchemi:permissionsdispatcher:${2.4}') {
//        // if you don't use android.app.Fragment you can exclude support for them
//        exclude module: "support-v13"
//    }
//    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:${2.4}'
}
`

**Comment by Abdelsattar** [comment]
activity 
`package com.example.developer.compersionexample;

import android.Manifest;
import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.support.annotation.RequiresApi;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.zhihu.matisse.Matisse;
import com.zhihu.matisse.MimeType;
import com.zhihu.matisse.engine.impl.GlideEngine;

import java.io.File;
import java.util.List;

import permissions.dispatcher.NeedsPermission;
import permissions.dispatcher.OnNeverAskAgain;
import permissions.dispatcher.OnPermissionDenied;
import permissions.dispatcher.RuntimePermissions;

@RuntimePermissions
public class MainActivity extends AppCompatActivity implements View.OnClickListener{

    private ImageView imOrginalPic;
    private TextView txtImgSize;
    private Button btnSelectImge;
    private ImageView comperessedImge;
    private TextView txtCompressedImgSize;
    private int REQUEST_CODE_CHOOSE = 500;

    List<Uri> mUris;


    private void findViews() {
        imOrginalPic = (ImageView)findViewById( R.id.imOrginalPic );
        txtImgSize = (TextView)findViewById( R.id.txtImgSize );
        btnSelectImge = (Button)findViewById( R.id.btnSelectImge );
        comperessedImge = (ImageView)findViewById( R.id.comperessedImge );
        txtCompressedImgSize = (TextView)findViewById( R.id.txtCompressedImgSize );

        btnSelectImge.setOnClickListener( this );
    }


    @Override
    public void onClick(View v) {
        if ( v == btnSelectImge ) {
            // Handle clicks for btnSelectImge
            MainActivityPermissionsDispatcher.pickUpImageWithCheck(this);
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN)
    @NeedsPermission(Manifest.permission.READ_EXTERNAL_STORAGE)
    void pickUpImage(){
        Matisse.from(MainActivity.this)
                .choose(MimeType.allOf())
                .countable(true)
                .maxSelectable(9)
                .restrictOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED)
                .thumbnailScale(0.85f)
                .imageEngine(new GlideEngine())
                .forResult(REQUEST_CODE_CHOOSE);
    }


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        findViews();
    }


    @OnPermissionDenied(Manifest.permission.READ_EXTERNAL_STORAGE)
    void showDeniedForCamera() {
        Toast.makeText(this, "permission_camera_denied", Toast.LENGTH_SHORT).show();
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN)
    @OnNeverAskAgain(Manifest.permission.READ_EXTERNAL_STORAGE)
    void showNeverAskForCamera() {
        Toast.makeText(this, "permission_camera_neverask", Toast.LENGTH_SHORT).show();
    }

    int getFileSize(String filePath) {
        File file = new File(filePath);
        return Integer.parseInt(String.valueOf(file.length() / 1024));
    }


    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == REQUEST_CODE_CHOOSE && resultCode == RESULT_OK) {
            mUris = Matisse.obtainResult(data);
            for (int i = 0; i <mUris.size() ; i++) {
                Log.d("Matisse", "mSelected: " + mUris.get(i));
                Log.d("Matisse", "mSelected: " + mUris.get(i).getEncodedPath());
                Log.d("Matisse", "mSelected: " + mUris.get(i).getPathSegments());
                Log.d("Matisse", "mSelected: " + mUris.get(i).getPath());


            }
        }

    }
}
`

**Comment by aurae** [comment]
In your build.gradle, you've accidentally excluded the `annotationProcessor` dependency on PermissionDispatcher's processor. Please include that dependency and rebuild.

**Comment by Abdelsattar** [comment]
No i did it on propose as it gives me that 

Error:(34, 13) Failed to resolve: com.github.hotchemi:permissionsdispatcher:${2.4}
<a href="openFile:D:/Sattar/Android/Compersionexample/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by shiraji** [comment]
What is `${2.4}` ???

**Comment by Abdelsattar** [comment]
{latest.version}

  annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:${latest.version}'

**Comment by titoaesj** [comment]
in you file build.gradle (project) add  `ext.permissionsdispatcher_version = '2.4.0'`

**Comment by satnamvision** [comment]
@Abdelsattar  how you have solved this problem. i am getting the same problem
