### ISSUE TITLE
Activity or Fragment behaves strange when the method needs permission is called in "OnCreate" or "OnResume" 

### ISSUE THREAD

**Issue by VersaceSilva** [hotchemi/PermissionsDispatcher#322]
## FAQs

 
___

## Overview

- I just put the method which needs permissions in "OnResume" or "OnCreate",it means that the method will be called when this activity or fragment is created,but the permission request dialog will show again and again if i click"deny" button,if i choose "never ask again" and deny this request,the toast in "@OnPermissionDenied" will show and never disappear,then this activity will be stuck and you can't exit.

### Expected

- If i click "deny" button or choose "nerver ask again" and click the "deny" button,the dialog should not show anymore,and the "@OnPermissionDenied" should only be called once.

### Actual

- Actually,if i deny the permission request,the dialog will show again and again,and the method "@OnPermissionDenied" will be called again and again,which may be the reason why the activity or fragment is stuck.

## Environment

- Library version:2.4.0
- On Huawei P9

## Reproducible steps

- just put the "@NeedsPermission" method for example "NotesActivityPermissionsDispatcher.loadDataWithCheck(mNotesActivity);" in "OnResume" or "OnCreate",this issue will happen.But if this method is put in "OnClick",it behaves normal

**Comment by hotchemi** [comment]
@VersaceSilva If you're calling annotated method in `onResume`, the problem might be a https://github.com/hotchemi/PermissionsDispatcher/issues/90. Could you check?

**Comment by VersaceSilva** [comment]
@hotchemi Thank you very much,it helps.

**Comment by noam2** [comment]
@hotchemi  i also have this problem, but i need to check contacts permissions every time the user returns to the app in OnResume(), so i can't put it in OnStart(), What Should I Do ?

**Comment by hotchemi** [comment]
@noam2 

> i need to check contacts permissions every time the user returns to the app in OnResume(),

I think the only way to avoid the problem is that not calling permission related method in `onResume`. If user turn off any permission the process of corresponding app would be restarted according to Android developers document.
