### ISSUE TITLE
infinite loop in onResume

### ISSUE THREAD

**Issue by noam2** [hotchemi/PermissionsDispatcher#323]
i have a problem when i put the check permission method in onResume and click deny it keeps showing a dialog. I can't move it to onStart because i need to check contacts permissions every time the user returns to the app in OnResume(), so i can't put it in OnStart(), What Should I Do ?

**Comment by shiraji** [comment]
Duplicate #90

**Comment by aurae** [comment]
To elaborate on this a little more: We share Android's official guideline's advice when it comes to requesting permissions inside a lifecycle method. Please consider an alternative approach to your use case, where you can safely ask for permission in `onStart()` - I can't think of a scenario where that wouldn't be possible. If necessary, ask again when the user does something (e.g. click on a button that performs the permission-protected action). We're simply compliant with the official stance on this behavior here.

**Comment by noam2** [comment]
@aurae Hey thanks for ansewring. As i Wrote - it's not possible for me to do that and call it in onStart, as i said i need to check the contacts phone every time the activity is started/restarted/resumed etc'. 
And @shiraji  - this is not a duplicate , maybe next time red the question then reply, the solution there doesn't apply for my case.

**Comment by hotchemi** [comment]
> i need to check contacts permissions every time the user returns to the app in OnResume(),

You went to the wrong direction because if you remove the library you'll encounter the same situation. I recommend to fix to call it onStart or check permission granted state by yourself.

**Comment by noam2** [comment]
why would i encounter the same situation ? and why can't you fix it because this a bug

**Comment by hotchemi** [comment]
pls read the issue carefully and address without the library. you'll find out what we mean!

**Comment by noam2** [comment]
Sorry i don't understand , what issue are you referring to ? mine ? #90 ? your readme ? and you suggest not to use your library for this problem ?

**Comment by farmazon3000** [comment]
@noam2 he means that your problem is not relevant (not caused by) the library. If you'd try to implement it without the lib, then you'd encounter exactly the same problem.
