### ISSUE TITLE
How do I passing arguments？

### ISSUE THREAD

**Issue by Adusta** [hotchemi/PermissionsDispatcher#324]
I have a method 
@NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
    private void writeToSD(String param1,String param2) {
       ...
    }
but I only can use XXXActivityPermissionsDispatcher.xxxWithCheck(this) to making the method execute.

How do I pass arguments?

Should I declare parameters as global variables? or other solutions？

**Comment by hotchemi** [comment]
@Adusta we support argument with `Needspermission` annotation like the following.

https://github.com/hotchemi/PermissionsDispatcher/blob/master/processor/src/test/java/permissions/dispatcher/processor/data/Source.java#L995

**Comment by Adusta** [comment]
thanks
