### ISSUE TITLE
 could you update the support library to 25.4.0

### ISSUE THREAD

**Issue by a1018875550** [hotchemi/PermissionsDispatcher#332]
the  support library is update to 25.4.0,could you update it. Thank's!

**Comment by shiraji** [comment]
Do we need this to up-to-date @hotchemi @aurae ?

**Comment by aurae** [comment]
@a1018875550 Are there any relevant bug fixes in regards to Runtime Permissions in 25.4.0? Gradle will automatically augment the transitive dependency, so we shouldn't need to keep up-to-date at all costs otherwise. Does the automatic version switch not work for you?

**Comment by hotchemi** [comment]
We'll plan it for sure but I'd say it's nor urgent, so let us include the update to next release.
I'm gonna close this issue for the time being but if you're in trouble please reopen.
