### ISSUE TITLE
Is it possible to customise/change the permission flow?

### ISSUE THREAD

**Issue by rohangoqii** [hotchemi/PermissionsDispatcher#333]
I want to show the rationale after clicking Deny for the first time. After the Rationale is displayed, now if the user clicks on "Retry" then the permission is displayed once again(with the don't ask again checkbox).

**Comment by aurae** [comment]
We are following the platform's Runtime Permission flow, which doesn't allow for customization of the system dialog boxes per se. However, you can implement your own logic into a `@OnPermissionDenied` method, showing a dialog as necessary for your use case. The "Retry" button of that dialog would then be connected to calling the permission-protected method again.

**Comment by hotchemi** [comment]
@rohangoqii as @aurae explained we follow the official flow which is explained in [Android developers](https://developer.android.com/training/permissions/requesting.html) and also you can show rationale related UI in `OnPermissionDenied` easily by your side.

**Comment by rohangoqii** [comment]
Thanks for taking the time to respond! I will rethink the permissions flow. 
(P.S: You guys have done a superb job with the library!)
