### ISSUE TITLE
Code in NeedsPermission does not execute first time

### ISSUE THREAD

**Issue by cmendes0101** [hotchemi/PermissionsDispatcher#337]
## Overview

Button to go to contacts to select a phone number. When user accepts permission dialog the code in NeedsPermission does not execute and user has to click the button again.

### Expected

Expected behavior is the code in NeedsPermission would be executed. In this case:
Intent intent = new Intent(Intent.ACTION_PICK, ContactsContract.CommonDataKinds.Phone.CONTENT_URI);
startActivityForResult(intent, PICK_DESTINATION_CONTACT_REQUEST);

### Actual

User accepts permission and nothing happens from NeedsPermission. User needs to click the button again(no additional permissions display) and then executes the code.

## Environment

- Which library version are you using? 2.3.2
- On which devices do you observe the issue? Appears to be all devices, Nexus 5x and Pixel recently tested.
- Note any other information that might be useful.

**Comment by hotchemi** [comment]
@cmendes0101 thx, I tried with sample module but couldn't reproduce it.
could you give us tiny example project which can reproduce the problem?

**Comment by shiraji** [comment]
> Which library version are you using? 3.1.0

3.1.0??? Current latest PermissionsDispatcher version is v2.4.0.

**Comment by cmendes0101** [comment]
Sorry version is actually 2.3.2. Copied the wrong package version. Let me go head and upgrade to 2.4.0

**Comment by hotchemi** [comment]
@cmendes0101 any update? let me reopen if you're still in trouble.

**Comment by CherryPepsi** [comment]
@hotchemi I am still seeing this issue with lib version 2.4.0 and Android OS versions 7.1.1 and 7.1.2.

Has this issue been reported elsewhere?

**Comment by yektasarioglu** [comment]
I have that issue, too. Any ideas, why it happens?
