### ISSUE TITLE
Error:Module 'com.github.amigold.fundapter2:library:1.02' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by Sitaraam** [hotchemi/PermissionsDispatcher#345]
## FAQs

 
___

## Overview

- Describe the issue briefly

### Expected

- What is the expected behavior?

### Actual

- What is the actual behavior?

## Environment

- Which library version are you using?
- On which devices do you observe the issue?
- Note any other information that might be useful

## Reproducible steps

- While it's not required, it'd be perfect to add a link to a sample project where you encounter the issue

**Comment by aurae** [comment]
This issue is unrelated to this library. Please report your issue to the maintainers of Fundapter2.
