### ISSUE TITLE
Not generate *.kt file with use 3.0-SNAPSHOT

### ISSUE THREAD

**Issue by a1018875550** [hotchemi/PermissionsDispatcher#347]
I try used the 3.0-SNAPSHOT, and this is my code; but it not generate *.kt file when I build project
![image](https://user-images.githubusercontent.com/8246218/28373341-a839a7f6-6cd4-11e7-8fe7-1cf833b23566.png)

![image](https://user-images.githubusercontent.com/8246218/28373378-bf26d164-6cd4-11e7-81bd-7199dfb00df4.png)

---

is there a mistake here?

**Comment by hotchemi** [comment]
@a1018875550 can you try to use kapt3? https://kotlinlang.org/docs/reference/kapt.html
seems you're using old ver of kapt.

**Comment by a1018875550** [comment]
thank's, I add the ```apply plugin: 'kotlin-kapt'``` it's working

**Comment by hotchemi** [comment]
OK! waiting your feedback.
