### ISSUE TITLE
Module depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by laomo** [hotchemi/PermissionsDispatcher#35]
Warning:Module 'com.github.hotchemi:permissionsdispatcher:1.2.1' depends on one or more Android Libraries but is a jar

**Comment by laomo** [comment]
In my case, many repositories(JCenter, Central and https://jitpack.io/) in my project.  so I need write like this:
```
dependencies {
  compile 'com.github.hotchemi:permissionsdispatcher:1.2.1@aar'
  apt 'com.github.hotchemi:permissionsdispatcher-processor:1.2.1'
}
```

**Comment by HarryMMR** [comment]
I'm still facing the same error. Adding @aar doesn't help either. Somebody help please!

**Comment by apperside** [comment]
same issue here, any solution? Really can't find out what does it mean!

**Comment by hotchemi** [comment]
@apperside Have you tried https://github.com/hotchemi/PermissionsDispatcher#download ?

**Comment by apperside** [comment]
tried what exactly? I followed all the steps indicated but when I sync the project with gradle I receive the error message

Error:Module 'com.github.hotchemi:permissionsdispatcher:2.1.2' depends on one or more Android Libraries but is a jar

I modified the **project** build.gradle adding 

classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'

to the dipendences


and modified the **app** build.gradle adding the plugin and the dependencies

**Comment by gokselguren** [comment]
Same issue occured.

**Comment by gokselguren** [comment]
Encountered same issue

**Comment by shiraji** [comment]
So, have you guys add following code?

project build.gradle

```gradle
buildscript {
  dependencies {
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
  }
}
```

app build.gradle

```gradle
apply plugin: 'android-apt'

dependencies {
  compile 'com.github.hotchemi:permissionsdispatcher:2.1.3'
  apt 'com.github.hotchemi:permissionsdispatcher-processor:2.1.3'
}
```

**Comment by jschnall** [comment]
Why was this closed?  I'm still seeing the issue.  My gradle files look just like what shiraji has posted above.

**Comment by hotchemi** [comment]
Yup it's the general problem of Gradle.

**Comment by hotchemi** [comment]
@Xiaolin-Zhu https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/35#issuecomment-235432557

**Comment by vishnu8742** [comment]
This link solved my problem.
[https://libraries.io/github/magiepooh/RecyclerViewPager](https://libraries.io/github/magiepooh/RecyclerViewPager)
