### ISSUE TITLE
How to do for multiple permissions for specific function?

### ISSUE THREAD

**Issue by polaris0227** [hotchemi/PermissionsDispatcher#351]
`@NeedsPermission(Manifest.permission.CAMERA)
@NeedsPermission(Manifest.permission.READ_EXTERNAL_STORAGE)
void myFunction() {
        ...
    }`

As you can see, I need 2 permissions allowed to call this function.
Please give your advice.
Thanks.

**Comment by aurae** [comment]
Our annotations accept arrays as their parameter, so you'd specify multiple permissions in the same annotation [like so](https://github.com/hotchemi/PermissionsDispatcher/blob/master/sample/src/main/java/permissions/dispatcher/sample/MainActivity.java#L57):

```java
@NeedsPermission({Manifest.permission.CAMERA, Manifest.permission.READ_EXTERNAL_STORAGE})
```

**Comment by polaris0227** [comment]
Thanks.

**Comment by hotchemi** [comment]
Thx!

**Comment by hardikamal** [comment]
@hotchemi Tried this but not working.
