### ISSUE TITLE
Generate unique request code

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#36]
Now, we generate request code from zero per `@RuntimePermissions` annotated class.
But it may cause conflict when the user annotate base class and extended class or like that at once. 
So, we should generate completely unique code in the app or provide a option like this.

```java
@RuntimePermissions(requestCodeBase=100)
```

**Comment by aurae** [comment]
I don't think we should transfer the burden of request code bookkeeping to the user, however I do see the point and the potential issue with inheritance. I think we should implement a global request code counter for the processor round-trip. Let's add this to 2.0 and the Kotlin revision, though!

**Comment by hotchemi** [comment]
Actually it's the feedback from the user. 
It's just the couner case but the same thing happen when you use Activity which has anntated fragment.

**Comment by hotchemi** [comment]
And when it comes to the Kotlin, I've been thinking which we should go, Java8 or Kotlin...
And I wanna discuss about the stuff at the pr issue.
