### ISSUE TITLE
Gradle sync fail

### ISSUE THREAD

**Issue by Maxxan** [hotchemi/PermissionsDispatcher#37]
I follow the instructions how to import the library, but I get this error:
Error:Could not GET 'https://jitpack.io/com/github/hotchemi/permissionsdispatcher-processor/1.2.1/permissionsdispatcher-processor-1.2.1.pom'. Received status code 401 from server: Repository not found or requires authentication

Android studio 1.5

**Comment by Maxxan** [comment]
I figured out it was due to the order of repositories. When jitpack.io was last one, then it worked.

**Comment by hotchemi** [comment]
You should see https://github.com/hotchemi/PermissionsDispatcher/issues/35.
