### ISSUE TITLE
ShowsRationales callback

### ISSUE THREAD

**Issue by mtrakal** [hotchemi/PermissionsDispatcher#39]
Hi, 

it would be nice, when we could show Dialog (or do any other action) on calling ShowsRationales. Now it's possible show some Toast, but you can not interact on it. 
Everything what you open is overlap by permission dialog, which is called immediately. 

In some cases is better show dialog with OK button than toast. When you make app for older people, they like Click on button after read a message, than autohide message like Toast.

**Comment by Maxxan** [comment]
+1 
It would be very useful!

**Comment by aurae** [comment]
In version 2, we introduce the concept of a PermissionRequest object, which is passed to ShowRationale callbacks. On those, you call either `proceed()` or `cancel()` depending on whether you want the request to "go through" or abort. You will be able to defer this choice to a listener click in a Dialog, for instance, which will resolve this issue!

**Comment by hotchemi** [comment]
OK, we should discuss about the interface!
@aurae Any idea?

**Comment by aftabsikander** [comment]
@aurae When you guys are planning to release version 2. As of now I heavily plan on getting this feature to show user some explanation about why i need this permission.

**Comment by aurae** [comment]
This is now released as version 2.0.0. Check out the wiki for a quick migration guide!
