### ISSUE TITLE
README Dependencies 2.0.0 ?

### ISSUE THREAD

**Issue by SmallMouth** [hotchemi/PermissionsDispatcher#40]
I cant download 
```groovy
dependencies {
  compile 'com.github.hotchemi:permissionsdispatcher:2.0.0'
  apt 'com.github.hotchemi:permissionsdispatcher-processor:2.0.0'
}
```
And I check maven, the latest is 1.2.1? right?
https://bintray.com/hotchemi/maven/permissionsdispatcher/view

**Comment by hotchemi** [comment]
Ah sorry currently our latest one is 1.2.1. So please use it.

**Comment by SmallMouth** [comment]
thank you!
