### ISSUE TITLE
Service support

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#41]
It's more convenient to support Service or something on those lines which has no ui.

**Comment by aurae** [comment]
It would be easy to plug in a new `ProcessorUnit` implementation for `android.app.Service` classes into the processor. The main question here relates to the problem of showing a system UI dialog (or a rationale, fwiw) in a context which shouldn't have a presentable UI, such as a dialog. How should we go about this?

**Comment by hotchemi** [comment]
Sorry, I'm gonna close this issue because I think it's out side scope of this library.
Yes, we can show notification and launch activity to show dialog to grant permission, but developer can do it with current version.
If some issue would be reported, we should reconsider about it!
