### ISSUE TITLE
DeniedPermission does not work in a Fragment v4

### ISSUE THREAD

**Issue by Shusshu** [hotchemi/PermissionsDispatcher#42]
I can make it work in an Activity but not in a support v4 Fragment

**Comment by hotchemi** [comment]
What is the error?

**Comment by SmallMouth** [comment]
I think because,
now support ActivityCompat/FragmentCompat,
but if use v4 Fragment need use requestPermissions
http://developer.android.com/intl/zh-tw/reference/android/support/v4/app/Fragment.html#requestPermissions(java.lang.String[],%20int)

http://stackoverflow.com/questions/32890702/request-runtime-permissions-from-v4-fragment-and-have-callback-go-to-fragment

**Comment by Shusshu** [comment]
Nothing... it doesn't do anything....

**Comment by hotchemi** [comment]
@Shusshu Sorry what u mean?

**Comment by Shusshu** [comment]
There are no errors and nothing else happens

**Comment by hotchemi** [comment]
Hey, I can't understand what happened.
Please explain what 'DeniedPermission does not work' actually means.

**Comment by aurae** [comment]
Could you please share a code excerpt with the annotated @NeedsPermission and @DeniedPermission methods, your Fragment's `onRequestPermissionsResult()` implementation, and the call to the respective generated method?

**Comment by Shusshu** [comment]
Here is some code

    //User event
	@Override
	public void onClick(View v) {
		MyFragmentPermissionsDispatcher.pickContactsWithCheck(MyFragment.this);
	}
	
	
	@NeedsPermission(Manifest.permission.READ_CONTACTS)
    void pickContacts() {
        // pick contact using contact api
    }

    @DeniedPermission(Manifest.permission.READ_CONTACTS)
    void deniedActionForContacts() {
        // launch intent to pick a contact
    }

    @ShowsRationale(Manifest.permission.READ_CONTACTS)
    void showRationaleForContacts() {
        Toast.makeText(getActivity(), "showRationaleForContacts", Toast.LENGTH_SHORT).show();
    }
	
	@Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        MyFragmentPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
    }

**Comment by aurae** [comment]
This very code works perfectly for me. Are you verifying that `onClick()` is actually called? What version of the library are you using? Could you share the source of the generated `MyFragmentPermissionsDispatcher` class?

**Comment by hotchemi** [comment]
@Shusshu Please check the generated code again. If anything is wrong, please reopen this issue.
