### ISSUE TITLE
Can cordova/phonegap plugins use this?

### ISSUE THREAD

**Issue by lovelyelfpop** [hotchemi/PermissionsDispatcher#43]
Can cordova/phonegap plugins use this?

**Comment by hotchemi** [comment]
Not sure but this plugin uses annotation processing and generates java code. So it seems impossible...

**Comment by lovelyelfpop** [comment]
@hotchemi I think it is possible. corodva plugins(android) are written in java and the "CordovaPlugin" class is just like "Activity".
But I don't know how to do it, I am not really good at android development.
![qq 20151124145223](https://cloud.githubusercontent.com/assets/5656924/11359871/fd38e38e-92ba-11e5-945f-0f030135805d.png)

**Comment by lovelyelfpop** [comment]
![123](https://cloud.githubusercontent.com/assets/5656924/11360075/5ac205a2-92bc-11e5-85ca-34c4bc2619c4.png)

[CordovaPlugin.java.txt](https://github.com/hotchemi/PermissionsDispatcher/files/42439/CordovaPlugin.java.txt)

**Comment by hotchemi** [comment]
Could u try it? If something is wrong, please ping me.
And if your app doesn't use Activity-extended class, you can't use this library.

**Comment by aurae** [comment]
Judging from the screenshots you provided, PermissionsDispatcher is most likely incompatible with Cordova at this point, even beside the fact that we don't know if it even supports annotation processing using the apt. It would require the generated code to pick up on the Cordova environment and generate something based on that.
