### ISSUE TITLE
What is the problem? 

### ISSUE THREAD

**Issue by lovelyelfpop** [hotchemi/PermissionsDispatcher#44]
![qq 20151124133528](https://cloud.githubusercontent.com/assets/5656924/11358708/46b202f8-92b0-11e5-91e2-83e825522ff4.png)

**Comment by hotchemi** [comment]
Did u add jcenter as repository?
Please see https://github.com/hotchemi/PermissionsDispatcher/blob/ver1.x/build.gradle#L15.
