### ISSUE TITLE
Support "never ask again"

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#48]
We can check the user has checked "never ask again" or not by the following code.

```java
@Override
public void onRequestPermissionsResult(int requestCode, String[] permissions,
    int[] grantResults) {
  super.onRequestPermissionsResult(requestCode, permissions, grantResults);

  switch (requestCode) {
    case REQUEST_CODE:
      if (!verifyPermissions(grantResults)) {
        if (shouldShowRequestPermissionRationale(REQUIRE_PERMISSION)) {
          // show error
        } else {
          // Never ask again.
          // show app settings guide.
        }
      } else {
        // do something.
      }
  }
}

public boolean verifyPermissions(@NonNull int... grantResults) {
  for (int result : grantResults) {
    if (result != PackageManager.PERMISSION_GRANTED) {
      return false;
    }
  }
  return true;
}
```

And in these case, we should lead the user to system setting activity to grant the permission.

```java
Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
Uri uri = Uri.fromParts("package", getPackageName(), null);
intent.setData(uri);
startActivity(intent);
```

**Comment by aurae** [comment]
This could be handled by adding a new annotation for callbacks in the "Never ask again" case. Something like `@OnNeverAskAgain` maybe? I would like to have another callback for this rather than dictate the redirection to the system settings ourselves. This way, the users can decide how to handle this case on their own.

**Comment by hotchemi** [comment]
Nice interface :+1:

**Comment by hotchemi** [comment]
It would be nice to add the following method to `PermissionUtils` :-)

```java
Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
Uri uri = Uri.fromParts("package", getPackageName(), null);
intent.setData(uri);
return intent;
```

**Comment by aurae** [comment]
You mean, as a utility function for our library's users that want to redirect to the app settings directly? Sure thing!

**Comment by hotchemi** [comment]
Yup it's not necessary stuff but might be helpful :-)

**Comment by aurae** [comment]
This has been implemented and will be deployed with the next release.
