### ISSUE TITLE
SYSTEM_ALERT_WINDOW and WRITE_SETTINGS support

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#50]
From Android Developers,

```
There are a couple of permissions that don't behave like normal and dangerous permissions. SYSTEM_ALERT_WINDOW and WRITE_SETTINGS are particularly sensitive, so most apps should not use them. If an app needs one of these permissions, it must declare the permission in the manifest, and send an intent requesting the user's authorization. The system responds to the intent by showing a detailed management screen to the user.

For details on how to request these permissions, see the SYSTEM_ALERT_WINDOW and WRITE_SETTINGS reference entries.
```

**Comment by hotchemi** [comment]
```java
if (!Settings.canDrawOverlays(this)) {
  Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
  Uri.parse("package:" + activity.getPackageName()));
  activity.startActivityForResult(intent, REQUEST_CODE_PERMISION_SYSTEM_ALERT_WINDOW);
} 

@Override protected void onActivityResult(int requestCode, int resultCode, Intent data) {
   if (requestCode == REQUEST_CODE_PERMISION_SYSTEM_ALERT_WINDOW) {
     if (Settings.canDrawOverlays(this)) {
       // yay!
     } else {
      // denied.
     }
   }
 } 
```

**Comment by shiraji** [comment]
Is this issue trying to implement followings?

XXActivity.java

```java
public void onClick(@NonNull View v) {
    XXActivityPermissionsDispatcher.showSystemAlertWindowWithCheck(this);
}

@Override protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    XXActivityPermissionsDispatcher.onActivityResult(this, requestCode, resultCode, data);
}

@OnPermissionDenied(Manifest.permission.SYSTEM_ALERT_WINDOW)
void onSystemAlertWindowDenied() {
  // denied.
}

@NeedsPermission(Manifest.permission.SYSTEM_ALERT_WINDOW)
void showSystemAlertWindow() {
  // yay!
}

```

XXActivityPermissionsDispatcher.java

```java
static void showSystemAlertWindowWithCheck(XXActivity target) {
  if (!Settings.canDrawOverlays(target)) {
    Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
    Uri.parse("package:" + target.getPackageName()));
    target.startActivityForResult(intent, REQUEST_CODE_PERMISION_SYSTEM_ALERT_WINDOW);
  } 
}

static void onActivityResult(XXActivity target, int requestCode, int resultCode, Intent data) {
  switch(requestCode) {
    case REQUEST_CODE_PERMISION_SYSTEM_ALERT_WINDOW:
    if (Settings.canDrawOverlays(target)) {
      target.showSystemAlertWindow();
    } else {
      target.onSystemAlertWindowDenied();
    }
    break;
  }
}
```

**Comment by hotchemi** [comment]
@shiraji Sorry for the late.
Yes, I'd like to get the best interface and your proposal seems nice.

**Comment by shiraji** [comment]
Thanks for reviewing! Would you mind if I implement this issue?

I think the hardest part is `showSystemAlertWindowWithCheck`. Currently, `ActivityProcessorUnit` does not check which annotation is handled in `addWithCheckBody`.

My current idea is creating 2 helpers that generate `xxWithCheckBody` and ActivityProcessorUnit use these helpers. 

What do you think?

---

It is totally out of topic but the CHANGE log has typo https://github.com/hotchemi/PermissionsDispatcher/commit/d253d15503083e1670345415214817156cdc3976?diff=unified#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3 It should be 2.0.2

**Comment by hotchemi** [comment]
> It is totally out of topic but the CHANGE log has typo d253d15?diff=unified#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR3 It should be 2.0.2

Ah sorry we've not released yet..revered it. Thx!

**Comment by hotchemi** [comment]
And when it comes to impl, your interface looks good.

**Comment by hotchemi** [comment]
I assigned you for this issue :-)

**Comment by shiraji** [comment]
One question about this issue. Do I have to handle this feature for Fragment?

**Comment by hotchemi** [comment]
Do you mean this feature supports Activity and Fragment? Yes.

**Comment by shiraji** [comment]
OK, I will do that as well. I was concerned about the nested fragments. They won't get call `onActivityResult`. See [StackOverFlow thread](http://stackoverflow.com/questions/13580075/onactivityresult-not-called-in-new-nested-fragment-api).

**Comment by hotchemi** [comment]
@shiraji Ah I didn't know that. IMO we must not nest fragments...:D
