### ISSUE TITLE
trying to compile permissionsdispatcher-processor:2.0.1

### ISSUE THREAD

**Issue by OAbdan** [hotchemi/PermissionsDispatcher#53]
Error:Could not GET 'https://jitpack.io/com/github/hotchemi/permissionsdispatcher-processor/2.0.1/permissionsdispatcher-processor-2.0.1.pom'. Received status code 401 from server: Repository not found or unauthorized

**Comment by hotchemi** [comment]
Sorry I just published to jcenter.
