### ISSUE TITLE
@OnPermissionDenied and @OnNeverAskAgain not working properly

### ISSUE THREAD

**Issue by sibeliusseraphini** [hotchemi/PermissionsDispatcher#57]
When I try to use @OnPermisionDenied like this:

```
@OnPermissionDenied({
            Manifest.permission.READ_PHONE_STATE,
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.WRITE_EXTERNAL_STORAGE,
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.RECORD_AUDIO})
public void showDeniedMessage() {}
```

It doesn't generate the correct code, and not even reference my method from PermissionDispatcher.
The behavior that I expected is to call showDeniedMessage for any of these permissions.

The same happens for @OnNeverAskAgain

I will try to work on this tomorrow

**Comment by hotchemi** [comment]
No, specification of the library is not such.
@OnPermissionDenied is called when request of @NeedsPermission which has same string array as arguments is denied.

**Comment by aurae** [comment]
Yeah, as @hotchemi said, your example would trigger these callbacks for a permission request that asks for ALL of these permissions at once. It would be ambiguous to the code generator if it were an "any-of" relationship, since there would be cases where it didn't know which callback to connect to the @NeedsPermission call.

**Comment by sibeliusseraphini** [comment]
We can have another annotation for this case or another parameter that will determine the behavior of the code generator

**Comment by hotchemi** [comment]
@sibeliusseraphini We have no plan to do that. Why do you need it?

**Comment by sibeliusseraphini** [comment]
My use case is this:

My app will only work if the user enable all 3 permissions that my app needs.
When the permission is denied the app will show the same message to the user explaining the these permissions are really required, and when user type check never ask again the app will ask the user to go to the Settings to enable the permissions for the app

We could have a default method for OnPermissionDenied and NeverAskAgain 

This will reduce some boilerplate code

@hotchemi thanks for this great library, I think we should have more annotated library like this to reduce boilerplate code in android and java in general

**Comment by aurae** [comment]
In this case, why don't you specify a `@NeedsPermission` method that requires all of the permissions you need, and then mirror this signature in your catch-all `@OnPermissionDenied` and `@OnNeverAskAgain` callbacks? This way, you can check for all permissions at the same time, and fall back to a single callback in case of denial.

**Comment by sibeliusseraphini** [comment]
@aurae thank, I will try that

**Comment by ubarua123** [comment]
I had a small doubt chaining permissions. I have a method with `@NeedsPermission` with multiple permissions and another method with `@OnPermissionDenied`  with the same signature of permissions. Question is, how will I know which ones got denied, which ones got accepted?
