### ISSUE TITLE
Request Permission  About Dialog

### ISSUE THREAD

**Issue by chond** [hotchemi/PermissionsDispatcher#58]
if  we request two permission at the same time ,we agree one deny the other one , the  next  time , we   request  permission ,Should we only request  the last time we deny this permission , but not all , how do you  think ?

**Comment by aurae** [comment]
IIRC, the framework keeps track of the granted permissions inside of a multi-permission request. That is, if you have a method annotated with `@NeedsPermission({Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE})`, and the user grants access to the camera, but **not** the external storage, the framework will keep the camera permission as granted internally. The next time the method is called, only `WRITE_EXTERNAL_STORAGE` is being requested again, even though `CAMERA` is part of the request.

I can't verify this with a device right now, though.

**Comment by chond** [comment]
yeah ,you are right,but if next time request,about dialog,we can do ,We only show the last rejected this permissions, but agree the permissions is not display , this is better?

**Comment by hotchemi** [comment]
@chond Isn't it current specification? Have you tested on your app?

**Comment by chond** [comment]
@hotchemi   yes, of course, but did not get what I want  results

@NeedsPermission({Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE})
void showCameraAndFile() {
        Intent intent = new Intent(this, PhotoSelectActivity.class);
        startActivityForResult(intent, RQCODE_PHOTO_SELECT);
}

@OnShowRationale({Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE})
void showRationaleForCameraAndFile(PermissionRequest request) {
        showCameraDialog(getResources().getString(R.string.permission_camera_photo), request);
}

@OnPermissionDenied({Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE})
void showDeniedForCameraAndFile() {

}

@Override
public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        ShopOtherActivityPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
}

private void showCameraDialog(String content, final PermissionRequest request) {
        String ok = getResources().getString(R.string.permission_ok);
        String cancel = getResources().getString(R.string.permission_deny);
        String title = getResources().getString(R.string.permission_title);
        new MaterialDialog.Builder(this).title(title).content(content).positiveText(ok).negativeText(cancel).callback(new MaterialDialog.ButtonCallback() {
            @Override
            public void onPositive(MaterialDialog dialog) {
                request.proceed();
            }

            @Override
            public void onNegative(MaterialDialog dialog) {
                request.cancel();
            }
        }).cancelable(false).show();
    }

**Comment by aurae** [comment]
The behaviour I described is referring to the implementation of runtime permissions in the Android platform, which is out of scope for this library. Until there is more customizability for how apps show the system dialogs for multi-permission requests (i.e. so that you could specify "either accept all, or deny all"), there's nothing that can be done about the behaviour that PermissionsDispatcher is exposing.

**Comment by hotchemi** [comment]
Thanks for your report.
