### ISSUE TITLE
Add embedded lint checks to prevent direct access to permission-protected methods

### ISSUE THREAD

**Issue by aurae** [hotchemi/PermissionsDispatcher#59]
This enhancement is derived from #56, in which the OP asked for a more convenient way to use PermissionDispatcher's delegate pattern. In my opinion, it would make sense to embed custom lint checks that prevent users from directly invoking methods annotated with `@NeedsPermission`. Furthermore, another check would raise a warning (preferably an error) if the call to the delegate object's `onRequestPermissionsResult()` method is omitted in the respective Activity / Fragment method.

```java
@NeedsPermission(Manifest.permission.CAMERA)
void useCamera() {
}

// Somewhere else...
void onCameraButtonClicked() {
    this.useCamera();    // This line would raise a lint error ("Trying to access permission-protected method directly", for instance)
}
```

[Futher reading (tools.android.com)](http://tools.android.com/tips/lint-custom-rules)

**Comment by hotchemi** [comment]
Seems nice!

**Comment by shiraji** [comment]
Are you guys expect lInt check done by Kotlin?

**Comment by aurae** [comment]
Personally, I'm indifferent to the language used to implement the lint checks, but I'd welcome a contribution written in Kotlin, for sure!

**Comment by shiraji** [comment]
One issue of writing lint in Kotlin is I don't know how to include kotlin
runtime.jar in lint.jar.

2016年1月15日(金) 20:22 Marcel Schnelle <notifications@github.com>:

**Comment by aurae** [comment]
That's true, I haven't looked into that as well, which is why I was interested in that. Java works just as well for this task, though, seeing as all references keep to using Java for custom lint rules. So in case you are interested in implementing this, Java works just fine :+1:

**Comment by shiraji** [comment]
OK, I will do this then in Java. I don't think this lint will be huge. We will be able to rewrite this in Kotlin if we find a way to include kotlin runtime in lint.jar.

**Comment by aurae** [comment]
True. Thank you for the offer!

**Comment by hotchemi** [comment]
Btw, can it be bundled with artifact?

**Comment by shiraji** [comment]
Not sure how, yet but according to [this documentation](http://tools.android.com/tech-docs/new-build-system/aar-format), aar is able to include lint.jar.

**Comment by hotchemi** [comment]
ic.

**Comment by shiraji** [comment]
Maybe, we could use [the idea from Timber](https://github.com/JakeWharton/timber/blob/master/timber/build.gradle#L45-L55).

**Comment by aurae** [comment]
Timber would have been the primary source of guidance for me as well, let's follow that approach.

**Comment by a11n** [comment]
@shiraji do you know a way to check Kotlin code via lint? If so, **please tell me**, cause AFAIK there is no way hence there is no `KotlinScanner`available. (But this information may be deprecated)

This is one reason people hesitate to use Kotlin in enterprise projects, cause there's no Lint support. It would be a big milestone if you'll find a way!

**Comment by hotchemi** [comment]
@a11n It might be better to discuss on [Kotlin Discussions](https://discuss.kotlinlang.org/).

**Comment by shiraji** [comment]
check this https://youtrack.jetbrains.com/issue/KT-7729

**Comment by shiraji** [comment]
> Furthermore, another check would raise a warning (preferably an error) if the call to the delegate object's onRequestPermissionsResult() method is omitted in the respective Activity / Fragment method.

Meaning `@OnShowRationale` does not have matching `@NeedsPermission`?

**Comment by aurae** [comment]
That's a good idea as well, but it isn't what I meant. I was referring to lint raising an error if you use a `@NeedsPermission` method inside a class, but do not call through to `YourClassPermissionsDispatcher.onRequestPermissionsResult()`. I'm not sure how this would be detectable, though.

**Comment by shiraji** [comment]
OK, I got it. 

The lint checks that there is a method call with `YourClassPermissionDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);` in the class which has `@NeedsPermission` (or `@RuntimePermission`). 

I think it is not that bad. There is a way to traverse all method call in lint check, AFAIK.

I will implement this one, too. 

> @OnShowRationale which does not have matching @NeedsPermission?

**Comment by aurae** [comment]
> @OnShowRationale which does not have matching @NeedsPermission?
Yes, as far as I remember the processor isn't handling this case itself, so it would be nice to have a lint warning raised for this case. Thank you!

**Comment by aurae** [comment]
Didn't mean to close this, sorry!

**Comment by shiraji** [comment]
Let me reopen for another lint check.

**Comment by hotchemi** [comment]
Cool!

**Comment by hotchemi** [comment]
Done!
