### ISSUE TITLE
Possibility to ask for several permissions in a chain?

### ISSUE THREAD

**Issue by Rainer-Lang** [hotchemi/PermissionsDispatcher#61]

**Comment by aurae** [comment]
If you specify multiple permissions inside the annotations provided by PermissionsDispatcher, the underlying framework will ask the user for approval on each of them consecutively. Is this what you're referring to?

**Comment by Rainer-Lang** [comment]
And I will get different rationale before each of the permission dialogs? Would be great. :-)
How about the sequence of the dialogs?

**Comment by hotchemi** [comment]
No, the specification is here.
https://github.com/hotchemi/PermissionsDispatcher/issues/57#issuecomment-163458466

**Comment by aurae** [comment]
I see. If you'd like to show the system permission dialog and the corresponding rationales alternately, then this would only be possible by requesting those permissions one by one and proceeding the chain in each `@NeedsPermission` method itself.

**Comment by Rainer-Lang** [comment]
@aurae Thanks. I will try it.
