### ISSUE TITLE
PermissionsDispatcher Class

### ISSUE THREAD

**Issue by hmedat2008** [hotchemi/PermissionsDispatcher#62]
Why all methods in ActivityPermissionsDispatcher not public method?

Can you make it public methods

**Comment by aurae** [comment]
The code generated by PermissionsDispatcher always resides in the same package that the annotated Activity/Fragment classes live in, which is why those classes are able to use the non-public `static` methods from the generated code. We chose to reduce visibility of these methods as much as possible to prevent abuse and highlight the tight connection that an annotated class has to its generated counterpart. I don't see why we should relax those restrictions.

**Comment by hmedat2008** [comment]
I agreed with you, but I have another  implementation before using PermissionsDispatcher methods, So I need to put all my code in single class, 

So I need from you to give me an option to set modifier (public,default,protracted) of those methods,

**Comment by aurae** [comment]
Can you go into a little detail on the implementation you're referring to? I'd like to get a better understanding about how it would be beneficial to add something like this to the library.

**Comment by hmedat2008** [comment]
I have Class name DialogHelper, I put all my implementations inside it, 
My Implementation, to add another dialog before show native permission dialog like this

class DialogHelper{
  public static void showSmsForRegisterPage(final RegisterFragment fragment) {
        Permission permission = Permission.READ_SMS;
        if (PermissionDialogUtil.hasPermission(fragment, permission)) {
            fragment.showSms();
            return;
        }

        if (permission.isNeverAsk()) {
            fragment.onShowSmsNeverAsk();
            return;
        }

        PermissionDialogUtil.showDialog(fragment, permission,
                new MaterialDialog.ButtonCallback() {
                    @Override
                    public void onPositive(MaterialDialog dialog) {
                        RegisterFragmentPermissionsDispatcher.showSmsWithCheck(fragment);
                    }

                    @Override
                    public void onNegative(MaterialDialog dialog) {
                        fragment.onShowSmsDenied();
                    }
                });
    }

}

Permission is an enum I created it to set all details permissions inside it, 

The DialogHelper class I need to repeat it, inside each package I used a permission inside it's classes

This is my problem basically

**Comment by hotchemi** [comment]
We have no plan to do that.
We constrain generated codes to being called only annotated class itself.
IMO, in your case you should modify application codes to being them more loose coupling.

**Comment by hmedat2008** [comment]
I know your library do 1 2 3 4, but I need to give ability to change modifiers of methods, 

Thant all My needs
