### ISSUE TITLE
Include Build.VERSION_CODES into library-sources.jar

### ISSUE THREAD

**Issue by aurae** [hotchemi/PermissionsDispatcher#64]
At the moment, test cases are failing because of a missing link inside the JAR file which is generated for the processor's test suite:

```
processor\src\test\libs\library-sources.jar(permissions/dispatcher/PermissionUtils.java):18: error: cannot find symbol
import static android.os.Build.VERSION_CODES.KITKAT_WATCH;
^
  symbol:   static KITKAT_WATCH
  location: class
```

This is related to the recent addition of SDK-level-dependent auto-granting of permissions on devices older than the permission itself. We should either remove the dependency on these constants (and replace them with their actual values), or bundle `Build.VERSION_CODES` into the generated jar.

**Comment by hmedat2008** [comment]
Any updates?

**Comment by hotchemi** [comment]
Well, is this permission needed to be tested...? I'm not sure but the dialog doesn't show on watch device right?

**Comment by aurae** [comment]
The output above was just an example of one missing version code reference, it is the same for the others. Because we have switched to SDK-level dependent permission checks, those constants need to be accounted for when testing, or else the unit test environment can't find them (which causes all those tests relying on that code to fail).

**Comment by aurae** [comment]
f41a38c8 removes `Build.VERSION_CODES` from `PermissionUtils`. Shintaro, could you check out the latest master & verify that the test suites are passing with the latest `library-sources.jar`?

**Comment by hotchemi** [comment]
@hmedat2008 @aurae Just releases 2.0.2. Thanks!
https://github.com/hotchemi/PermissionsDispatcher/releases/tag/2.0.2

**Comment by hmedat2008** [comment]
Thank you so muck :) , Great library and great guys :D
