### ISSUE TITLE
[Discuss] Move to Java8 from Kotlin

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#66]
I'm definitely not sure this movement is good for product...so I'd like to discuss about it.

Yes, Kotlin is the nice language. But when it comes to the performance, it's still less faster than Java8.
I've not verify at all but I saw one blog post which tastes the performance of each JVM languages.

![image](https://cloud.githubusercontent.com/assets/471318/12068467/4382625c-b052-11e5-82b3-8061d30ef6f6.png)

If it's true, I'd like to focus on the merit of the user.
And some other famous libraries that use apt don't adopt better JVM language for processor.

Umm, actually I'm just saying but how do you think about it?

**Comment by shiraji** [comment]
Could you give us the URL for the blog post? You are talking about compile time performance, right?

**Comment by hotchemi** [comment]
Sorry, that's my mistake.
Yes, it's just the compile time problem and there is no difference(I wish) in runtime performance.

**Comment by hotchemi** [comment]
But I think there is no need to be kotlin...

**Comment by shiraji** [comment]
Choose language whatever you want.  But, before you try to work on that, could you merge or review [my pull request](https://github.com/hotchemi/PermissionsDispatcher/pull/65)? I removed a lot of duplicated code. It will help you rewriting code.
