### ISSUE TITLE
Incorrect handling of interrupted permissions flow

### ISSUE THREAD

**Issue by wlowe** [hotchemi/PermissionsDispatcher#68]
It seems like this library should handle the case where the flow doesn't get a chance to complete.  As per the API docs, when this happens, ```onRequestPermissionsResult()``` is called with an empty list of permissions and grants.  This is to be treated as a cancel.

However ```PermissionUtils.verifyPermissions()``` interprets the empty grant list as valid (since there aren't any items with rejected permissions in the list).  We can easily work around this by embedding the check in our code but it's a bit redundant to do every time.

**Comment by aurae** [comment]
How would one cause the cancellation case to happen? Do I tap outside of the permission dialog in order to close it? Do I exit the app via the home button? The docs indeed point at the cancel case, so we should consider supporting it for sure. Do you have any more information on this?

**Comment by hotchemi** [comment]
I guess it never happens because it doesn't make sense.right?
Which case should you put empty list to arguments?

**Comment by wlowe** [comment]
We ran into this case because we're forced to ask for permissions in one of the initial screens of our app.  Backgrounding the app via the home button then re-entering causes ```onRquestionPermissionsResult()``` to be called with the empty lists for some reason.

**Comment by hotchemi** [comment]
```diff
    public static boolean verifyPermissions(int... grantResults) {
+        if (grantResults.length == 0) {
+           return false;
+       }
        for (int result : grantResults) {
            if (result != PackageManager.PERMISSION_GRANTED) {
                return false;
            }
        }
        return true;
    }
```

**Comment by hotchemi** [comment]
@wlowe Any update?

**Comment by hotchemi** [comment]
Please reopen if you still have the problem.
