### ISSUE TITLE
Anomaly between speakerdeck slide and github docs

### ISSUE THREAD

**Issue by aprofromindia** [hotchemi/PermissionsDispatcher#71]
There is a slight anomaly between the linked speakerdeck slides and the github doc on whether to call: -

super.onRequestPermissionsResult(requestCode, permissions, grantResults); in the public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) method.

A proper update could help a lot of people.

**Comment by hotchemi** [comment]
@aprofromindia The slide is old so I deleted and updated the link. Thx.
