### ISSUE TITLE
Release problem.

### ISSUE THREAD

**Issue by hotchemi** [hotchemi/PermissionsDispatcher#74]
[Release to jcenter](https://github.com/hotchemi/PermissionsDispatcher/wiki/Release-to-jcenter) sometimes fail to upload library module. And when we move to library dir and execute this script again, new library artifact is uploaded...

**Comment by shiraji** [comment]
It happens in my library in most time. I really hate this...In my case, I uploaded modules, separately. Like this.

```bash
./gradlew clean build generatePomFileForMavenPublication :processor:bintrayUpload -PbintrayUser=hotchemi -PbintrayKey={$bintrayKey} -PdryRun=true
./gradlew :library:bintrayUpload -PbintrayUser=hotchemi -PbintrayKey={$bintrayKey} -PdryRun=true
```

**Comment by hotchemi** [comment]
Umm, it might be the bug of novoda/bintray-release.

**Comment by hotchemi** [comment]
There is no solution and we have to work around with...
