### ISSUE TITLE
Handling permission is denied/prohibited case in onRequestPermissionResult

### ISSUE THREAD

**Issue by daisy1754** [hotchemi/PermissionsDispatcher#8]
Current implementation of PermissionDIspatcher generates code that executes @ShowsRationale annotated method inside onRequestPermissionResult when the permission is not granted. I think it's a bit weird (well, the Activity#shouldShowRequestPermissionRationale()  is weird API in the first place...)

[The doc](https://developer.android.com/preview/features/runtime-permissions.html#explain-need) explains the motivation behind Activity#shouldShowRequestPermissionRationale() is to help developers show custom message to explain users why the permission is necessary. IMO, this message only makes sense if you show permission dialog just after the message (see [sample code by google](https://github.com/googlesamples/android-RuntimePermissions/commit/e459ec4653e91b734fb2569e88b71fd278ce8171#diff-fc1458af97f4fa524fc5b5121166830aR158))

On the other hand, onRequestPermissionResult() is called after developer requested permission. Additionally, at the time of onRequestPermissionResult(), developer may not be able to re-ask the permission (e.g., user select 'never ask me' option, the device policy prohibits the permission) so showing rational for permission doesn't actually help users :)

**Comment by hotchemi** [comment]
Yup that's exactly. This feature was implemented from 1.0.0 just as experimental but this is my failure.
On the other hand, some people request me to the feature which insert an action when user deny permission, so I'm gonna add another annotation.
Anyway I'm gonna fix the issue. Thx!

**Comment by hotchemi** [comment]
1.0.1 was out! Really thx.
