### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by prashantwosti** [hotchemi/PermissionsDispatcher#82]
Since 2.0.4, I'm getting 
```
java.lang.UnsupportedClassVersionError: permissions/dispatcher/Runtime Permissions : Unsupported major.minor version 52.0
```
rolled back to 2.0.3 and everything is fine.

**Comment by hotchemi** [comment]
Could u give me a full stack trace?
I think it might be the problem of JDK version. Could u give me a output of `java -version`?

**Comment by hotchemi** [comment]
@prashantwosti 
Could u give me a full stack trace?
I think it might be the problem of JDK version. Could u give me a output of `java -version`?

**Comment by ogapants** [comment]
Me too.
My JDK version was `1.7.0_79`, but succeeded after update to `1.8.0_66`.
It's my stack trace.
```
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.UnsupportedClassVersionError: permissions/dispatcher/RuntimePermissions : Unsupported major.minor version 52.0
```

**Comment by shiraji** [comment]
Are we able to remove these 2 lines?

https://github.com/hotchemi/PermissionsDispatcher/commit/7235d1c816d897befd31f88bd362bb41bd618ad5#diff-5382f29622a37ec83f27f1d848d143eaL6

**Comment by hotchemi** [comment]
Yup, my recommend is using jdk 8 but we use Kotlin for processor so we can support older jdk.
I'm gonna release minor version update.

**Comment by hotchemi** [comment]
@prashantwosti Do you need a fixed version? Or did u decided to update jdk version?

**Comment by prashantwosti** [comment]
@hotchemi, A fixed version would be better. 
Due to time limit, I had to downgrade to 2.0.3.

**Comment by hotchemi** [comment]
@prashantwosti 2.0.3 has a but which @OnNeverAskAgain is never called, please use 2.0.2.
I'm gonna release 2.0.5 tonight in JST.

**Comment by prashantwosti** [comment]
@hotchemi Oh. So I was going hit a brick while testing. Thanks. Will do accordingly.

**Comment by hotchemi** [comment]
@prashantwosti Released 2.0.5. Thanks.

**Comment by prashantwosti** [comment]
@hotchemi i just noticed that @OnNeverAskAgain is never called on 2.0.5?

**Comment by shiraji** [comment]
@prashantwosti why don't we do this in different issue like #78? This was the issue for JDK1.8 not v2.0.5.

**Comment by prashantwosti** [comment]
@shiraji created a new issue. sorry :)

**Comment by shiraji** [comment]
No worry! Thanks for reporting this.
