### ISSUE TITLE
Asking for permission in onResume might cause infinite loop

### ISSUE THREAD

**Issue by kenshin171** [hotchemi/PermissionsDispatcher#90]
Hi, not exactly a bug, BUT i think this should be documented. Asking for permissions in onResume will cause an infinite loop when user ticks "never ask again" and denies the permission. After the user returns to the activity from the permissions dialog box onResume is called and it asks for permission again. It seems that onResume is always called after returning from a permission request check. Below is a very simple code snippet that demonstrates this issue.

```java
    int i = 0;
    @Override
    protected void onResume() {
        super.onResume();
        MainActivityPermissionsDispatcher.enableLocationWithCheck(this);
        i++;
    }

    @NeedsPermission(Manifest.permission.ACCESS_FINE_LOCATION)
    void enableLocation() {
         //do something with location
    }

    @OnNeverAskAgain(Manifest.permission.ACCESS_FINE_LOCATION)
    void showNeverAskForLocation() {
        App.ToastMessage("Never ask again! "+i,this);
    }
```

This issue can be solved by putting the permission request call in onStart instead of onResume as onStart is called only once for the activity as documented in http://developer.android.com/training/basics/activity-lifecycle/pausing.html.
Below is the better place to call a method with permission request when you want the permission request to be asked on activity start.
```java
  @Override
    protected void onStart() {
        super.onStart();
        MainActivityPermissionsDispatcher.enableLocationWithCheck(this);
    }
```

**Comment by hotchemi** [comment]
Interesting, I've never tested that case. We'll investigate about it and do documentation. Thx!

**Comment by aurae** [comment]
Good catch!

**Comment by hotchemi** [comment]
I added this issue link to wiki. https://github.com/hotchemi/PermissionsDispatcher/wiki/Checklist
Thx for your report @kenshin171 !

**Comment by shiraji** [comment]
Another lint check? :smile:

**Comment by hotchemi** [comment]
Lint master :heart_eyes:

**Comment by codebased** [comment]
so whats the solution - where should be checked for required permissions ? I have just faced this problem

**Comment by kenshin171** [comment]
> This issue can be solved by putting the permission request call in onStart instead of onResume as onStart is called only once for the activity as documented in http://developer.android.com/training/basics/activity-lifecycle/pausing.html.
Below is the better place to call a method with permission request when you want the permission request to be asked on activity start.

**Comment by codebased** [comment]
yup thanks!

**Comment by t894924815** [comment]
thanks!!!but why it behave like this?

**Comment by hotchemi** [comment]
@t894924815 this is caused inside of Android permission framework so we dunno... 😅

**Comment by kenshin171** [comment]
More like this is how the android activity lifecycle works.

**Comment by farmazon3000** [comment]
Why do we even need to start a dialog? Can't we show sth that doesn't trigger onPause/onResume?

**Comment by farmazon3000** [comment]
Same issue on google samples:
https://github.com/android/location-samples/issues/83
